### ISSUE TITLE
Debugger TIA Tab Positions Are Wrong

### ISSUE THREAD

**Issue by Omegamatrix** [stella-emu/stella#210] opened 2017-08-22 03:56 UTC
It looks like the positions are listed -1 to where they should be. For example if I have P0 as 1 copy, and positioned to the left edge of the screen it should by at pos #0 in the debugger, but the position it lists is 159.

**Comment by thrust26** [comment] 2017-08-22 07:36
Confirmed. All position values are 1 lower than in 4.7.2.

**Comment by DirtyHairy** [comment] 2017-08-22 07:42
Thanks 😉 Apart from the question where the details should go, this sounds like an easy fix, I'll take a look later.

**Comment by DirtyHairy** [comment] 2017-08-22 13:19
Fixed in commit 5661b245 . The issue was caused by the fact that the decoding delay starts ticking down the next clock **after** the actual decoding event. The bug in consistent in that it affects both getting and setting the position :smiling_imp:

**Closed by DirtyHairy** 2017-08-22 13:19 UTC
Labels: bug
