### ISSUE TITLE
Games randomly flicker after entering and exiting a menu

### ISSUE THREAD

**Issue by lordlouckster** [stella-emu/stella#762] opened 2021-01-30 08:15 UTC
https://user-images.githubusercontent.com/57062013/106351288-120f7300-62e4-11eb-8779-d4849e983889.mp4

**Comment by thrust26** [comment] 2021-01-30 09:47
Which OS are you on? And which renderer are you using?

**Comment by anonymous7002** [comment] 2021-01-30 10:10
Windows 10, OpenGL

**Comment by thrust26** [comment] 2021-01-30 10:29
@sa666666 I cannot reproduce this, but I know you are working on something similar.

**Comment by sa666666** [comment] 2021-01-30 13:54
Try Direct3D.  OpenGL is not as well supported in Windows.

**Comment by anonymous7002** [comment] 2021-02-04 12:34
Sometimes, it may flicker between the game and the last selected menu box. It shows the game when the mouse is on a menu entry and the box when outside of one.

**Comment by anonymous7002** [comment] 2021-02-04 12:35
https://user-images.githubusercontent.com/57062013/106893390-2beef280-66f6-11eb-89a0-af96054383bc.mp4

**Comment by sa666666** [comment] 2021-02-04 12:57
Have you tried Direct3D?  As I said earlier, OpenGL isn't really well supported in Windows.  Also, which video card, and are you using the latest drivers?

**Comment by anonymous7002** [comment] 2021-02-07 07:38
I tried Direct3D, no luck. Intel HD Graphics 4600.

**Comment by anonymous7002** [comment] 2021-02-13 16:06
It also appears when the game is not loaded.

**Comment by thrust26** [comment] 2021-04-15 14:37
Looks like a driver problem to me (double buffering?). Are you using the latest Intel driver version?

**Comment by thrust26** [comment] 2022-12-17 10:05
@anonymous7002 Is that still an issue?

**Comment by sa666666** [comment] 2022-12-30 22:45
I can't reproduce this, and we haven't heard back from the original reporter.  So I guess we can close this one?

**Comment by thrust26** [comment] 2022-12-30 22:48
Same here. Agreed.

**Comment by thrust26** [comment] 2023-03-04 21:45
So let's close this.

**Closed by thrust26** 2023-03-04 21:45 UTC
Labels: bug, target 6.7
