### ISSUE TITLE
NTSC/PAL autodetection not being properly used

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#32] opened 2016-12-11 02:42 UTC
The old NTSC/PAL autodetection isn't used, only the one from the new core.  However, the new core autodetection is sometimes mistaking PAL for NTSC and vice-versa.  The two need to be integrated, since the old way was working nearly 100%.

**Comment by thrust26** [comment] 2016-12-11 08:33
What's the algorithm used?

A simple idea would be:
Usually the first few frames do not create a valid VSYNC signal, so those should be ignored. Only if two or more consecutive frames create (about) the same amount of scanlines,  the resulting number should be used for detection.

Additional logic (e.g. color values used, size of visible screen) might help in corner cases, but I am not sure, if that really helps improving the result. Except for a repeated odd scanline count, which pretty clearly indicates an NTSC game.

**Comment by DirtyHairy** [comment] 2016-12-11 10:58
@sa666666 That's to be expected, the algorithm I implemented for autodetecting TV mode was just a quick shot to get things going (6502.ts does not currently support autodetect).

The current algorithm for Frame and TV mode detection currently works like this:

 * Before starting emulation, Stella runs the emulation for a bunch of frames (60 or so, would have to check the code to be sure) and counts how many frames were identified by the core as PAL and how many were detected as NTSC. Emulation is then restarted with the "winner" selected. This was already there before I added the new code. The rest below is part of the new core and lives in the FrameManager class.

* The FrameManager starts out in NTSC mode. At the end of each frame ("frame" in this context means everything = vsync + vblank + kernel + overscan), the code checks whether the total line count matches PAL or NTSC mode up to a certain tolerance. If yes, the mode is changed accordingly (or preserved, if the matched mode is unchanged).

 * The frame detection algorithm is a state machine that transitions like this: `waitForVsync` -> `vsync` -> `vblank` -> `kernel` -> `overscan` -> `vsync`

* `waitForVsync` -> `vsync` is triggered by setting VSYNC

* `vsync` -> `vblank` is triggered by clearing VSYNC

* `vblank` -> `kernel` is triggered by either clearing VBLANK exceeding a line limit, but not before a underscan limit is reached.

* `kernel` -> `overscan` is triggered by reaching a line limit (comprised of the minimum visible height and a visible piece of overscan).

* `overscan` -> `waitForVsync` is triggered by reaching a line limit

* Setting VSYNC  anywhere other than `waitForSync` will finish the current frame and return to `waitForVsync`

* If a number of frames (60 or so) passes without VSYNC being touched, the algorithm gives up and ignores VSYNCs altogether. From this point, the state machine transitions only between `vsync`, `kernel` and `overscan`.

I think this algorithm can still be improved by just tuning the parameters, all of 
 which are encoded in the `enum` at the start of `FrameManager.cxx`.

**Comment by thrust26** [comment] 2016-12-11 11:27
That sounds pretty smart. Maybe checking for odd scanlines should be added, especially in corner cases.

BTW: 
Do you have a list of games which are critical to detect (or detected wrong)? I suppose most are prototypes, right?

**Comment by DirtyHairy** [comment] 2016-12-11 13:11
Thinking about what I wrote, I guess my naive TV mode autodetect could break at least for games that do not VSYNC properly. Without VSYNC, the frame detection algorithm is much more dependent on scanline counts and might fail to leave NTSC mode for PAL games. If we can identify some testcases, I think this can be improved.

Regard your comment above, Thomas: this may sound stupid, but what exactly do you mean by "279 lines displayed as 558"? The prototypes look OKish to me on the new core. TV mode might be off for Desert Falcon and Dungeon, but that's it (however, hard to tell as the old core doesn't run DF at all, and Dungeon is detected as PAL, just as the new core). Rush hour displays something that looks like garbage above and below the track, but it is complete rubbish on the old core, so I can't crosscheck.

**Comment by thrust26** [comment] 2016-12-11 14:02
With ALT+L you can enable an info display, which also displays the scanlines and the detected mode.

For me, all prototypes (besides Rush Hour) run on the old core.
- DF should be detected as NTSC (wrong in both cores)
- Dungeon should be NTSC (wrong in new core)
- Rush Hour shows almost 4000(!) scanlines in new core (doesn't run in old core)
- Millipede should probably be NTSC (judging by the colors), but that's hard to detect
- Save The Whales should be NTSC from the scanlines (but PAL from the colors)
- Wings clearly has PAL scanlines but NTSC colors (identified as PAL on both cores)

Not sure why you get completely different results from the old core.

**Comment by DirtyHairy** [comment] 2016-12-11 14:12
I'll have to look into this later, but it seems the displayed scanline count is just wrong 😉

**Comment by thrust26** [comment] 2016-12-11 14:15
Could be.

BTW: There may be some games (protos), which do not use VBlank. This works, as long as the screen is black and the TV is not tuned too bright.

**Comment by thrust26** [comment] 2016-12-11 15:20
This one is jumping up and down in the new core (scanline count constantly changing). And one version sometimes shows a scan line count above 500.
[Save Our Ship.zip](https://github.com/DirtyHairy/stella/files/644522/Save.Our.Ship.zip)

**Comment by DirtyHairy** [comment] 2016-12-11 20:04
After taking a closer look, I have indeed found a bug b9e2fc9 and fixed it: VSYNC during kernel would step to `overscan` instead of `waitForVblank`. This fixes the protos which showed a scanline count of about 500: these did VSYNC during kernel, and the result would be that each other frame would be gobbled up by VSYNC (the way it is implemented now, "scanline count" refers to the total frame, including vsync, vblank and overscan).

With this fix, all protos and Dark Mage run as you describe they should, with the exception of Rush Hour. This one looks plain broken and spends about 3600 lines in vsync. A log of  the state machine for Rush Hour looks like this (the number behind the @ is the line count spent in this state, and the states are numbered in the order I wrote them down above).
```
frame complete @ 212 (3931 total)
state change 3 -> 4 @ 212
state change 4 -> 0 @ 10
vsync 0 -> 1: state 0 @ 3676
state change 0 -> 1 @ 3676
vsync 1 -> 0: state 1 @ 3
state change 1 -> 2 @ 3
state change 2 -> 3 @ 30
frame complete @ 212 (3931 total)
```
The result is that RH works, but at massively reduced frame rate (and the timing therefore is massively off, see #10).

Robin Hood jumps because it alternates between 2 frames @ 48 lines vblank and 2 frames @ 32 lines vblank. Setting the tolerated underscan to zero fixes this, but of course, this will break other games. I'm not sure what to do about that one.

Thomas, can you build from source? Then you could recheck with the current git version of Stella.

**Comment by thrust26** [comment] 2016-12-11 20:26
That VSYNC thing is weird. What do you mean exactly with "VSYNC during kernel"? I doubt any game will enable VSYNC during kernel display, so I don't know what you mean.

Don't worry about Rush Hour, I am pretty sure it doesn't run on real hardware too. 

No, I currently can't build from source. Too much hassle. But I was hoping for another test release soon. :)

**Comment by DirtyHairy** [comment] 2016-12-11 20:44
:smirk: With "vsync in kernel" I mean that the game outputs too few display lines and sends vsync when it should still be running its kernel and outputting display lines (according to proper timing). It gets more clear if you look at the log for Desert Falcon (which is still detected as PAL, sorry, my bad):
```
frame complete @ 245 (287 total)
state change 3 -> 1 @ 245
vsync 1 -> 0: state 1 @ 4
state change 1 -> 2 @ 4
state change 2 -> 3 @ 38
vsync 0 -> 1: state 3 @ 245
frame complete @ 245 (287 total)
```
The game is 245 lines into the visible frame region when it starts sending VSYNC, so that's forcing the state machine to finish the frame and start again to wait for VSYNC to end.

As to why DF is detected as PAL instead of NTSC, that is because the total line count per frame is 301 and 327 in the first two frames and 287 after that. The first two frames cause the code to lock onto PAL, and 287 is out of the tolerance window of +- 20 scanlines in which the algorithm would treat it as a valid frame for any TV mode. Even if the tolerance window were increased, the result would not change because 287 is the exact middle between PAL (312) and NTSC (262).

**Comment by thrust26** [comment] 2016-12-11 20:56
IMO you should completely ignore the first two frames. Usually there is just initialization code running.

287 is an odd number, so that can be used as a tie breaker.

**Comment by DirtyHairy** [comment] 2016-12-11 21:00
Ignoring the first few frames sounds like a good idea. What exactly is the reasoning behind the even vs. odd thing?

**Comment by thrust26** [comment] 2016-12-11 21:01
PAL looses color on odd frames, so all PAL games take care for an even number.

**Comment by DirtyHairy** [comment] 2016-12-11 21:16
Interesting. I guess I have to read up on TV signals one of these days. So, what do you think of modifying the algorithm for mode detection like this:

* The algorithm starts in 'unconfirmed' NTSC
* The first 5 frames are ignored altogether
* If mode is 'confirmed': line counts within the tolerance window cause the mode to change
* If mode is 'unconfirmed: line counts both within and without the tolerance window cause the mode to change, but for line counts outside the tolerance window and between PAL and NTSC, odd frames always are treated as NTSC
* After five consecutive frames in one mode, 'unconfirmed' changes to 'confirmed'

**Comment by thrust26** [comment] 2016-12-11 21:23
I quite don't get point #3. Do you mean the **opposite** mode tolerance window? And combined with point #5, does this mean that the mode can change later on (e.g. if the ROM is switched into a different mode)?

**Comment by DirtyHairy** [comment] 2016-12-11 21:29
Exactly, in confirmed mode, the mode changes if the line count falls within the opposide mode tolerance window (it just stays the same if it falls within the window of the current mode). That's how it is now, so already now, the new core would be able handle mode hotswitch.

**Comment by thrust26** [comment] 2016-12-11 21:41
Sounds good. 

Don't forget to to disable the algo after the user (or the game properties) actively selected a mode.

**Comment by sa666666** [comment] 2016-12-11 22:55
I'm ready for a new test release whenever you are.  Just create a new tag and let me know, and I can do the builds and upload, as before.

**Comment by sa666666** [comment] 2016-12-11 23:00
I should also add something about the display that pops up when you press 'Alt+L'; the framerate that is shown is incorrect.  For example, if the ROM is NTSC it will always show 60fps, and PAL will be 50Hz.  With the old core, the framerate is calculated based on the scanline count.  I still need to do this, since this framerate is passed on to other parts of the code (particularly the sound code, to keep it in sync).  This will fix https://github.com/DirtyHairy/stella/issues/10 as well.

**Comment by DirtyHairy** [comment] 2016-12-13 11:41
After analyzing #28, I have another change to frame detection in the pipeline that I would like to include in the next prerelease. This will stabilize games with shifting vblank timings and fix #28 and also Robin Hood. I think I'll find time to do that tonight. After that, I'm ready to go for another release :smirk:

**Comment by thrust26** [comment] 2016-12-13 11:52
There are no rules for VBlank, except that it should be enabled for "some" time. With more modern CRTs, the time required for vertical retrace is massively reduced so large part of the vertical blank interval is used for data transmission (e.g. teletext). And with normal brightness, a black screen serves the same purpose as VBlank enabled.

Probably you should remove "vblank" from your state machine. 
@sa666666 Does the old core use that state at all?

**Comment by DirtyHairy** [comment] 2016-12-13 12:18
I have also thought about removing the dependency on vblank before. At the moment, the algorithm uses vblank as the marker to identify where the visual frame starts (and, in absence of vsync, to synchronize). The alternative would be to use start the frame with a fixed offset starting from vsync on of vsync off. What do you think? Would that make sense?

My pending change is a slightly more dynamic version of this: after identifying the visual frame start (and observing the same offset for several frames in a row), the code switches to a fixed offset and only becomes dynamic again if it observers deviation from this offset for several frames in a row.

**Comment by thrust26** [comment] 2016-12-13 12:36
If a game doesn't vsync, it wouldn't work on hardware anyway. So synchronizing and frame start both have to happen at vsync. And a (fixed) offset from vSync (off?) already exists as a property in the old core (YStart, #31)

**Comment by DirtyHairy** [comment] 2016-12-13 12:55
With "frame start" above I mean the beginning of the visible region, not the TV frame (vsync + vblank + kernel + overscan) --- this is currently determined from vblank off. This is one of the places where 6502.ts differs considerably from Stelle, hence the difference. I am totally open to changing this bit though :smirk: 

I'll investigate ditching the current vblank logic completely in favor of alwas using ystart.

**Comment by DirtyHairy** [comment] 2016-12-13 23:51
As of `5.0.0-pre2`, FrameManager contains additional logic that improves vblank / ystart autodetection to the point where it works for Robin Hood and Yatzeeh. I have eliminated the unnecessary logic for missing vsync (as @thrust26 points out, this cannot happen, I am not quite sure why it put it there in the first place).

However, this version still doesn't honor mode, height or ystart as configured in the game preferences; this needs to be reimplemented (#31, but the changes to FrameManger should facilitate this more easily). As I do not know under which circumstances ystart is configured, I will refrain from doing so for now. Also, we might want to look over the game preferences and check where we can trade the preconfigured ystart for autodetection.

**Comment by sa666666** [comment] 2016-12-14 01:58
TBH, ystart is simply a hint to the TIA emulation to start at a specific line.  It defaults to 34, but I don't really know the origin of this (probably found during experimentation).  I think the FrameManager code you've added basically obsoletes this, except for in one specific case.

Sometimes, a ROM starts rendering above the visible window, and part of the image is thus cut off at the top of the screen.  It's mostly these cases where ystart is increased from 34 to a larger value, indicating that the image should move downward, so it's full contents can be seen.

This needs to be reworked.  I suggest the default ystart be changed to 0, in which case it results in the default behaviour that we're seeing now.  It should then only be increased for ROMs that need it.  In fact, it we want to be clever, we can automatically detect the first scanline being drawn, and set ystart internally so the full image is always shown.  That was what I was attempting to do with the 'myStartScanline' variable being detected during VBLANK; get rid of the manual tweaking, and have the core detect it itself.

**Comment by DirtyHairy** [comment] 2016-12-14 08:54
That's what the FrameManager is doing: it tries to detect the first visibile scanline and sets the visible window accordingly. This failed for ROMs that do not have stable VBLANK timings like Yahtzee: the FrameManager would always start the frame at the first visible line, but the actual contents jumped.

The changes I have made try to identify several stable (as in constant first scanline index) frames in a row and then lock the FrameManager to this start line (which corresponds to the yindex, if I am not mistaken). If several deviations from this start line are observed in a row, the FrameManager leaves locked mode and again starts to identify stable frames. I have configured both limits to one stable frame (meaning two frames with identical line index in a row) and two deviations, and with these parameters, all cases I have checked work. Robin Hood and Yahtzee show brief jumping while the code locks onto the frame parameters, but work stable after that.

I agree with you, @sa666666 : I think we should default ystart to zero in ignore it in this mode (letting the autodetect do it's thing) and add an additional "fixed ystart" mode to the FrameManager for games that really need it.

**Comment by thrust26** [comment] 2016-12-14 09:59
I think we need a clear definition of the first visible scanline. E.g. if VBlank is disabled but nothing is displayed, this IMO isn't the first visible scanline. 

My definition would be:
- on a black background, the first line where anything which is not black is displayed
- on a colored background the same but at least one line earlier, else e.g. a black score on top of the screen would clash with the black border.
- black would be $00 for NTSC and $00, $10, $e0, $f0 for PAL) 
- I would also keep YStart (or so) as an option in case auto detection fails

**Comment by sa666666** [comment] 2017-01-12 21:09
One of the more recent tweaks to the display format autodetection is now causing quite a few PAL ROMs to mis-identify as NTSC.  There are many I can mention, but off the top of my head: Mission Survive, CompuMate, Gopher, etc.  Also many of the homebrew ROMs from Pouet are failing.  I can provide ROMs if necessary, but the above should be enough to see the effect.

All these ROMs were properly detected as PAL before the more recent commits.

**Comment by DirtyHairy** [comment] 2017-01-12 23:02
Hi Steve!

Yeah, I noticed the same today when I played around a bit during lunch break :smirk: I also agree with your suspicion about aba48e8 being the issue. I'll take a closer look --- let's hold off with next release until I've identified and fixed the issue.

**Comment by DirtyHairy** [comment] 2017-01-13 08:47
Fixed in 0a8b1de . What happened was that aba48e8 introduces a limit on the amount of lines the algorithm will spend waiting for the vsync on/off cycle to complete. However, this limit (30 lines) is about the same size as the separation between PAL and NTSC (in terms of scanlines) and can cause the TV mode autodetection to get stuck in NTSC.

0a8b1de increases the limit to 100 lines while autodetection is in progress. While this is sufficient to fix the issue, I also changed autodetection to wait for an initial amount of "garbage frames" and then do a statistic of PAL and NTSC frames; the winner is selected. The old algorithm would stick with whatever was selected after 60 frames, and this might lead to issues if the game is not generating a valid signal around frame 60.

@sa666666 , could you recheck any regressions you found? It should be fine now.

**Comment by sa666666** [comment] 2017-01-13 18:13
Confirmed that PAL autodetection is working fine again.  I think we can close this one now.

**Comment by DirtyHairy** [comment] 2017-01-14 13:24
The first issue is adressed in b0b8074 --- this was a bug. I have an idea what is going on with Mariana and similar ROMs, but I'll have to find some more time this weekend to check it. Let's hold off with releasing until then :smirk:

As for the nondeterminism: this is due to the first vsync happening at different cycles. I checked with valgrind, and it doesn't detect any uninitialized variables. However, disabling the randomization of the timer turns the behavior deterministic, so it seems that this affects ROMs that depend on the initial values of the timer (as a crosscheck, my simple test ROMs for which I wrote the code myself act always deterministic). Afaik, it was/is common practice to get entropy for random number from INTIM, so this might be the explanation.

**Comment by sa666666** [comment] 2017-01-14 15:24
Hmm, this FrameManager stuff is getting really complicated isn't it?  Almost moreso than the TIA stuff :smirk:

**Comment by thrust26** [comment] 2017-01-14 22:40
Unrelated: For some hours now I am getting old release notifications, currently its version 3.7.4 and decreasing. Am I alone with that?

3.7.2 now

**Comment by sa666666** [comment] 2017-01-14 22:53
I am going through the old releases (in reverse order) and adding changelog and binaries.  So it will look like a new release is being done.  You can simply ignore these messages.

**Comment by DirtyHairy** [comment] 2017-01-15 00:45
@sa666666 :smirk: you're right. I think it is the combination of detecting ystart AND TV mode that renders this problem tricky. Also, this state machine start exhibiting real complex behavior in edge cases.

However, I think that have finally fixed the remaining issues for good in 3303f05 . The problem was that I was calling `finalizeFrame` once the state machine exits `frame` mode and starts waiting for VSYNC. Among other things, `finalizeFrame` is the piece of code where the total scanline count / frame is evaluated and where TV mode detection happens, based on this value. By definition, "frame size" is the number of scanlines between two vsync cycles and, if the algorithm has locked onto the signal, this should be independent of the point where it is measured, as long as there is always a full period in between. However, if TV is unfixed, this is not guaranteed. For Marinara, the result was the the scanline count of three frames was unevenly distributed over three frames, causing the TV mode to become unstable and switch between PAL an NTSC periodically.

3303f05 ameliorates this by finalizing and starting frames always after vsync goes off. This point is stable and independent the internal state of the detection algorithm. From my tests, this seems to fully stabilize the algorithm. Can you confirm that?

**Comment by sa666666** [comment] 2017-01-15 02:14
Confirmed that this fixes all the issues I saw.  I think we can close this bug, and that we're also ready for another test release.  Feel free to tag a release at your convenience.

**Comment by DirtyHairy** [comment] 2017-01-15 12:41
@sa666666 Done :beers: I have filled the changelogs with the item from my side.

@thrust26 Regarding your suggestions for the definitions of the first line above: I agree with these. However, while relying on VBLANK does not require any crosstalk between frame logic and screen rendering, implementing those would require to prerender every line and decide based upon is structure. As this does not fit well with the way the code is set up and would break the current separation of concerns, I would like to revisit this at a later point. I'd also like to carefully measure the performance penalty incurred by this approach (currently, the core gains speed by skipping several things if nothing is visible on screen).

**Closed by DirtyHairy** 2017-01-15 12:41 UTC
Labels: missing feature
