### ISSUE TITLE
Feature request: new analog paddle options from stella2014-libretro

### ISSUE THREAD

**Issue by Cibomatto2002** [stella-emu/stella#774] opened 2021-03-02 13:41 UTC
I see on stella2014-libretro that they have added more analog paddle options will that be something we will see on stella ?

    Paddle Sensitivity (Analog): Specifies paddle speed. Allowed values are 10%-150%
    Paddle Response (Analog): Determines how the speed of the paddle varies when tilting the RetroPad analog stick.
        Linear: Speed is directly proportional to analog stick displacement.
        Quadratic: Speed increases quadratically with analog stick displacement; this allows for greater precision when making small movements without sacrificing maximum speed at full analog range.
    Paddle Deadzone (Analog): Used to eliminate drift/unwanted input (e.g. X360 controllers typically need this set to 15% when using a Linear paddle response)

https://github.com/libretro/stella2014-libretro/pull/71

**Comment by thrust26** [comment] 2021-03-02 17:11
Paddle sensitivity is already there.

The other two sound interesting, but we would need some controllers for testing. I hope @sa666666 can help here.

**Comment by alijani1** [comment] 2021-04-17 03:55
Standalone Stella (not libretro) works perfectly with paddles as it allows users to map analog gamepad directions to "Paddle 0 Analog", paddle 1 analog, etc, but Stella-libretro with retroarch does not and it seems retroarch forces mapping of analog directional gamepads to just left,right,up,down joystick directions only :(

Please fix Stella-libretro to allow users to map analog controls to Stella analog 0/1/2/3 as its designed to allow.

Its a real shame that we cant play any paddle games and all the systems that use retroarch which uses lr-stella do not support atari paddle games :(

**Comment by Cibomatto2002** [comment] 2021-04-17 14:20
OK thanks for your time :)

**Comment by thrust26** [comment] 2021-04-17 14:24
I meant my answer for @alijani1, not for your request about additional options in Stella itself.

**Comment by alijani1** [comment] 2021-04-17 15:58
ok thanks. I contacted @jdgleaver on the liberto forum who recently appears to have added mouse support.

**Comment by mediamoshpit** [comment] 2021-04-17 15:59
Functionally, the recent analog solution from stella2014-libretro _feels_ identical to standalone Stella's actual analog in practice. The larger shortcoming would seem to be that it only supports two players. Having granular, four player paddle control (no matter how it's achieved) available on every platform libretro reaches would be a real boon.

**Comment by alijani1** [comment] 2021-04-17 19:54
> Functionally, the recent analog solution from stella2014-libretro _feels_ identical to standalone Stella's actual analog in practice. The larger shortcoming would seem to be that it only supports two players. Having granular, four player paddle control (no matter how it's achieved) available on every platform libretro reaches would be a real boon.

I tried the recent Stella2014 version with analog support but I am not able to get it to work identical to standalone analog.  I could not get it to do absolute positioning with mouse or analog game  controllers.   when i move left or right, it moves but it does not stop at the relevant position. it keeps going all the way.  @mediamoshpit,  can you tell me steps on how you got this to work?

**Comment by mediamoshpit** [comment] 2021-04-17 20:35
I may be wrong, but I believe the relevant positioning you're referring to was a feature yet to be added in the snapshot that was chosen for Stella 2014. I noticed it a bit myself, but I've used Stella for so many years now that it just feels like what I was used to for so long. If this is indeed the issue, porting this feature to the modern stella-libretro would potentially work itself out.

**Comment by alijani1** [comment] 2021-08-03 01:36
This now works perfectly in libretro stella2014 and code was fixed under this issue:
https://github.com/libretro/stella2014-libretro/pull/78

They added support for absolute positioning which is perfect for paddle devices.

how can we get this merged into the standard libretro stella builds instead of stella2014 which is not installed on many systems?

**Comment by alijani1** [comment] 2021-09-05 23:22
@thrust26, if you could get this in to the standard libretto Stella core, me and the Atari community would be grateful. I will be happy to test it as I did on the stella2014 fix that rolled out.  If you are interested check out this video that shows [The fix in lr-Stella2014](https://www.youtube.com/watch?v=BYivtbp9cHs)

**Comment by thrust26** [comment] 2021-09-06 05:35
@alijani1 I only want to add this to Stella itself. No clue if this will add it to Libretro too, you have to ask its team.

**Comment by alijani1** [comment] 2021-09-06 14:00
> @alijani1 I only want to add this to Stella itself. No clue if this will add it to Libretro too, you have to ask its team.

@thrust26, but libretro team points me back here that this portion is maintained here as part of this project. see [https://github.com/stella-emu/stella/tree/master/src/libretro](https://github.com/stella-emu/stella/tree/master/src/libretro).

Perhaps someone like @sa666666  can help?  who would you suggest I seek to possibly assist?

**Comment by thrust26** [comment] 2021-09-06 14:04
So if we add it to the desktop version of Stella it will also end in the Libretro version? Then you only have to wait until we find the time for this. 😈

**Comment by alijani1** [comment] 2021-09-06 14:15
There is no issue with desktop version of Stella as paddles work great with absolute positioning. Dead zone also works fine with paddles.  The problem is only with [libretro ](https://github.com/stella-emu/stella/tree/master/src/libretro) because it only sees paddle movements as left and right commands.  [Here is a video showing the problem](https://www.youtube.com/watch?v=H_90k_SJizg&t=64s). This was fixed y adding absolute positioning to lr-stella2014 so it now correctly maps to Paddles settings in desktop Stella under fix: [issue 78]c(libretro/stella2014-libretro#78).

**Comment by thrust26** [comment] 2021-09-06 15:02
Sorry, now I am confused. Are there multiple Libretro versions? And one is implementing stuff on its own and the other one requires our input?

**Comment by alijani1** [comment] 2021-09-06 15:14
yes. there are 2 Stella Libretro versions that are widely adopted.

1. [lr-stella](https://github.com/stella-emu/stella/tree/master/src/libretro)
2. [lr-stella2014](https://github.com/libretro/stella2014-libretro)

While the first one is most common, its got many issues that have been going on for long time and we cannot find anyone to fix.  Th second one (lr-stella2014) core version has many fixes and improvements but its adoption is more limited. Large systems like Retropie and Retroarch standalone installed support it but you cannot get them for Emuelec or Batocera.

This is why I am searching to see whom can get the fix that was done in the lr-stella2014 into the lr-stella repository.

**Comment by thrust26** [comment] 2021-09-06 15:21
So the lr-stella is build on current Stella? And the issues in there are not Stella specific? But they would be solved if we add extra functionality to Stella? Sounds odd.

Sorry for asking that many questions, but I never got interested into Libretro.

**Comment by thrust26** [comment] 2021-09-06 15:26
Anyway, I think we can add something Stelladaptor or USB Controllers. Though I would make the paddle response configurable between a power of 1 (linear) and 2 (quad) (or even more).

**Comment by sa666666** [comment] 2021-09-06 15:58
There shouldn't be any further development on stella-2014.  If someone is adding code to that repo, the should rebase it on the current Stella (ie, the main branch).  That way, it will be released each time we do a new release.  The problem is that nobody is really maintaining Stella for libretro.  Patches are being created and applied to an old version.  If those people would instead develop against the main branch and submit a PR to us, then we could get it added.

**Comment by alijani1** [comment] 2021-09-06 16:18
@sa666666,  thanks and alright. I will contact the developer who fixed it in stella2014 and let them know.

Will you be able to look at this issue of no proper support for paddles and see if we can fix it here?

As I mentioned, the problem is the current version only sees paddle movements as left and right commands. [Here is a video showing the problem. ](https://www.youtube.com/watch?v=H_90k_SJizg)

We need to add absolute positioning mapping support so stella desktop paddle values get translated correctly to libretro instead of just left and right.   [It should function more like this](https://www.youtube.com/watch?v=BYivtbp9cHs)

**Comment by sa666666** [comment] 2021-09-06 16:26
Yes, I understand the issue.  My point is if someone has already done a fix for 2014, it makes more sense for them to look at the newer branch and see if it can be integrated there.  Maybe it's just a little fixup to get it working against the latest branch.  It doesn't make much sense for me to come up with a completely new solution/code when it's already been (mostly) done by someone else.

Overall, we need to mark the 2014 branch as discontinued, and not do any further work on it.

**Comment by thrust26** [comment] 2021-09-06 16:40
Why does the branch exist anyway?

**Comment by sa666666** [comment] 2021-09-06 16:47
Historical reasons, I guess.  Retroarch Stella support was done outside main Stella development for years.  It's based on Stella 3.9.x, which is what all the 'outside' systems seem to be using.  R77 had similar issues.  I guess it was because Stella 4.0 went to hardware acceleration and SDL2, and the others never made the jump.  But now the libretro is supported in mainline Stella, all development should move here.

**Comment by alijani1** [comment] 2021-09-06 17:04
> Yes, I understand the issue. My point is if someone has already done a fix for 2014, it makes more sense for them to look at the newer branch and see if it can be integrated there. Maybe it's just a little fixup to get it working against the latest branch. It doesn't make much sense for me to come up with a completely new solution/code when it's already been (mostly) done by someone else.
> 

Thanks. I contacted the developer ( @jdgleaver )  who fixed it to see if he can do a PR and assist.

**Comment by thrust26** [comment] 2021-09-06 17:06
Since Stella needs an UI anyway, I think I should do the changes myself. I looked into the existing Libretro code and it looks easy enough to replicate/integrate into Stella. Unfortunately this will have to wait a week, because I currently have not controller for testing with me.

**Comment by sa666666** [comment] 2021-09-06 17:20
The UI code and related stuff from mainline Stella is not compiled into libretro Stella at all.  The UI it has in those videos seems to come from Retroarch itself.  So that's the way we have to proceed, I think.

**Comment by thrust26** [comment] 2021-09-06 17:21
IMO mainline Stella will benefit form both changes too. That's why we should fully integrate them.

**Comment by sa666666** [comment] 2021-09-06 17:35
Sure, the functionality can be integrated.  But the configuration from the UI will be different.  We use our own UI code with SDL2 as the backend.  And Retroarch uses its own separate UI for configuration.

**Comment by thrust26** [comment] 2021-09-06 20:37
I got some basic code working already (testing with my mouse only). ACCEL is between 1 and 2, MOUSE_SENSITIVITY is adjusted automatically too.
Note: The `abs(diff)` are only there because C++ has (for whatever reason) no sign method.

```
  int diff = newAxis - lastAxis;
  double factor = diff ? pow(abs(diff), ACCEL) / abs(diff) : 0;

  newAxis = lastAxis - diff * factor * pow(MOUSE_SENSITIVITY, 1.f/ACCEL);
```

**Comment by twinaphex** [comment] 2021-09-06 22:13
We're fine with contributing to the mainline Stella core and we are all happy we have upstream support, however, I do feel that you need to understand why we cannot just abandon an old 2014 version of Stella, and it's for a very simple reason, and it's the same reason why older MAME cores exist -

current mainline MAME (and Stella) are just too slow on many older platforms and targets that we personally care about. We would not be creating additional maintenance burdens for ourselves by having these separate forks if this were not the case. I honestly feel in light of that and given the freedoms and permissions that the GPL license affords everyone, this really should not be an issue, and developers should understand where we are coming from.

In any other event, if the hardware is capable enough, yes, they should probably choose Stella mainline. But there's absolutely no harm in letting people have access to an older version that is more performant on older hardware. That has been our stance with MAME as well, and while we respect core authors and definitely want to work with them and we always try to do so, I feel to deny us outright any work on a fork that is clearly meant for underpowered hardware is a bridge too far since this is not covered by any open source license in any way or shape. As soon as there is no conceivable difference in performance beween Stella mainline and Stella 2014 and if it doesn't require some cutting edge version of C++ to compile (that might not even be available on random old hardware platform that we're targeting), then we could get rid of it. At no point sooner can this be done unfortunately. There are literally thousands of other forks of Stella that exist and none of them are brought to discussion either.

@alijani1 I really feel in this case you did more harm than good by going into these developer conversations and creating potential issues between developers that (if we were to calmly explain the situation) could likely be resolved in a mature and nuanced fashion vs. it leading to an escalation of grievances. We have seen this happen a bunch of times and we are not a fan of it. If you want something implemented, here's an idea - maybe contribute a PR yourself instead of requesting developers to do it? We could use all the help in terms of lightening our workload, and it's not fair to start requesting random contributors/volunteers of our project to start doing certain things immediately that you want them to do either.

But let it be said, we are perfectly willing to contribute to the upstream repo, and not only do I think we have shown in the past we have sent submissions, we also let the developers immediately know when a build is broken. We just respectfully disagree when it comes to being ordered to no longer submit a small patch to a 2014 fork of a repo that is clearly there for systems that don't have the hardware grunt to run mainline Stella. This should not be an issue and we do not believe this should be escalated into an argument either.

**Comment by sa666666** [comment] 2021-09-06 22:40
There was no offense on our end, I think.  I'm just stating that if someone has already written code that is working in the old version, it makes sense to port it to the latest Stella too.  If you want to maintain two branches (2014 and current), that is fine too.  But I think it makes sense to target mainline as well as 2014 if you add new features.

I guess the real issue is that nobody is really maintaining the Stella port for libretro.  I do make sure there are no breakages when we make large changes to the codebase, but I don't really do anything else with the libretro port otherwise.  It would be great to have someone that can coordinate that.

**Comment by twinaphex** [comment] 2021-09-06 22:41
If there are patches we can submit to mainline, I'll definitely try to make sure we aim at getting these things pushed upstream as soon as possible.

**Comment by thrust26** [comment] 2021-09-07 06:20
Sorry if I came over negative. That was not my intention. I was just trying to understand a bit more of the Libretro situation, which I am pretty unaware of. And absolutely don't mind asking for features here, as long as they are valid for the Stella mainline too. Which is the case. 

And so this feature will get integrated for mainline Stella too. I hope this will be useful for Libretro too.

**Comment by thrust26** [comment] 2021-09-15 20:03
Done with 4d78865

**Closed by thrust26** 2021-09-15 20:03 UTC
Labels: enhancement, Libretro, target 6.6

**Comment by sa666666** [comment] 2021-09-15 20:18
I guess now the libretro people can hook into this new functionality?

**Comment by thrust26** [comment] 2021-09-15 20:22
Yup.
