### ISSUE TITLE
request: appveyor build script

### ISSUE THREAD

**Issue by ghost** [stella-emu/stella#350] opened 2018-08-14 18:39 UTC
Hello, is it possible to make an appveyor script that can auto-generate (msvc2017) binaries? Thank you

**Comment by DirtyHairy** [comment] 2018-08-14 18:44
Already on my desk... 😉

**Comment by retrotalker** [comment] 2018-08-27 03:53
@DirtyHairy 
I've modified an snes9x appveyor script to generate windows apps (x86, x64) for Stella
https://github.com/retrotalker/stella/blob/appveyor/appveyor.yml

You can see results here of auto-building
https://ci.appveyor.com/project/retrotalker/stella/build/5.1-1

Feel free to tweak or correct this script further for Stella's aims. For those who have trouble compiling, this is a great help.

**Comment by DirtyHairy** [comment] 2018-08-27 08:12
He, awesome 😀 I'll check it out later this week.

**Comment by sa666666** [comment] 2019-06-01 00:47
I guess now that libretro has build scripts for many systems for Stella, we can close this??

**Comment by sa666666** [comment] 2019-06-02 20:14
@DirtyHairy, is this very difficult to add, or should we just close this one?  Libretro has these types of scripts, so it should be easy enough to adapt one??

**Comment by sa666666** [comment] 2019-08-15 00:11
@DirtyHairy, is it worth it to do this, or can we just rely on the libretro infrastructure to do it?  If the latter, we can close this one.

**Comment by snes2600** [comment] 2019-08-15 02:16
appveyor is useful for maybe:
- building standalone windows
- building standalone linux (?)
- libretro = who cares, buildbot is very active

**Comment by sa666666** [comment] 2019-08-15 10:13
I'd appreciate any help that you can provide.

**Comment by DirtyHairy** [comment] 2019-08-15 11:56
I think this would be useful. I have been eyeing Appveyor for windows builds, and Travis for Linux + MacOS, but I haven't gotten around to actually doing it. From my experience, settings this up may take some time due to the slow feedback cycle when you do changes, but once you've got it working, it is incredible useful.

**Comment by snes2600** [comment] 2019-08-15 22:01
Basic Appveyor one is done for Windows.
https://github.com/snes2600/stella/commit/040544dc83b908f5a789326c4319c5913bf19a8f

Which punches out this.
https://ci.appveyor.com/project/snes2600/stella/builds/26733254


I chose VM 2017 because VM 2019 takes forever to get started. 2017 usually enters the build queue quickly.

**Comment by snes2600** [comment] 2019-08-17 03:57
Scripts are ready. Logs pass.
https://github.com/snes2600/stella/commit/88d3149ac1057b7916a52e56b7a1bc4f047dbf8c


Windows: Visual Studio 2019
https://ci.appveyor.com/project/snes2600/stella/builds/26761799

Xenial: gcc 9
XCode 11: clang 11.0
https://travis-ci.com/snes2600/stella/builds/123582596

**Comment by sa666666** [comment] 2019-08-17 15:25
Anything to do I need to do on my end to activate this?

**Comment by snes2600** [comment] 2019-08-17 16:07
I've sent a PR now. Once the scripts are in stella-emu github, you'll need to login to that account. Go to the two websites mentioned and "sign up with github". It takes a few steps after that to get the CI bots active and auto-triggering.

**Comment by sa666666** [comment] 2019-08-18 00:05
Not sure what to do next.  @DirtyHairy, have you done this before??

**Comment by snes2600** [comment] 2019-08-18 01:27
Tested from scratch. Here's what I did:

1a. Log into https://github.com
- For development tests, you can use your own github account. Ex. I logged in using snes2600
- For project tests, you'll have to login with stella-emu account.

2a. Go to https://ci.appveyor.com
2b. Press GitHub
2c. Authorize appveyor
2d. New Project
2e. Authorize GitHub
2f. Authorize appveyor
2g. Select stella -- '+ Add' button
2h. Press 'New Build' to create initial test

3a. Go to https://travis-ci.com/
3b. Press 'Sign up with GitHub'
3c. Authorize travis-pro
3d. Go to https://travis-ci.com/account/repositories
3e. Press 'Activate'
3f. Only select repositories
3g. Select 'stella'
3h. Approve & Install
3i. Select 'stella'
3j. More options -- Trigger build -- Trigger custom build to create initial test

**Comment by sa666666** [comment] 2019-08-18 01:29
OK, I will look into this tomorrow.

**Comment by snes2600** [comment] 2019-08-18 23:27
I see green checkmarks showing in the list of master commits
https://github.com/stella-emu/stella/commits/master

Clicking that says "Travis CI - passed". So that's Linux and Mac taken care. Just Appveyor to go.

**Comment by DirtyHairy** [comment] 2019-08-19 08:18
But checking whether the source builds is only half of the deal 😏  IMO, the real treat is having builds generated and uploaded automatically for each tag or maybe even each commit. That makes generating reproducible release builds *much* easier.

With 6502.ts for example, I generate Stellerator builds on each tag and upload them automatically to the corresponding release on github. With Stella, we'd have do devise a policy like that --- then Travis and Appveyor can automatically generate and upload builds.

**Comment by snes2600** [comment] 2019-08-19 12:44
https://github.com/stella-emu/stella/commit/457bb086c4aa495836138b5904b8620e7a667f13

This Appveyor script will upload 32-bit and 64-bit Windows Stella.exe binaries, on every commit automatically. But it will first have to be activated using steps 2a-2h above. It's very nice when working. I tested the CI commit earlier and got this.

https://ci.appveyor.com/project/snes2600/stella/builds/26773565

https://ci.appveyor.com/project/snes2600/stella/builds/26773565/job/rbuli2uiotobvwqn
https://ci.appveyor.com/project/snes2600/stella/builds/26773565/job/rbuli2uiotobvwqn/artifacts
https://ci.appveyor.com/api/buildjobs/rbuli2uiotobvwqn/artifacts/src%2Fwindows%2Fx64%2FRelease%2FStella.exe

https://ci.appveyor.com/project/snes2600/stella/builds/26773565/job/q24m21x3mu13qm6k
https://ci.appveyor.com/project/snes2600/stella/builds/26773565/job/q24m21x3mu13qm6k/artifacts
https://ci.appveyor.com/api/buildjobs/q24m21x3mu13qm6k/artifacts/src%2Fwindows%2FRelease%2FStella.exe

Note that my history is somewhat empty since I like to delete builds too.

Appveyor has its own storage servers. Travis I think does not have any - you'd have to use Amazon AWS or some other upload hosting service. This part I couldn't figure out.

**Comment by sa666666** [comment] 2019-08-19 13:07
I think I have this all done.  Thanks for the detailed instructions; hopefully all works fine now.

**Comment by sa666666** [comment] 2019-08-19 17:43
I await feedback on whether it's working in all cases.  Then we can close this one.

**Comment by snes2600** [comment] 2019-08-19 21:45
Last 2 commits have Appveyor artifacts uploading. Travis reports no failures. At a basic level, all is working.

If @DirtyHairy wants Travis + Github integration, this will need to be done. Which would be more for tagged releases and not per-commit.
https://stackoverflow.com/questions/12343452/how-to-publish-artifacts-in-travis-ci

**Comment by sa666666** [comment] 2019-08-19 23:09
OK, I'll leave this open until either @DirtyHairy has time to work on it, or we decide we don't want to go any further.

**Comment by sa666666** [comment] 2019-08-31 02:20
We've decided to just use the auto-builds for commits, and create final releases on our own.  So this is now done.

**Closed by sa666666** 2019-08-31 02:20 UTC
Labels: enhancement
