### ISSUE TITLE
Libretro - iOS/Android build failure

### ISSUE THREAD

**Issue by twinaphex** [stella-emu/stella#546] opened 2019-11-10 19:19 UTC
Hi there,

the current build failure occurs when compiling the Stella libretro core for iOS -
 
http://paste.libretro.com/170312

Unrelated but slightly related - Would it be possible to add libretro Travis checks for each commit? Some of the errors that might occur during commits might be picked up on that way.

**Comment by DirtyHairy** [comment] 2019-11-10 21:28
That's weird. Can you narrow that down to a specific commit? Did you recently switch toolchains?

**Comment by twinaphex** [comment] 2019-11-24 08:33
No changes have been made to our buildbot. Toolchains should be the same.

Here's another error, now concerning the Android version -

http://paste.libretro.com/173593

**Comment by twinaphex** [comment] 2019-11-24 08:34
I also reiterate that Travis build rules for the libretro cores could go a long way towards being able to identify breakages in libretro cores earlier. Not sure if you need any help with that but we'd be able to help out maybe getting that setup in case it's necessary.

**Comment by thrust26** [comment] 2019-11-24 08:47
> Here's another error, now concerning the Android version -

Isn't that the same as mentioned above? For whatever reason `MT24LC256::INIT_VALUE` which is defined in `MT24LC256.hxx` cannot be resolved?

**Comment by tryal-star** [comment] 2019-11-29 02:55
Tried it with clang 9.0.0 and all Android will build. Weirdly only 32-bit Android are failing with libretro toolchain.

Maybe you could try this
https://github.com/stella-emu/stella/blob/master/src/common/bspf.hxx#L96
```#undef INIT_VALUE```

Or lto compiler bug with older libretro clang??

**Comment by sa666666** [comment] 2019-12-10 01:14
Please try the latest code; I think @DirtyHairy has found a fix for this.

**Comment by sa666666** [comment] 2019-12-18 14:42
Closing since there is no further feedback, and I think think the problem is solved.

**Closed by sa666666** 2019-12-18 14:42 UTC
