### ISSUE TITLE
Massive Stella slowdown caused by Ubuntu version

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#923] opened 2022-08-24 17:04 UTC
Here is what @Augusto7743 wrote in #916:

Stella 6.7 Linux Ubuntu 20.04 run much slow (game launcher playlist browse and gameplay speed).
Stella 6.7 Linux Ubuntu 18.04 run without problems.

Stella using default settings and enabled opengl and multithread in Ubuntu 20.04 FX-6300 GF GT640.

Stella 6.7 Linux Ubuntu 18.04.
cpu power profile power save
cpu percentage usage in single core

Enduro
8-25 %

Galagon
26-41 %

Mappy
15-40 %

Robotwar-2684
29-47 %

If using cpu power profile high performance the percentage is much low being less of 20 %.

Stella 6.7 Linux Ubuntu 20.04.
cpu power profile power save
cpu percentage usage in single core

Enduro
80-92 %

Mappy (and others Champ games)
100 % ... extremely slow ... need use cpu power profile high performance ... I not see command to enable FPS view in Stella. perhaps running at half speed 30 FPS.

cpu power profile using high performance
cpu percentage usage in single core

Galagon
50-62 %

Mappy
54-62 %

Robotwar-2684
40-60 %

Stella 6.7 Linux Ubuntu 20.04 cpu requirement is more of 3 times comparing with Ubuntu 18.04 version.

**Comment by sa666666** [comment] 2022-08-24 17:09
Does the 18.04 build run slowly in Ubuntu 20.04?  Basically trying to determine if it's a difference in how the binary was compiled (ie, compiler version, flags, etc), or a difference in the distro itself (kernel, power governor, etc).

**Comment by sa666666** [comment] 2022-08-24 20:03
To reiterate my last point.

- There are two builds; one for 18.04 and another for 20.04.
- For Ubuntu 20.04, you can install either the 18.04 build or the 20.04 build.

If you haven't already, please try installing the 18.04 build on Ubuntu 20.04.  That way, we are comparing the same binary one two different Ubuntu versions.  If there's no difference (ie, both are fast), then something changed in the Ubuntu 20.04 build.  Otherwise, something changed in the OS itself from 18.04 to 20.04.

**Comment by Augusto7743** [comment] 2022-08-25 04:36
@thrust26
Thanks.

Both Stella Ubuntu 18.04 and 20.04 tested on Ubuntu 20.04.4.
build 18.04 run correctly.
the problem is the build 20.04.
Possibly is anything related when compiling.

**Comment by sa666666** [comment] 2022-08-25 14:23
OK, I will contact the maintainer that creates the 18.04 builds, and get the compiler/flags used and compare to the 20.04 build.

For now, I can do another 20.04 build, making absolutely sure that the flags are correct.  I will do it and post a build in a moment.

**Comment by sa666666** [comment] 2022-08-25 14:39
Here are some test builds; both were built on 20.04.4.  The first is what we'd normally release, with gcc-9.4.0, O2 optimization and  link-time optimizations.  The second is almost exactly the same, except LTO is removed.

[stella_6.7_amd64-LTO-O2.deb.zip](https://github.com/stella-emu/stella/files/9425654/stella_6.7_amd64-LTO-O2.deb.zip)
[stella_6.7_amd64-O2.deb.zip](https://github.com/stella-emu/stella/files/9425655/stella_6.7_amd64-O2.deb.zip)

If either of these fix the issue, then we have a hint as to what direction to follow.  Otherwise, I will need to look at the 18.04 build, which uses gcc-7.5.0.

**Comment by Augusto7743** [comment] 2022-08-25 15:09
tested in Ubuntu 20.04.4.
problem was fixed with both builds

cpu percentage usage in single core

LTO build

Enduro
4-27 %

Galagon
14-40 %

Mappy
20-38 %

Robotwar-2684
20-42 %

O2 build

Enduro
6-33 %

Galagon
24-42 %

Mappy
20-46 %

Robotwar-2684
26-47 %

When running the O2 build cpu cores are more used happening more multithreading. Few times having 2 cores not being used.
LTO has less multithreading usage at point having 2 or 3 cores not being used almost all time.

Thanks very much.
Have an nice day =)

**Comment by sa666666** [comment] 2022-08-25 15:12
OK, it seems there was a problem with the build process for the 6.7 release.  I will update the download links accordingly.

**Closed by sa666666** 2022-08-25 15:12 UTC
Labels: build bug
