### ISSUE TITLE
Trackball asymmetrical

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#180] opened 2017-07-25 21:05 UTC
The Atari Trackball (formerly CX-22) is moving at different speeds. Reactions to right and down are (about) 50% slower than left and up. Atari and Amiga Mouse are fine.

[Missile Command (CX-22).zip](https://github.com/stella-emu/stella/files/1174762/Missile.Command.CX-22.zip)

**Comment by sa666666** [comment] 2017-07-29 15:53
This is systemic of a larger problem.  I see that in the other schemes too, there is slowdown in the same directions.  It's just not as pronounced as with the Trakball.

The code originally came from z26, and I don't really understand how it works.  But there are two values that are divided by 2 (shifted right by one).  This happens for AmigaMouse and AtariMouse.  So I figured that to reduce the resolution of Trakball, I would shift right again (to divide by 2 again).

Obviously that approach doesn't work.  But the original shifting doesn't really work either.  So in effect all 3 controller inputs are broken; it's just more noticeable with the trakball.  I will need to experiment to figure out how the current code works.

**Comment by sa666666** [comment] 2017-07-29 15:55
I should add that not having either a trakball to test with is making things much more difficult.  I do have a mouse on my Amiga that has a toggle switch to switch to Atari mode; maybe I should try this on my light-sixer??

**Comment by thrust26** [comment] 2017-07-29 16:00
For me Atari and Amiga mouse work pretty well with Stella. Just the Atari Trak-Ball doesn't.

I'll look into the code and try to understand it.

**Comment by sa666666** [comment] 2017-07-29 16:36
Try moving the cursor in Missile Command completely to the left of the window.  Then move your mouse completely to the left and against some obstacle (the side of your keyboard, etc).  Now move the mouse right until the cursor reaches the right side of the window.  Finally, move the mouse back again until the cursor reaches the left side of the window again.

I'm willing to bet that your hand/the mouse won't be to the complete left.  That is, moving left to right takes, say 10 cm, but moving right to left takes 8 cm.  So it's moving faster/further in one direction than the other.

This is happening for all 3 controllers; it's just more noticeable for the trakball.

**Comment by thrust26** [comment] 2017-07-29 17:18
I see. Since it is worse with the Trak-Ball, that would imply that the shifting right is causing the problem. 

And we are definitely loosing moved pixel here. And twice as many for the Trak-Ball. But that should happen for positive and negative values and (unless there is something else happening) completely average out. 

For testing, you could create and check versions which shift right by 3 and not at all. If the latter is acting without a bias and the former is even worse than the Trak-Ball, then we at least know the origin.

Then we could save the remainder and add before shifting the next time. Fingers crossed, that cures the problem. E.g. (code only for one axis):
```
myHCounter += myTrakBallHRemainder;
if(myHCounter < 0) myTrakBallDown = 0;
else               myTrakBallDown = 1;
myTrakBallHRemainder = myHCounter & 3; 
myTrakBallCountV = abs(myHCounter >> 2)
```
IMO the remaining trackball code itself can't be the reason, as it seems to act perfectly symmetrical for positive and negative directions.

**Comment by sa666666** [comment] 2017-07-29 23:00
Using 0 for the shift (aka, not shifting at all) works fine, but of course the cursor moves much too fast.  But at least it moves by the correct in each direction.  Setting it to 3 makes the problem even more obvious.  So it is definitely the shifting that's causing the issue.  What I'd like to know is why it's there at all.  Once I test my Amiga/Atari mouse, I may remove the shifting from those controllers altogether.

For now, I will test your code and let you know what happens.

**Comment by sa666666** [comment] 2017-07-29 23:26
Unfortunately, your code seems to make no difference.

**Comment by sa666666** [comment] 2017-07-29 23:59
I just added some debug code that zero's a static counter when pressing the left button, and updates the counter when moving left or right (for now I ignore up/down, as the results are the same).  Sure enough, moving to the extreme left and zeroing the counter, then moving to the right shows the value at ~800, but then moving to the extreme left shows the counter at ~200.  So we're moving 800 counts to the left, and 600 to the right.  This can be duplicated by starting at the right.  Moving to the left (from count 0) sets the counter to ~ -600.

Since this is the output before any processing, it seems that MouseAxisXValue and MouseAxisYValue _aren't_ evenly distributed.  Now I have no idea what is going on, since these values are coming directly from SDL.

**Comment by sa666666** [comment] 2017-07-30 00:07
This is now confirmed at a higher level than Trakball class; it's happening in EventHandler itself, which is receiving data directly from SDL events.  So perhaps yet another bug in SDL.

**Comment by sa666666** [comment] 2017-07-30 00:33
Correction; SDL is correctly reporting the movement.  Ignoring what happens onscreen, moving to the complete right increases to a certain value, then moving back to the left decreases back to 0.  So the data that the trakball class is receiving is correct; it's definitely in the post-processing.

Sorry for the confusion.  @thrust26, you really need to get a devel environment set up to see if you can duplicate what I'm seeing.

**Comment by sa666666** [comment] 2017-07-30 01:19
@thrust26, I'm attaching a Windows build for you to test.  Let me know if it's working better now.
[Stella-5.0.2_pre-windows.zip](https://github.com/stella-emu/stella/files/1185397/Stella-5.0.2_pre-windows.zip)

**Comment by thrust26** [comment] 2017-07-30 06:31
Thanks for your tests. I think we are very close to finding the root cause of the problem. And the new build seems to work better. It still seems to have a slight bias, but **much** lower. What did you change?

This morning (in bed :smile:), I had another idea. Is shifting working the same as dividing for negative values. E.g. (1 >> 1) = 0, but is (-1 >> 1) = 0 too? Or is that still -1?

I would suggest to change _abs(myVCounter >> 2)_ into _abs(myVCounter) >> 2_. That, or dividing by 4 instead of shifting.

As for setting up a development environment, I would first need to understand GitHub. :smile: From following the discussions here and in the AA forum, it seems to work quite differently than SVN. Also, I have set up **LOTS** of development environments in the past, which all stopped working after I didn't use them for some time. It seems they are all tailored for constants use and require permanent maintenance. And I am not very firm (or interested?) in such things. So that combined with the GitHub issue, I am quite reluctant now. 

Stupid? Maybe.

**Comment by thrust26** [comment] 2017-07-30 07:32
OK, I started to setup an environment:
- Github required an update, which (of course) required a system reboot :angry:
-  my Visual Studio was from 2013 and refused to continue to work or update, uninstalling seemed to to take ages
- Visual Studio C++ 2017 cost > $200, wasn't there a free solution?

**Comment by thrust26** [comment] 2017-07-30 09:07
Success. I got the problems fixed. Not only is the asymmetry gone now, but also slow movements are working now.

So, how can I commit?

BTW: Why 99% redundant code for the three trackball controllers? I am very tempted to refactor this with my aging C++ knowledge. :smile:

**Comment by thrust26** [comment] 2017-07-30 10:02
Here is the changed code:
 ```
 // Get the current mouse position
  myHCounter = myEvent.get(Event::MouseAxisXValue) + myHCounterRemainder;
  myVCounter = myEvent.get(Event::MouseAxisYValue) + myVCounterRemainder;

  if(myVCounter < 0) myTrakBallLeft = 1;
  else               myTrakBallLeft = 0;
  if(myHCounter < 0) myTrakBallDown = 0;
  else               myTrakBallDown = 1;

  myHCounterRemainder = myHCounter % MOUSE_DIVIDER;
  myVCounterRemainder = myVCounter % MOUSE_DIVIDER;
  myTrakBallCountH = abs(myVCounter / MOUSE_DIVIDER); 
  myTrakBallCountV = abs(myHCounter / MOUSE_DIVIDER); 
```
MOUSE_DIVIDER is 2 for Atari and Amiga mouse, 4 for Trak-Ball. myHCounterRemainder and myVCounterRemainder are initialized with 0.

**Comment by DirtyHairy** [comment] 2017-07-30 10:06
Deleted redundant code is the best kind of code :smirk:

**Comment by thrust26** [comment] 2017-07-30 10:14
100% agreed. But IIRC the refactoring into 3 classes was done lately. Before the we had only one class, with some ugly IFs.  

IMO we need 4 classes, one base TrackBall class and the existing 3 classes derived from that. The derived classes would only define the divider value and IOPortA calculation.

**Comment by DirtyHairy** [comment] 2017-07-30 11:45
I just had a look at those classes, 100% agreed that those should be one class. As they only differ in constants, I think that a template makes even more sense than actual inheritance with virtual methods:

* Introduce a PointingDeviceController as a template class, the template parameter being a helper class that contains the various parameters
* For each of the three controllers (AmigaMouse, AtariMouse, TrakBall), instanciate the template controller with a suitable helper class

This will avoid the dispatch overhead from calling virtuals and might be even more concise. What do you think?

**Comment by thrust26** [comment] 2017-07-30 11:51
To be honest, I haven't coded much for C++ for the last 10, 15 years. So I leave that for the real experts to decide.

How do you plan to handle the differences for IOPortA calculation?

**Comment by DirtyHairy** [comment] 2017-07-30 12:05
> How do you plan to handle the differences for IOPortA calculation?

I'd add a static method to the helper for this, something like

```
static uInt8 ioPortA(uInt32 countH, uInt32 countV, uInt8 down, uInt8 left),  {
  constexpr uInt32 ourTableH[2][2] = {{ 0x40, 0x00 }, { 0xc0, 0x80 }};
  constexpr uInt32 ourTableV[2][2] = {{ 0x00, 0x10 }, { 0x20, 0x30 }};

  return ourTableV[countV  & 0x01][down] |
             ourTableH[countH & 0x01][left];
}
```

The code in the controller class would then be
```
const uInt8 IOPortA = T::ioPortA(myCountH, myCountV, myTrakBallDown, myTrakBallLeft);
```

Writing the template class is simple enough:
```
template<T> class PointingDevice : public controller {
...
}
```

The only catch is that, with templates, all code has to reside in the header. In order to keep the header readable, it is a common pattern to start with the declaration as usual and then add the implementation further down below (i.e. tia/DelayQueueMember.hxx).

The individual controllers can then be replaced with typedefs:

```
typedef PointingDevice<AmigaMouseHelper>  AmigaMouse;
```

**Comment by thrust26** [comment] 2017-07-30 12:11
Go ahead, I am looking forward to your code refactoring. :smile:

**Comment by DirtyHairy** [comment] 2017-07-30 12:14
> So, how should I commit?

Caveat: unfortunately, I can only tell you how to do those things on the CLI, so the best thing I can do is to highlight the names of the corresponding git operations --- they should be in Tortoise somewhere.

Depends :smirk: The first step is to commit your changes locally --- as git is decentral and does not have the concept of a server, your local clone is a full-fledged repository. If @sa666666 gives you commit access to the repo, you can then **push** your changes to the repository. If the repository has moved beyond your local copy, the **push** will fail and you will have to **pull** in the new changes first. When pulling, you should tell Tortoise to **rebase** instead of **merging** (that should be an option when pulling) --- this will replay your commit on top of the new code and avoid creating and pushing a merge commit.

The more common way to contribute on github is to create a fork in the github web interface. A fork is like a branch that is completely under your control. You the clone your branch, do your work there and finally, when you are done, you do a pull request in the web interface. Stephen can then review your work, comment it and, finally, merge. At this point, you have to pull again from the upstream repo to get your code up to date, but one thing at a time :smile:

**Comment by DirtyHairy** [comment] 2017-07-30 12:19
> Go ahead, I am looking forward to your code refactoring. :smile:

Hihi, will do, and you add your changes on top :smirk: Unless you'd like to do it yourself, of course --- I don't want to force my personal coding tastes in. "Normal" inheritance should work fine as well, and the performance hit from the virtual methods is likely to be academic.

**Comment by DirtyHairy** [comment] 2017-07-30 12:21
As a sidenote, @sa666666 , I've never tried it before, but [gitter](https://gitter.im/) is a chat that is connected to github projects and might be more useful than tickets for discussions like this :smirk: I'm tempted to do an experiment and set it up of Stella, if this is OK for you.

**Comment by thrust26** [comment] 2017-07-30 12:25
My own coding preferences would condense the code a lot and I know most people don't like it that anyway. Also, we should keep the coding consistent. So just do all the changes, please.

**Comment by DirtyHairy** [comment] 2017-07-30 12:48
@thrust26 I have compiling code, but I have yet to test it. Can you point me to some testcases that use mouse or trakball?

**Comment by thrust26** [comment] 2017-07-30 12:51
There is a Missile Command hack at the top of this thread. Just move the cursor (slowly and fast) and check if it is responsible and has no bias.

**Comment by DirtyHairy** [comment] 2017-07-30 13:18
I have my refactoring working, including your changes. I'm doing a final build from scratch and commit after that, so you can check for yourself. I cannot feel much difference for the Missile Command hack, but I am sitting in the garden at my laptop and using my trackpad, so that might be the reason :smirk:

**Comment by DirtyHairy** [comment] 2017-07-30 13:20
Pushed, commit is 218da357 .

**Comment by sa666666** [comment] 2017-07-30 13:22
Wow, I just wake up to check the progress of this thread, and find not only are there 18(!) messages waiting to be read, but the time I get to the end of them, the implementation is already done :smiley: 

As for the virtual vs. template, I too would try to avoid inheritance when possible.  But it doesn't matter in this case, since they all inherit from Controller and the read/update methods are virtual anyway.

**Comment by DirtyHairy** [comment] 2017-07-30 13:23
> But it doesn't matter in this case, since they all inherit from Controller and the read/update methods are virtual anyway.

Noticed that, too, after I was halfway done :smile:

**Comment by thrust26** [comment] 2017-07-30 13:23
"Please commit your changes or stash them before you merge."

How can I overwrite my changes?

**Comment by DirtyHairy** [comment] 2017-07-30 13:25
On the CLI you do a "git reset --hard" (providing you have not commited). Google indicates there is a dialog in tortoise for this somewhere.

**Comment by thrust26** [comment] 2017-07-30 13:32
I did a "Stash Save" and then a Pull and now the VS project is broken. Looks like all my settings have been overwritten. How do I do it right?

**Comment by sa666666** [comment] 2017-07-30 13:45
@thrust26, I suggest for now that you leave it alone for an hour or so.  The fact that there are several broken links is normal; @DirtyHairy provided code for Linux, but not for the Windows and OSX builds.  Typically I do a commit after his to fix up these issues, since it's very easy for me (I have all systems here in my computer room/cave :smile: ).

So wait until another hour, and I'll get everything updated.   Then you can work from there, knowing that everything is in a working state.

BTW, I used SVN for years and some Git at work, and I'm still trying to understand some parts of Git.  But the work ends up being rewarded in the end.

**Comment by DirtyHairy** [comment] 2017-07-30 13:45
As far as git is connected you haven't done anything wrong. Stashing is fine, too. It is usually used to stow away your changes and apply them again later, but nothing forces you to do so :smile:

As far as VS is concerned, I am clueless. It could be that your local settings are stored in a file that is alsow checked into git, so stashing will wipe them. You could restore your stash, which will reapply your changes. However, you will get conflicts as I changed the corresponding code. AmigaMouse.cxx, AtariMouse.cxx and TrakBall.cxx are gone for good, so I at least understand why it is complaining.

However, VS should be able to integrate with git, too, maybe this works better. Generally speaking, git takes some time to get used to. The terminology seems a bit strange, and many things work a bit differently compared to SVN or CVS. Just ask if you have a question, I'll try to answer it :smiley: However, my battery is running low and our daughter is waking up, so I'll be gone for the afternoon, soon :smiley:

**Comment by DirtyHairy** [comment] 2017-07-30 13:47
> So wait until another hour, and I'll get everything updated. Then you can work from there, knowing that everything is in a working state.

Actually, this is a good point. I should try to get myself a virtual windows machine at some point and make a habit of cleaning up the mess I leave behind myself.

**Comment by thrust26** [comment] 2017-07-30 13:51
I doubt I will get used to GIT soon, given the ultra low frequency I am using it. 😇 

For now, I only want to be able to checkout without destroying my environment. Should be possible, no?

Pull was obviously the wrong choice. So how do I do it right? Fetch has lots of options and reports ancient branches (from me and bwmott).

**Comment by DirtyHairy** [comment] 2017-07-30 14:13
Pull **is** correct. In git, a repository is a connected  graph of files, directories and commits. Branches and tags are pointers to commit objects in this graph. **Fetch** pulls in the changes but won't update your local branches. **Pull** will do a **fetch** and then update your branches. Only at this point your working directory will change to reflect the update.

**Comment by thrust26** [comment] 2017-07-30 14:18
Thanks. Then probably to stash was the problem. Anyway, I managed to get it working again and did a few tests. IMO it works nicely. 

@sa666666 I still notice a slight right bias. How about you?

**Comment by sa666666** [comment] 2017-07-30 14:35
Yes, the bias is still there a little.  At this point I don't know what's causing it.  Then again, I don't really understand the original code either.

**Comment by thrust26** [comment] 2017-07-30 15:01
@sa666666 Its not that complicated:
- update() reads the mouse changes, defines the direction and last not least the interval how to spread those changes over the next frame (myTrakBallLinesV/H). 
- read() then distributes those changes based on myTrakBallLinesV/H over the whole frame.

While writing this, I realized that the code is still not 100% correct, because mySystem.tia().height() only returns the **visible** area (correct? I can't debug .hxx for whatever reason). The effect is, that the changes are only distributed over the first e.g. 200 scanlines. And nothing happens in the last 62 scanlines (this might explain why my experiments which tried to poll the trackball outside the kernel never worked as expected).

Can you fix that?

**Comment by sa666666** [comment] 2017-07-30 15:35
@thrust26, I think you just need to change mySystem.tia().height() to mySystem.tia().scanlinesLastFrame().  Can you try that and see if it works for you?  I won't do the commit until you confirm that it's what you need.

**Comment by thrust26** [comment] 2017-07-30 15:42
Works as expected. 👍

**Comment by sa666666** [comment] 2017-07-30 15:45
OK, this is done in https://github.com/stella-emu/stella/commit/04ce40b27c5f41d2cc79c0a3b3f8ca9d9a289c44.

**Comment by thrust26** [comment] 2017-07-30 15:54
GIT doesn't let my pull because I have uncommitted changes in: 
src/windows/Stella.vcxproj
src/windows/Stella.vcxproj.filters

I severely doubt that I should commit those, right? And I found now way to exclude them from updates or manually select the files to update.

**Comment by sa666666** [comment] 2017-07-30 16:05
Those files need to be commit-able, since they contain the files that need to be compiled, etc.  In Linux parlance, they're like Makefiles.  But the only time they should change is when a new file is added to the project, or an old file is removed.  And that shouldn't be happening in your case.  So I guess you edited something you shouldn't have :imp: 

You need to find the option to completely reset what you've done on your side.  On the commandline I would typically do "git checkout ." or "git reset --hard HEAD".  This gets you back to a clean slate, after which you can pull any new changes from us.

**Comment by sa666666** [comment] 2017-07-30 16:07
You may notice that I mention git and the commandline a lot.  IME, the commandline is what you need to use.  I tried TortoiseGit in Windows, and it didn't expose all the options I needed.  And I also tried the Git client built into Visual Studio, and at one point it corrupted my entire local copy.  In the end I used the commandline, just like I do in Linux and OSX.

**Comment by thrust26** [comment] 2017-07-30 16:13
I have removed and added the old and new trackball files to be able to compile. And I changed the SDL include paths. What's shouldn't I have done? 😄 (have you updated the VS project files?)

I used to like the command line, nothing wrong with it. But today, 20, 30 years later, I would have expected it to become more or less obsolete (SVN worked without). I suppose the Linux attitude which prevents this great OS from finally getting common shines through again. I am not a big fan of Windows, but MS got this part right.

**Comment by sa666666** [comment] 2017-07-30 16:15
Sorry, I just noticed that in one of the files (src/windows/Stella.vcxproj), there is specific mention of my personal pathnames on my system.  Obviously these will be different on your system, and this will cause an issue.  So you need to change them on your system, and hence the file changes.

This is a bug.  The files you mention should never have user-specific info in them, for exactly this reason.  I guess this is the first time that two people tried to work on Stella in Windows at the same time.  Pretty sad when you think about it.

For now, try typing "get pull --rebase" to keep your local changes, but also get the new ones.

As for using the GUI vs. commandline, it is fine when everything works.  But when it doesn't, sometimes the only way to fix it is to drop to the commandline.  Of course, my advice is also tainted by the fact that the commandline is what I use everywhere, so obviously it makes more sense to me.

**Comment by sa666666** [comment] 2017-07-30 16:18
To be clear, I'm going to work on fixing the personal information in the Stella.vcxproj files, and update the developer documentation accordingly. Under no circumstances should anyone need to modify these files if they're not adding/removing files from the project.

**Comment by thrust26** [comment] 2017-07-30 16:20
How do I work with the command line? How does GIT know which project I mean?

**Comment by sa666666** [comment] 2017-07-30 16:28
Sorry, I will have to leave this one to @DirtyHairy.  As for the commandline, I have it in Windows for Git, but I don't remember how I set it up.  Again something for @DirtyHairy.

The problems you're having are similar to what was happening for @SpiceWare.  So it might not be much consolation, but you're not alone.

**Comment by DirtyHairy** [comment] 2017-07-30 20:16
You can download a windows installer from the [git homepage](https://git-scm.com/downloads). After installation, git is available on the windows powershell (you might have to configure the path though). The biggest obstacle might be typing in commit messages as it brings up vim by default :smirk:

I'll add some more remarks about using git here when I find time later --- perhaps I might expand this into a short markdown document in the repo in order to ease contributing.

**Comment by thrust26** [comment] 2017-07-30 20:25
VIM? 🙀 👎 ❗️ 

(NOOOOOOO way that I will ever use that)

I am happy with posting the changed code here and avoid GIT that way. 😄

**Comment by sa666666** [comment] 2017-07-30 20:31
OK, that's fine, but in any event your tortured process of trying to build Stella in Windows has pointed out bugs in the process :imp: 

I pushed a change a few hours ago that changes the Stella.vcxproj files to use relative paths, and not have my personal info in them.  Unfortunately (for you, anyway), this means the initial setup procedure will change too.  I still have to update the webpage for that, but overall I think it means less work for someone checking out Stella for the first time.

**Comment by sa666666** [comment] 2017-07-30 20:33
@DirtyHairy, yes, that git and associated bash shell is what I use.  I do everything from that commandline from now on.  And vim is a slight issue, but I've gotten used to it, by having to work on remote systems.  But I agree that it is, in general, horrible.

**Comment by thrust26** [comment] 2017-07-30 20:34
Meanwhile I rather concentrate on improving the code. 😛

**Comment by DirtyHairy** [comment] 2017-07-30 20:36
Actually, I like vim alot. I even used to install vim input plugins into my IDEs :smile: But, as far as git is concerned, it is just a default that can be changed (by changing the EDITOR environment variable).

**Comment by sa666666** [comment] 2017-07-30 20:38
vim is growing on me.  But I'm still not terribly fond of it yet.

**Comment by thrust26** [comment] 2017-07-30 22:09
Attached you find my latest incarnation of the trackball files. I cleaned up the V and H confusion and made some variables local. The code is also prepared for a variable trackball sensitivity (e.g. by -tsense). I increased the sensitivity, it was already a bit low for my taste and the change https://github.com/stella-emu/stella/commit/04ce40b27c5f41d2cc79c0a3b3f8ca9d9a289c44 reduced it even further. 

[trackball.zip](https://github.com/stella-emu/stella/files/1186011/trackball.zip)

**Comment by sa666666** [comment] 2017-07-30 22:52
Implemented in https://github.com/stella-emu/stella/commit/6e4503f76224ef6e1fd3e52c9acdb57f982097dd.

**Comment by ale-79** [comment] 2017-07-31 08:14
I tried Stella with the latest commit applied and it seems to work fine.

The simple test I did was to continuosly trace a circle in the middle of the screen with the cursor in "Missile Command". With the official 5.0.1 release I have to adjust the drift by moving the mouse on the desk to keep the cursor in the center of the screen, while this doesn't seem to happen with the latest build.

I also tried this test rom (it displays numerical values for the two axis and the max per-frame ticks detected, as well as the state of the SWCHA nad INPTx bits - press the button to reset values to zero). 

[tb_test.zip](https://github.com/stella-emu/stella/files/1186813/tb_test.zip)

I placed the mouse in a plastic tray with borders, with a textured enough surface to work with the optical sensor, and moved from one border to the other in both directions, so to have fixed reference points.
It works quite well, with comparable values in both directions, but I noticed that there's some sort of "inertia" effect so that if I move the mouse fast and then instantly stop it (when I reach the tray border), the numerical values in the test rom keep changing for a few frames (I guess that's outside the control of Stella and depends on the OS?), resulting in higher values for the same distance.

**Comment by thrust26** [comment] 2017-07-31 08:18
Could be the result of mouse acceleration enabled for the OS.

**Comment by ale-79** [comment] 2017-07-31 08:22
I'll try playing with mouse settings in Xorg and see if it makes any difference.

> The code is also prepared for a variable trackball sensitivity (e.g. by -tsense). 

That's a good idea, that would allow to more closely match real hardware when using, for example, real trakballs with a 2600-daptor or similar device.

**Comment by thrust26** [comment] 2017-07-31 09:46
There is one detail in the code, which still makes me wonder and a bit worried. Maybe one of you can help me here.

The mouse pointer differences are evenly distributed as SWCHA changes over the next frame. For example a mouse pointer difference of 2 results into SWCHA changes every 262/2 = 131 scanlines. My question is, when should the first change happen? For the example it would currently happen randomly between scanline 0 and 130. The idea behind this is, that the exact change positions are undetermined.

Looking only at one frame, IMO this absolutely makes sense. But for multiple frames maybe not. E.g. for the first frame the first SWCHA change could happen at scanline 10 and (assuming constant mouse speed) at scanline 120 for the next frame (or vice versa). So while the changes are evenly distributed within on frame, they are not over multiple frames. That's my concern.

Before the code had the first change at 131/2 = 65. This evenly distributed the changes over multiple frames, but the changes were all locked at static positions. IMO this is not realistic.

So, what do you think? How can I get the best of both variations? Especially considering that the mouse pointer speed will vary.

**Comment by ale-79** [comment] 2017-08-01 09:01
You could calculate a random (percentage) offset for the first SWCHA change and use that while there's continuous movement of the mouse pointer.
If there was no mouse movement in the current frame, calculate a new offset.

example:

frame 0: no mouse movement -> calculate new random offset, e.g:  65
no changes in SWCHA

frame 1: mouse movement = 2 
1st change: (262/2)*65/100=85
2nd change: 85+(262/2)=216

frame 2: mouse movement = 3
1st change: (262/3)*65/100=57
2nd change: 57+(262/3)=144
3rd change: 144+(262/3)=231

frame 3: mouse movement = 1
1st change: 262*65/100=170

frame 4: no mouse movement -> new offset, e.g: 35
no SWCHA changes

frame 5: mouse movement = 2
1st change: (262/2)*35/100=46
2nd change: 46+(262/2)=177

....

Changes are still locked to static position while there's movement, but at least they will change each time the cursor stops and starts moving again.
Changes are evenly distributed over multiple frames.

**Comment by thrust26** [comment] 2017-08-01 10:29
Interesting idea, thanks! 👍 

This sounds like a perfect solution (and better than my ideas), except for completely randomizing the new offset when there is no movement. In case of very slow movement (less than 1 pixel/frame) the random base would change very frequently and the distribution would become uneven again.

But if the new random value is tied to the previous one (e.g. +/- 10%, maybe something smarter to get an even distribution), then everything should be fine.

**Comment by thrust26** [comment] 2017-08-01 13:02
I implemented Alex' suggestion. The random offset is defined by the previous offset plus a random value (up to 1/8th). Simple enough. I also refactored the code a bit, update() uses the same subroutine for both directions. 

Except for definable sensitivity, I consider this done now. 😃 
[PointingDevice.zip](https://github.com/stella-emu/stella/files/1190634/PointingDevice.zip)

**Comment by sa666666** [comment] 2017-08-01 13:49
Committed in https://github.com/stella-emu/stella/commit/87282e6707417fb1fcda750dac1127d29b7f8786.

As for 'tsense', how should it be implemented (what range should it have)?

**Comment by thrust26** [comment] 2017-08-01 14:13
Like dsense and msense (command line and UI) would be perfect. 1..20 like in the UI should be sufficient. 10 should be (about) like the current trackball sensitivity. Are those values linear for msense and dsense? Then 1 would mean 10% and 20 would mean 200% of the current trackball sensitivity, right? 

The UI seems to be a bit out of space for Devices & Ports. Do you have a plan how to fit it? Maybe the three sensitivities can be grouped? Or just extend the height?

BTW#1: The UI shows a range from 1..20 for dsense and msense, however the documentation has different values for -msense (1..15) and -dsense (1..10). 
BTW#2: I noticed a mouse pointer in some screenshots. 😃

**Comment by thrust26** [comment] 2017-08-01 14:34
And, while you are at it anyway 😉, it would be nice to have controller input for trackballs available in the debugger (like for driving controller, but for both directions).

**Comment by sa666666** [comment] 2017-08-01 14:53
OK, your issues in turn:
- I can have 1-20, with 1 being 10%, 10 being 100% (current) and 20 being 200% (twice as fast).  It can really mean whatever we define it to mean.
- There is sufficient vertical space to add this in the Devices & Ports area.
- The incorrect ranges are just that; typos.  I'll fix it in the manual.
- Controller input for trackballs is already covered under #73, so I will cover that one there.

So once we get tsense and associated UI implemented, we can close this issue.

**Comment by thrust26** [comment] 2017-08-01 14:56
I doubt 1 for tsense would make much sense, but who knows. And msense at 1 is dead slow too, so let's do it like that.

**Comment by sa666666** [comment] 2017-08-01 17:31
@DirtyHairy, I need some advice on template programming, as I'm more used to inheritance.  So I create a static method to set the sensitivity as mentioned above:

```
template<class T>
void PointingDevice<T>::setSensitivity(int sensitivity)
{
  ourSensitivity = (double(sensitivity) / 10.0) * T::trackballSensitivity;
}
```
And then use ourSensitivity instead of T::trackballSensitivity elsewhere.  ourSensitivity is declared as static.  Problem is, how do I call this method?  I've tried
```
TrakBall::setSensitivity(sensitivity);
```
but that results in the static variable not being updated.  I sort of know what's happening, but don't really understand templates enough to fix it.  Advice??

**Comment by thrust26** [comment] 2017-08-01 17:43
I may not be the expert you need, but IMO setSensitivity and ourSensitivity both belong into PointingDevice (the latter as a simple, private member.

**Comment by sa666666** [comment] 2017-08-01 17:50
I only mentioned @DirtyHairy because I thought he was the one that wrote this template code.  If you did, then perhaps you can answer it. :smile: 

If using inheritance, the reason for making something static is that all subclasses can share it, and I can simply call BaseClass::someFunction(). IOW, I want to call the function without having had to create an instance of the object; aka, the perfect use for static.

Now templates don't work the same way, since there is no base class.  Or more specifically, the base class (if you can call it that) is PointingDevice<T>, but at the time of invocation I don't know what 'T' is.  Nor do I want to care; I just want PointingDevice to hold the value I pass to it.

**Comment by thrust26** [comment] 2017-08-01 18:03
No, I didn't write the template code, I most likely would have used inheritance too. And my knowledge is limited.

So I could only offer vague guesses. 😄

**Comment by sa666666** [comment] 2017-08-01 18:08
OK, I'll wait to hear what @DirtyHairy has to say.  Other than that issue, I've implemented the 'tsense' setting and associated UI stuff.

**Comment by thrust26** [comment] 2017-08-01 18:15
Once you have committed your changes, how can I retrieve them without overwriting my project settings?
(I don't care for any code changes I did)

**Comment by sa666666** [comment] 2017-08-01 18:25
I don't know if you've been following the commits over the past few days, but I've modified the Stella.vcxproj file to not have user-specific information in it (ie, it will no longer contain hard-coded paths for my personal system).  That was the reason why the file differs on your system too; the instructions on the Stella development webpage specifically say to modify the file and add paths on your system.

In any event, I've fixed the problem in the Stella.vcxproj file.  But now the instructions for checking out Stella from Git have changed slightly, for the better I hope.  It is now much easier if you're using Windows.   
 The only issue is, I haven't updated the documentation yet :imp: 

Unfortunately. when I do, you will need to re-read them and redo some of the initial setup.  At that point, you can blow away any local changes and start fresh.  I will let you know when this is done, and how to clean up your local changes.

**Comment by thrust26** [comment] 2017-08-01 18:29
I just saw the changes in VC++ Directories. And after some trial and error I found the right place for the SDL directory. 😄 So pull worked for me.

Thanks for the update! 👍

**Comment by sa666666** [comment] 2017-08-01 19:00
OK, good that you have it figured out.  In any event, the online docs have now been updated.

**Comment by DirtyHairy** [comment] 2017-08-01 20:29
@sa666666 , the catch with the template is that each instantiantion of a template class with a different template argument counts as a separate class. So, you can call `TrakBall::setSensitivity` just fine, and it will indeed update the static variable, but only scoped to `TrakBall` aka `PointingDevice<TrakBallHelper>` --- the other two instantiations have their own versions of `ourSensitivity`. I've hacked up a brief example to illustrate what I mean:

```
#include <iostream>
#include <string>

template<class T> class Foo {
    public:
        static std::string hanno;

        static void setHanno(std::string _hanno) {hanno = _hanno;}

        static void dump() {std::cout << hanno << "\n";}
};

template<class T>
std::string Foo<T>::hanno = "";

class Fuppe {};
class Foppe {};

typedef Foo<Fuppe> Hanni;
typedef Foo<Foppe> Nanni;

int main() {
    Hanni::setHanno("hi from hanni");
    Nanni::setHanno("hi from nanni");

    Hanni::dump();
    Nanni::dump();
}
```

The output is
```
hi from hanni
hi from nanni
```
If you need something that is common to all three classes I'm afraid you're going to need a global variable.

I'm now off to five days of booze, beer and heavy metal :smile: :beer: :metal: Talk to you all again next week!

**Comment by thrust26** [comment] 2017-08-01 20:45
Refactoring again?

**Comment by DirtyHairy** [comment] 2017-08-01 20:47
> Refactoring again?

I'd just add a global variable in an anonymous namespace ;) That's what a static field is anyway: just a glorified global :smile:.

**Comment by thrust26** [comment] 2017-08-01 20:55
I think Stephen only needs the local variable of the current controller to update. And that doesn't work too.

**Comment by DirtyHairy** [comment] 2017-08-01 21:00
I don't know the specifics of Stephen's code, but setting static variables on template class **instances** definitely works --- see my example. You just have to be wary that the template class itself does not exist, just its various instantiations.

**Comment by sa666666** [comment] 2017-08-01 22:28
Yes, a global variable will work, but it somehow feels dirty :smile:   Anyway, I'll think of something.  If all else fails, I'll just convert it to use inheritance instead.

**Comment by DirtyHairy** [comment] 2017-08-02 05:31
@sa666666 , @thrust26 Thanks alot!

**Comment by sa666666** [comment] 2017-08-02 19:31
This is now implemented in https://github.com/stella-emu/stella/commit/d22ed691b599af56b18a0852b92253bf12f797c5.  'tsense' is available as a commandline argument, as also in the UI.

@thrust26, please test, and if acceptable, go ahead and close this issue.

**Comment by thrust26** [comment] 2017-08-02 20:02
Looks and work good (UI and command line). And thanks for cleaning up my float/double mess.

One question about the command line parameters: Some command line parameters (like -d/m/tsense) seem to be global (and persistent) and some (e.g. -pp) only temporary(?) for the current ROM. Is there some logic behind that? The doc doesn't tell anything (read: I found nothing). 

IMO it would be most logical that a parameter provided with a ROM name only works for the current ROM, while the same parameter provided without a ROM name is global and persistent.

BTW: I defined PointingDevice::updateDirection(const int& counter...), wouldn't a simple (int counter...) be better?

**Comment by sa666666** [comment] 2017-08-02 20:29
BTW1 is fixed in https://github.com/stella-emu/stella/commit/b23830487dc2b78a95c700a933949940a1ffcdbd.  It was a minor point, but we may as well fix it.

BTW2, I will have to look into it.

As for the persistent vs. temporary setting of some options, it comes down to how they're supposed to be used.  In particular, anything that changes ROM properties is temporary; my reasoning is if you want to do that, you should use the UI.  Some others, like 'holdselect', 'holdreset', etc are obviously temporary in nature, and shouldn't be saved.

There actually aren't all that many non-persistent settings, but the ones that are non-persistent are that way for a reason.  If you want to discuss these further, lets open another issue for it.  I will close this one now.

**Closed by sa666666** 2017-08-02 20:29 UTC
Labels: bug

**Comment by thrust26** [comment] 2017-08-02 20:40
Its a minor problem anyway, so I won't open an issue for this. But maybe the doc should give a hint.

**Comment by sa666666** [comment] 2017-08-02 21:00
I just sent an email for you to join a mailing list for Stella commits.  It seems that github doesn't offer this functionality, so (per instructions I found on the web) I had to create a google groups email list instead.

**Comment by thrust26** [comment] 2017-08-02 21:03
I have joined now. You test commit didn't work, because I first had to enable notifications. Can you try again?

**Comment by thrust26** [comment] 2017-08-02 21:08
Works! 👍

**Comment by thrust26** [comment] 2017-08-03 05:42
> Oh, and have a good time at whatever it is you're going to 😃

Must be this: www.wacken.com

**Comment by DirtyHairy** [comment] 2017-08-05 09:50
The mud adds to the experience 😛 Muddy greetings!

**Comment by thrust26** [comment] 2017-08-05 10:14
![media media d82479b0-2a85-4782-83b1-6f3ee82a17be original1024](https://user-images.githubusercontent.com/24360774/28994820-a525b6b2-79d7-11e7-9974-609561b8562e.jpg)
![media media e0261360-e82b-4537-a09a-4264b4bae6c8 original1024](https://user-images.githubusercontent.com/24360774/28994818-a2403634-79d7-11e7-82c9-cf6670434ad6.jpg)

**Comment by DirtyHairy** [comment] 2017-08-05 11:07
https://goo.gl/photos/P9Ae24RhjLzN6g7j7

**Comment by DirtyHairy** [comment] 2017-08-05 11:08
We call it "The bridge of death"

**Comment by thrust26** [comment] 2017-08-05 11:27
How many "deaths" so far?

**Comment by DirtyHairy** [comment] 2017-08-05 11:35
None witnessed, but there's currently a guy standing at the other side, stick in hand and asking the famous three questions 😀
