### ISSUE TITLE
Wrong file type detection in ZIP files

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#851] opened 2021-12-03 22:28 UTC
A non-ROM file is detected as directory inside a ZIP file.

[ziptest.zip](https://github.com/stella-emu/stella/files/7652643/ziptest.zip)

**Comment by sa666666** [comment] 2021-12-03 23:24
In Linux, the 'readme' is shown as a dir folder, but 'entering' it plays it as if it's a ROM file.  So as you say, it's just the detection that is off.

**Comment by sa666666** [comment] 2021-12-05 02:08
Confirmed; I see the problem.  It considers a valid ROM as a file, and everything else a directory.  The code needs to be reworked to mark a directory as such, and everything else a file.  Working on it ...

**Comment by sa666666** [comment] 2022-06-12 19:26
I know now what the issue is, but it will have to wait until the `FSNode` API is simplified, when we move to `std::filesystem` in C++17.

**Comment by sa666666** [comment] 2023-08-01 20:10
@thrust26, I am now looking at this again.  And I still wonder why we even need to show non-ROMs in the Stella launcher at all?  All that will happen when attempting to run them is to get a message that it can't be done.  If we only allow showing ROMs and directories, then the UI gets simpler, and this issue disappears.

**Comment by thrust26** [comment] 2023-08-01 20:22
As of now it only gives an overview of other existing files. And maybe it could be used to display e.g. text files (manuals) in the future. But generally it doesn't make much sense. It was always there, so I never wondered about it. 

It is a problem?

**Comment by sa666666** [comment] 2023-08-01 20:27
Yes, it complicates fixing this very issue when dealing with ZIP files.  So if it isn't necessary and we can't see a use case for it, I would like to remove it, and in the process make this issue moot.

**Comment by sa666666** [comment] 2023-08-01 20:28
I probably added this sometime in the (far) past, and no longer know why I did it :smiling_imp:

**Comment by thrust26** [comment] 2023-08-01 20:53
Remove it then. Fine by me.

**Comment by sa666666** [comment] 2023-08-02 20:51
Fixed in https://github.com/stella-emu/stella/commit/49fb4d01bb819628d07f3716a1bf1f8afa650751.

**Closed by sa666666** 2023-08-02 20:51 UTC
Labels: bug
