### ISSUE TITLE
Selectable text in debugger... or save of dump... please?

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#527] opened 2019-08-24 23:36 UTC
It would be really nice to be able to copy text from the debugger output window.
For example, if I wanted to dump RAM via dump command, then to be able to copy those bytes into the clipboard. Perhaps the 'dump' command could have an optional filename to allow the dump to be saved?
One use case: 'recording' gameplay joystick commands to a buffer, then doing a dump of the buffer so that the commands can be used for a demo mode. That is, process the human's input into a 'demo' mode feed of joystick values instead of from the controller.
Second use case - dump RAM for comparitive analysis between runs of a program.

**Comment by sa666666** [comment] 2019-08-24 23:43
I believe this is a duplicate of https://github.com/stella-emu/stella/issues/105.

And I believe it's already possible to save the contents with 'saveses' (although there could many improvements made to this).

**Comment by andrew-davie** [comment] 2019-08-24 23:49
> I believe this is a duplicate of #105.
> 
> And I believe it's already possible to save the contents with 'saveses' (although there could many improvements made to this).

I did actually spend some time looking at the help list in the console before posting. However it did not occur to me that saving the console output would be fine. It will, thanks.

**Comment by thrust26** [comment] 2019-08-25 06:33
Shall we close this one?

**Closed** 2019-08-25 06:54 UTC
Labels: debugger, enhancement
