### ISSUE TITLE
HMOVE behavior varies between different TIA generations

### ISSUE THREAD

**Issue by SvOlli** [stella-emu/stella#246] opened 2017-10-24 17:45 UTC
Hello,

toying around with triggering HMOVE not directly after triggering WSYNC, I noticed that Stella did not produce the same visual output as my PAL 2600 jr. does. I've narrowed this down to a small example. It triggers HMOVE every 75/77 cpu cycles (selectable with left difficulty), the sprite is configured to be moved one pixel to the left/right (right difficulty), it tries to move towards the center of the screen.

Example images from my 2600 jr are included. The example os provided as binary and ca65 sourcecode.

It seems that I can't attach the file, so you can download it at [http://i.svol.li/oddhmovetest.zip](http://i.svol.li/oddhmovetest.zip).

**Comment by thrust26** [comment] 2017-10-24 18:44
File attached
[oddhmovetest.zip](https://github.com/stella-emu/stella/files/1412075/oddhmovetest.zip)

**Comment by thrust26** [comment] 2017-10-24 18:46
@SvOlli Have you tried a non-Jr console too? Same results?

**Comment by DirtyHairy** [comment] 2017-10-24 18:58
@SvOlli , @thrust26 I'll add a more detailed analysis soon, but I agree: it would be very interesting to see how non-Jr consoles react to this.

**Comment by DirtyHairy** [comment] 2017-10-24 19:17
First of all, I think your testcase (thanks alot for it) has a minor flaw: sprite positioning overwrites HMP[01], so them configures movement is not +- 1 pixel. I have attached a modified version of the test that fixes this here: 
[modified_test.zip](https://github.com/stella-emu/stella/files/1412174/modified_test.zip)

With this, I get the following shots on my PAL Jr.:

Movement to the left:
![img_20171024_210532](https://user-images.githubusercontent.com/2444224/31963160-159a28da-b900-11e7-919f-c8915e697c74.jpg)
Movement to the right:
![img_20171024_210512](https://user-images.githubusercontent.com/2444224/31963161-15bc1b2a-b900-11e7-8cf7-edc824e414e0.jpg)

In Stella, those look like this:

Movement to the left:
![oddhmovetest](https://user-images.githubusercontent.com/2444224/31963278-692c947e-b900-11e7-8230-a1805ef3d502.png)
Movement to the right:
![oddhmovetest_1](https://user-images.githubusercontent.com/2444224/31963311-7e5aba1a-b900-11e7-9420-58981081ce8c.png)

**Comment by thrust26** [comment] 2017-10-24 19:39
My PAL Vader looks like Stella, so I suppose this is a compatibility issue.

**Comment by DirtyHairy** [comment] 2017-10-24 19:44
What is going on here is the effect described in Andrew Notes under "HMOVE during visible scanlines".

As you propably know, HMOVE works by 1. extending HBLANK by 8 color clocks and 2. sending a variable number of extra clocks down the lines to the sprite counters during HBLANK. If no clocks are sent, the sprite will move 8 pixels to the right, and every extra clock reduces this movement by one, giving -7 to 8 pixels of horizontal movement. If you invert the highest bit of HMPx and shift four bits to the right, you get the full number of clocks.

The interesting part is what happens when the extra clocks are sent after HBLANK. As they go down  the same lines as the regular clock pulses, the naive assumption is that they fall together with those and have no effect. This is what Stella currently emulates --- the effect is visible in the screenshots: 

* At the start of each HBLANK block, we get nice and steady motion.
* As the clock where HMOVE is strobed gets closer to the boundary of HBLANK, more and more extra clocks are gobbled, and the movement goes farther to the right.
* After HBLANK, all clocks are gobbled, and the sprites remain stationary
* As we close in on late HMOVE, extra clocks start falling into the next HBLANK interval, and sprite starts moving to the left
* After the line end is crossed, the extended HBLANK interval kicks in, and the sprite starts moving to the right again.

As already indicated by ATs experiments, reality seems to be more complicated :smirk: Depending on the phase between the extra clocks and the regular clocks, the extra clocks "stuff" the gap between those, virtually gobbling them. This is what causes the large jumps to the right by 7 / 0 pixels that we observe on real hardware. However, even more funky things seem to happen:

* Some jumps are even wider. This *might* be related to the shape of the extra pulses --- if they are wider, they could swallow up more than two consecutive clocks. A discrete TIA and a logic analyzer might help :smile:
* Some sprites seem to be elongated. I guess this means that the graphics scan counters might be affected by those clocks, too
* The size of P0 (not P1) oscillates on my Jr. at certain positions. This makes sense as we are essentially watching a beating effect that is sensitive to the phase of the two signals.

Emulating parts of this effect would be easy enough (the clock gobbling part). However, simulating the aforementioned extra wide gaps and the modulation of the sprite width may be impossible to do reliable without **a lot** trial and error, and a lot of testing will be required to make sure the description is accurate enough to avoid regressions.

Also, I have a strong feeling that these effects depend on the TIA generation, and I would very much like to see more results on different consoles before touching the emulation.

**Comment by DirtyHairy** [comment] 2017-10-24 19:45
This might be a nice point to start adding support for various TIA models :smile: However, I think 100% accurate emulation may not be worth the effort here.

**Comment by thrust26** [comment] 2017-10-24 20:05
Maybe not here. But e.g. the starfield trick is quite frequently used.

BTW: I have added **very** basic (just initial RAM and pause key) support for the 7800 lately.

**Comment by DirtyHairy** [comment] 2017-10-24 20:20
WTF. I thought "let's have a quick shot at this before doing the kitchen and calling it a day". This is the result of simulating the gobbled clocks:

![oddhmovetest](https://user-images.githubusercontent.com/2444224/31965718-827e2b56-b908-11e7-925a-7a23eecd3f3b.png)
![oddhmovetest_1](https://user-images.githubusercontent.com/2444224/31965728-883c2836-b908-11e7-86aa-0693e34ed746.png)

If I am not mistaken, this is pixel perfect! Remarkably enough, this also describes the elongation **and** the extra wide jumps perfectly. I guess the wide jumps are not so funky after all, but "just" the effect of the extra pulses the clocking delay before rendering starts :smirk:. Now what to do with this...

@thrust26 ? @sa666666 ? I am inclined to add this to the next release behind an option. We should also test other known deviation between TIA revisions against this, it might describe some of these effects, too.

**Comment by DirtyHairy** [comment] 2017-10-24 20:23
I have pushed the change to a branch if you want to play around with it: https://github.com/stella-emu/stella/tree/feature/tia-jr

**Comment by DirtyHairy** [comment] 2017-10-24 20:30
I also have to find out how this relates to the starfield, as the mechanics are pretty much the same there. So, propably no release in the next version after all :smirk:

**Comment by thrust26** [comment] 2017-10-24 20:38
Very cool! 👍

**Comment by SvOlli** [comment] 2017-10-24 20:41
I'll have to second that. And I'll have to digg through the source code, where the difference between the two different versions of the chip are... for what I wanted to do in the first place.

Thanks!

**Comment by sa666666** [comment] 2017-10-24 21:05
It always amazes me how such a small change in the code can magically emulate new findings.  To me, this says that the emulation is quite robust and only needs minor 'fixups' here and there to properly emulate all versions of the TIA.

**Comment by DirtyHairy** [comment] 2017-10-24 21:58
> And I'll have to digg through the source code, where the difference between the two different versions of the chip are... for what I wanted to do in the first place.

@SvOlli I think the upshot of your and @thrust26 findings is that HMOVE outside HBLANK is unreliable across TIA generations :smirk: On the Jr., the extra clock pulses gobble up regular clock pulses and delay the sprite counters, while they are without effect on @thrust26 's Vader.

> It always amazes me how such a small change in the code can magically emulate new findings. To me, this says that the emulation is quite robust and only needs minor 'fixups' here and there to properly emulate all versions of the TIA.

I agree :smile: I am particularly amazed by the number of features that I didn't expect to be reproduced --- it is fascinating how the interaction between those counters can create complex effects.

Another interesting thing is the fact that, while some individual sprites still appear slightly shifted or elongated with my change, the differences cancel in the sum. I guess the remaining discrepancies are connected to the exact part of the signal (combined extra + regular clock) that triggers the counter transition, and I can get a bit closer by fiddling around with the equivalents in the emulation. However, I suspect that this might be different even between differen Jr. TIAs and a pain in the a** to emulate in any case --- I am inclined to live with those for the moment.

**Comment by ale-79** [comment] 2017-10-26 21:22
The behaviour of my 7800 changes as it warms up.
It starts like this:
![cold](https://user-images.githubusercontent.com/24704739/32077197-d7237094-baa2-11e7-8f15-47480f9f7115.jpg)

And, gradually changes until it stabilizes to this (after about 2m30s):
![warm](https://user-images.githubusercontent.com/24704739/32077213-de870666-baa2-11e7-8f79-139a6878c62d.jpg)


I used the "modified_test.zip" posted by @DirtyHairy, with both difficulty switches set to A

Here is an extremely low quality video to see it in action:
[hmove_test_7800.zip](https://github.com/stella-emu/stella/files/1420082/hmove_test_7800.zip)

**Comment by thrust26** [comment] 2017-10-27 06:35
Wow! It almost looks like the console is alive and awakening.

Emulating that seems pretty challenging. But maybe @DirtyHairy can gain some info from the video.

**Comment by sa666666** [comment] 2017-10-27 11:45
Yep, I don't think emulating that will be feasible, since perhaps no two TIA chips behave exactly the same way.  We're now getting into undefined/warm-up behaviour of the system, which may be nearly impossible to duplicate.  I would be satisfied if Stella could emulate the final result (@ 2m30s), or IOW a stable system.

**Comment by DirtyHairy** [comment] 2017-10-27 22:18
Thanks alot, @ale-79 ! To me, this looks like the phase two different clocks I described is drifting during warmup. Emulating a approximation the two different states (no extra clocks vs. gobbled clocks) is definitely possible.

An accurate emulation may be impossible of scope, as I suspect the exact shape of the signal and, consequently, the visual details may vary from console to console. However, I still have to do some testing before I do any serious work on this. In particular, I want to look at the starfield and write a test (a have been planning for a long time) that cycles through the different objects and NUSIZ values.

Also, I propably should work on automated regression tests by screenshotting before doing any changes to HMOVE behavior :)

**Comment by thrust26** [comment] 2019-05-16 21:29
With the new TIA developer options, we can close this one.

**Closed by thrust26** 2019-05-16 21:29 UTC
Labels: affects 6502.ts, enhancement
