### ISSUE TITLE
colour/banding/scaling issue

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#525] opened 2019-08-21 00:31 UTC
The image shows a local build, left, and release build, right.
On the left, the scaling appears to be causing banding issues - it's faint, but there. It looks much worse on brighter screens. The scaling also, in this case, causes a significant brighness loss because of the contribution of surrounding black scanlines. This is not evident in the release version.

<img width="1263" alt="Screen Shot 2019-08-21 at 10 25 59 am" src="https://user-images.githubusercontent.com/16424075/63393502-c2463000-c3fe-11e9-9657-a09ebf2e1260.png">

The horizontal lines are spaced every 3 scanlines. The banding causes the lines to appear slightly different intensities. On the right, you can see the scaling is slightly different, and we don't see those effects. I have the scale set to 200% for the local build, and "Zoom 2x" for the release. These should give identical visuals. They don't.
So, this is an issue for me - I don't want to see banding effects caused by scaling. Particularly when scaling by "whole values". In particular, if I select 200% scale, I would hope/expect the scanlines are exactly 2x the size. Clearly they are not, as shown by the difference in vertical size between the two. What's happening here?  Is this a bug, and can it please be fixed?

**Comment by sa666666** [comment] 2019-08-21 00:56
This looks _very_ familiar to something we changed (and supposed to have fixed) in a previous commit.  @DirtyHairy  or @thrust26, do either of you remember the commit where we removed scanline interpolation or something related to that?  Because this 'banding' is exactly what we used to see back then.

**Comment by andrew-davie** [comment] 2019-08-21 05:25
... also compare the quality of the images. Current release on the left, beta2 on the right. Both displaying PAL with the same palette. There is a very large degradation in image quality happening here.
<img width="175" alt="blur" src="https://user-images.githubusercontent.com/16424075/63404776-df432900-c427-11e9-81e1-11669ca6e74e.png">

**Comment by thrust26** [comment] 2019-08-21 07:23
@andrew-davie The right one is definitely with scanlines enabled. So you should disable that, if you dislike the effect.

**Comment by thrust26** [comment] 2019-08-21 07:29
> This looks _very_ familiar to something we changed (and supposed to have fixed) in a previous commit. @DirtyHairy or @thrust26, do either of you remember the commit where we removed scanline interpolation or something related to that? Because this 'banding' is exactly what we used to see back then. 

@sa666666 We have removed the option to disable scanline interpolation. That's always enabled when scanlines are enabled. I think that's what you remember here.

But the problem here seems different and related to the WIP aspect ratio topic. Previously, the height of a pixel was fixed and we changed the width to correct the aspect ratio (especially between NTSC and PAL). But to correctly emulate a TV, the height of a pixel must vary instead. This seems to cause what Andrew is reporting (I already had mentioned that we might need a mode with integer pixel widths and heights, especially for developers).

@andrew-davie Anyway, a quick fix should be to set aspect ratio to 1.0.

**Comment by andrew-davie** [comment] 2019-08-21 10:05
Image shows aspect ratio at "100%" and I have disabled scanlines.
There are still the issues in the scaling of the screen, I think...!  But yes, the man does look better. And it's oh so dark because I've been developing all this time using the Z26 palette and have only just realised that it present dark colours as quite bright. So now I'm using the standard palette, I have to go and fix up all my colours :)
But that's a separate issue. Here we see the scaling artefacts are not cured by "aspect 100%".

<img width="648" alt="Screen Shot 2019-08-21 at 8 01 14 pm" src="https://user-images.githubusercontent.com/16424075/63423035-d1ed6500-c44e-11e9-8758-d5054c83016e.png">

**Comment by DirtyHairy** [comment] 2019-08-21 20:35
Hm, I can confirm the banding on my Macbook --- this is a Moirée pattern between the line pattern in the game and the display resolution. I remember that we changed the way scaling works, so I am not overly surprised. 

However, what seems curious is that enabling TIA interpolation now looks much blurrier to me, too --- did we perchance reduce the resolution of some immediate surface?

A way for reducing the banding effect due to the scaling would be to support HIDPI --- this made the effect almost indiscernible in Stellerator.

**Comment by thrust26** [comment] 2019-08-22 07:00
@andrew-davie To fix the banding (this is inevitable with correct scaling) enable TIA interpolation.

@DirtyHairy It doesn't look blurrier to me.

**Comment by andrew-davie** [comment] 2019-08-22 07:05
> @andrew-davie To fix the banding (this is inevitable with correct scaling) enable TIA interpolation.
> 
> @DirtyHairy It doesn't look blurrier to me.

I disagree. Thought experiment - scale to 200%.  Scanlines are now exactly 2 lines deep instead of one. Exactly. That is "correct scaling". They are not interpolated to something slightly less than 2 lines deep, as appears with the current implementation.

**Comment by andrew-davie** [comment] 2019-08-22 08:09
I just wanted to comment that "TIA interpolation" does significantly improve the image.

I also understand the complex issues regarding aspect ratios and keeping the same window size while rendering either 262 or 312 lines to that window. I would prefer/like to be able to say "hey, I want one scanline per line" and bugger the window size, adjust it as required. But that's another issue, I suppose.

**Comment by andrew-davie** [comment] 2019-08-22 08:23
TIA scaling at 200% looks banded. TIA scaling to 225% (PAL) looks great, so I'm happy to use that and stop complaining. It's just a bit disappointing that the 3-line striped kernel I use is going to look banded/poor for most users.

**Comment by thrust26** [comment] 2019-08-22 21:35
If a scanline is 2 lines tall for NTSC, how tall would it be for PAL? See the problem?

**Comment by andrew-davie** [comment] 2019-08-23 00:33
> If a scanline is 2 lines tall for NTSC, how tall would it be for PAL? See the problem?

As I said, I understand the issues. It's because of how you **think** about what the user is asking for. Your view is that the user wants to fit either a PAL or a NTSC image in a particular sized window, without changing the window size. My view was that the user is asking for the size of the image to be stretched vertically by the scaling factor and thus for PAL and NTSC, a 2-line tall scanline would be 2 lines for PAL, 2 lines for NTSC. But the screen size would be different as a consequence.

I'm OK with how it is now, though it is not how I would implement it.

**Comment by sa666666** [comment] 2019-08-23 00:42
The window size being different for NTSC vs. PAL is how Stella operated for its entire lifetime, up to about a month ago.  We are now pushing for a realistic representation of how a TV actually works, and in that case, the TV screen doesn't change size in NTSC vs. PAL.  The new code added over the past month or two (still being worked on) emulates this idea.  Although I will concede that perhaps for developers, there needs to be a mode that is pixel-accurate, and changes window height if necessary.

This is really just a symptom of a larger problem, though.  We are trying to emulate an analog device with variable-height scanlines in a digital framebuffer.  From that POV, it's just another example of integer vs. non-integral scaling.  That's why choosing a larger zoom level lessens the effect; one has more pixels to work with, and the discrepancy between real and emulated scanline height is diminished.

Going forward, we may potentially have to accommodate both approaches, or possibly insist that the minimum window size is large enough to hide such effects.

**Comment by DirtyHairy** [comment] 2019-08-23 11:38
Those are the results of TIA interpolation on my Macbok with Stella 6.0 and the current development version. If you compare them side by side, you can see that the new one is blurrier.

Both are taken with TV effects turned off.

Development version, TIA zoom 275%:

<img width="885" alt="image" src="https://user-images.githubusercontent.com/2444224/63590049-06763380-c5ab-11e9-8149-c42afe0e2c9b.png">

Stella 6.0, 3x zoom

<img width="872" alt="image" src="https://user-images.githubusercontent.com/2444224/63589930-b26b4f00-c5aa-11e9-8206-79818aed178d.png">

**Comment by thrust26** [comment] 2019-08-23 15:29
Yup, that's the result of scaling vertically with fractional numbers. I cannot see how this can be avoided. But we could add an option which does scale non-fractional.

**Comment by DirtyHairy** [comment] 2019-08-23 16:36
Are you sure? Note that this is TIA scaling, which (afaik) is just bilinear texture filtering at the level of SDL. I would have assumed that an integer scale factor should be pretty similar to a noninteger factor of roughly the same value.

**Comment by DirtyHairy** [comment] 2019-08-23 16:45
Thinking a bit more about how bilinear scaling actually works, I guess you are right 😏 . I rest my case.

**Comment by DirtyHairy** [comment] 2019-08-23 17:21
Although, what I think could improve scaling quality, is to first do nearest-neighbour-scaling to the closes integral factor (in each direction), and then do bilinear scaling to the final dimensions. So, i.e., if you scale an image of dimension 100x100 to 483x524, first scale to 400x500 and then to 483x524.

**Comment by sa666666** [comment] 2019-08-23 17:32
All this is really an issue with https://github.com/stella-emu/stella/issues/368.  That's where this whole 'scaling thing' started.

**Comment by thrust26** [comment] 2019-08-23 21:06
Yes. There I also mentioned the non-fractional pixel sizes.

**Comment by sa666666** [comment] 2019-08-23 21:07
What I meant was that since this issue is because of the other one, perhaps this one is redundant.

**Comment by thrust26** [comment] 2019-08-23 21:08
> Although, what I think could improve scaling quality, is to first do nearest-neighbour-scaling to the closes integral factor (in each direction), and then do bilinear scaling to the final dimensions. So, i.e., if you scale an image of dimension 100x100 to 433x524, first scale to 400x500 and then to 433x524.

I am not sure if that works. Else this would be implemented already.

**Comment by thrust26** [comment] 2019-08-23 21:11
> What I meant was that since this issue is because of the other one, perhaps this one is redundant.

We could merge them, yes. But maybe better handle the issue one by one, You decide.

**Comment by DirtyHairy** [comment] 2019-08-23 21:55
> I am not sure if that works. Else this would be implemented already.

Consider a 1D example. An image is a step function with the individual steps centered at the integral pixel coordinates. If this is upscaled by a fractional factor, the resulting upscaled image samples the original image at fractional coordinates between the centers. The resulting value has a discontinuity at the step boundary, and this gives rise to visible aliasing artifacts.

Bilinear scaling replaces the steps with linear slopes that interpolate the pixel values between the pixel centers. Sampling this function at fractional coordinates smoothly interpolates between the different pixel values, eliminating the aliasing artifacts at the price of blur. If you upscale an image by a factor of 3.3, a white-black transition in the original image will take 3.3 pixels in the destination image to decay --- the visible "blur radius" is 2.3 pixels.

If you upscale by a factor of 3 first, the resulting intermediate image still has sharp transitions. If you upscale by another factor of 1.01 (with bilinear scaling) to achieve the 3.3, then a white-black transition in the original image will only take 1.01 pixels in the destination image to decay (that's the distance of the last white pixel and the next black pixel in the intermediate image) --- the blur radius is much smaller.

I am pretty sure that this works, and I would be surprised if this weren't implemented somewhere else already. I'm not saying that we should implement this in Stella to try out, plain bilinear scaling is imho good enough, but that's something that I'd eventually like to play with.

**Comment by f21red** [comment] 2019-08-23 22:13
When using Retroarch shaders, oversizing the image with Nearest Neighbor then using Bilinear to drop it down to target resolution creates nice, clean sharp pixels. I think there's a shader called Bilinear-Sharp that specifically does this with hardware.

When we go the other way (NN closest) and use Bilinear to scale up to the target, it's kinda fuzzy compared to the downsampling version.

**Comment by sa666666** [comment] 2019-08-23 22:21
A potential problem with these approaches is that we're limited by what SDL provides through its 'render' API.  To do some of these things properly, we may need to access the graphics API directly, and write code specifically for OpenGL(ES), Direct3D, Metal, etc.  And then we get into differences in both API's, versions of API's, shader languages, etc.

I originally moved Stella away from that, since it was too much to handle for one person (ie, me).  The SDL Render API abstracts all that away, and if we break the abstraction we pay a heavy maintenance cost.

**Comment by DirtyHairy** [comment] 2019-08-23 22:53
@f21red Thanks, this is precisely what I had in mind (with the delta that I didn't necessarily consider overscaling, but scaling with the nearest integral factor).

@sa666666 This could be done solely with SDLs render API: the first step (integral scaling) is blitting to a dedicated texture without the `sdl_render_hint_quality` hint set to 0, and the second step is blitting to another texture with `sdl_render_hint_quality` set to 1.

**Comment by sa666666** [comment] 2019-08-23 23:31
There's a facility in the render API to blit to a streaming, hidden texture, that may be useful here.

**Comment by thrust26** [comment] 2019-08-24 05:53
@DirtyHairy You got me convinced.

**Comment by DirtyHairy** [comment] 2019-08-25 18:53
I created two new issues (for MacOS Retina support and improved TIA interpolation): #528 + #529

**Comment by thrust26** [comment] 2019-09-05 10:15
@DirtyHairy Is everything covered by the new issues? If yes, we can close this one.

**Comment by DirtyHairy** [comment] 2019-09-05 19:40
👍

**Closed by DirtyHairy** 2019-09-05 19:40 UTC
Labels: enhancement
