### ISSUE TITLE
New Audio - Regression test ROMs

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#311] opened 2018-05-14 20:12 UTC
These are ROMs which should be tested:
- Ms. PacMan 
- E.T. 
- Stargate (Defender II)
- Quadrun
- Hole Hunter
- Q-Bert
- Stone Age

**Comment by sa666666** [comment] 2018-05-15 14:18
Current issues:
- Stargate (Defender II) still has some very slight static, if that's what you can call it.
- Stone Age has off-key notes at certain points, and when it happens there are 'underrun' message appearing.
- Some ROMs have an audible 'click' or parts of other sounds upon startup.  It could be because of previously loading a ROM, sound emulation not kicking in until a few frames have passed, garbage in the sound queue, etc.
- Thrust ROM ([phaser06.zip](https://github.com/stella-emu/stella/files/2005321/phaser06.zip)) now sounds correct.  Much worse than the old core, but matches real hardware.  One thing that happens, though, seems to be related to the previous point; it starts playing in the idealized way (like Stella 4), then after a second or so goes to the proper way (like real hardware).  So again, it seems that the sound emulation isn't kicking in until a frame (or so) have passed.

Working well:
- E.T. and Ms. Pacman now sound like the real thing.  The former finally has the ship landing sound working properly (a first for any 2600 emulator, besides Stellerator of course).  The latter now has the interference of channels properly emulated.  Again, a first for any 2600 emulator.

Overall:
- No lag on my systems at all.  All can do 44100/48000, only some can do 96000.  Similarly, all can do 512 byte fragsize, only some can go below.
- Most testing has been in Linux so far; more testing needed in Windows and OSX.
- I didn't change anything in the code, so it's using the default filtering at the default level.  I'm waiting until the UI is implemented before changing/experimenting with those settings.

**Comment by sa666666** [comment] 2018-05-15 14:37
One final comment (for now) on the Linux issues.  I'm not convinced it is related to the code at all, and may be issues on my system.  I have two main systems, and both are quite top of the line.  And AMD 1800x system at home, and and Intel 8700K system at work.  On the AMD system, CPU usage is ~15% on one core.  On the Intel system, usage is 65-90% on one core.

Now I know the AMD system is faster in general, but it shouldn't be differing by _that_ much.  The Intel system is also the one that can't do 96000Hz, and has differences when using different CPU governors.  So for now, I take results from this system with a grain of salt; there is likely something else going on here.

**Comment by DirtyHairy** [comment] 2018-05-15 14:52
@sa666666 Agreed, The lookups should not happen. Could you also provide me some examples of those „wildly fluctuating scanlines“ ROMs? I already have some provisions for those in my scheduling code, so there may still be something wrong there.

**Comment by sa666666** [comment] 2018-05-15 15:05
Sound drops out, and "underrun" printed, on the following:
- Bachelor Party
- The Music Machine

Sound is quite different with AVCSTec Challenge, but I haven't yet confirmed that this is how real hardware sounds.  I have noticed with limited testing on real hardware that the new core is much more like the real thing, but also not as 'nice' as Stella 4.  Not surprising I guess, since much like the old TIA code, the emulation was _idealized_ and not reflecting the real thing.  Now that the sound core is more accurate, it really points out how primitive some of the original sound effects were.

I will get back to you later today about ROMs with irregular scanline count.

**Comment by sa666666** [comment] 2018-05-15 15:14
Overall, my testing seems to show that the sounds 'sound' right.  It's just that sometimes there are underruns, and at those times the sound drops out/clicks.  So I think the actual sound core and resampling are working, it's just that we need to keep the pipeline fed with data.

**Comment by DirtyHairy** [comment] 2018-05-15 15:25
I had suspected „A VCSTec challenge“, too (I noticed when playing in Stellerator, but didn‘t compare), and the Homestar Runner sounds very different (much dirtier), too. Both are Paul Slocum tracks, maybe he has a habit of taxing the TIA 😉

**Comment by sa666666** [comment] 2018-05-15 16:36
Just did some testing on a 4+ year old Haswell-based system (integrated video and audio), and the CPU usage is fairly low, with no dropouts, etc.  So it looks like there is an issue with my CoffeeLake system.  Arrgh, for once I'd like to be strictly a software developer and not always be _fixing_ computers.

**Comment by sa666666** [comment] 2018-05-15 18:20
All results are for Linux so far.  I will check my work computer (the problematic one) tomorrow.

When I get home this evening, I will post results on Windows and possibly OSX.

**Comment by sa666666** [comment] 2018-05-15 21:54
For Stargate (Defender II), hold down Reset (F2) and listen.  You can hear slight static in the playback.  Again, not sure if this isn't also on real hardware.  I don't have my console set up ATM, but I will test it again when I do.

**Comment by sa666666** [comment] 2018-05-15 21:58
For varying scanline counts, a good example would be Q-Bert, when you press Reset.  Note the count goes from 262 to 310, and values in between.  Many messages, both overflow and underrun, are printed to the console.

**Comment by sa666666** [comment] 2018-05-15 22:01
Regarding 96000Hz sampling, I wonder what is the benefit.  The samples are being generated at ~31400Hz, and 44100/48000 are standard sample rates.  So what is the benefit of oversampling in this case?

Since I really don't know much about sound programming, it could be that 96000Hz is beneficial.  Can you explain why it is??

**Comment by sa666666** [comment] 2018-05-15 22:15
Pick 'n' Pile has an inconsistent scanline count, which leads to inconsistent sound.  I'm not sure if this is a problem with the ROM itself or the TIA scanline emulation.  Since it's a PAL ROM, I can't test on a real console anyway.

[pickpile.zip](https://github.com/stella-emu/stella/files/2006920/pickpile.zip)

**Comment by sa666666** [comment] 2018-05-15 22:46
All ROMs tested in Linux from above sound the same in Windows at 48000/512 settings.  This leads me to believe that the sound core is behaving exactly the same in Linux and Windows (which is a good thing, obviously).

On a worse note (no pun intended), I just realized that my real console has a video mod and stereo sound, so I can't properly test for the normal, mixed-mono mode :(

**Comment by sa666666** [comment] 2018-05-15 22:49
Issue #104 (Vong demo) is now fixed with the latest sound core changes, so I closed the issue.

**Comment by DirtyHairy** [comment] 2018-05-16 08:06
@sa666666 concerning the usefulness (or uselessness 😉) of 96kHz, I‘ll try to explain what I know. However, I am no expert in signal processing either, so take this with a grain of salt.

Whenever you sample a signal with a sampling rate f, you can only capture frequency components of f/2 max. This is the Nyquist theorem, and higher frequency components lead to aliasing artifacts. As an extreme example, think about sampling a 44000Hz signal at 44100Hz: aliasing will give you an audible beating at 100Hz in the result, even if though the source signal was much higher (in fact inaudible). Therefore, it is vital to apply a lowpass filter to a signal before sampling it with a ADC, just as a DAC has to include lowpass filtering of the reconstructed signal.

When we resample the 33kHz output of the TIA, the same is happening: the square wave signal contains a lot of higher harmonics, and those above the Nyquist threshold of the sampling rate (i.e. 44100Hz) cause aliasing artifacts — this is the noise in Quadrun & Co. By applying the Lanczos filter, I reconstruct a signal from the TIA that is band limited at about 16kHz. This can then be safely sampled again with arbitrary sampling rates higher than the original 33kHz.

The Lanczos filter is not perfect, and there is a parameter a that controls computational complexity vs. frequency response. Higher a is slower and causes higher supression of the harmonics (but also washes out the edges in the signal). My choice for medium is a=2, high is a=3.

So, choosing 96kHz over 48kHz has a few implications:

1. Reproduces the higher harmonics more accurately and exhibits less aliasing (frequencies >48kHz are strongly suppressed already without filtering aka quality = low)
2. Allows for lower latency, as the OS latency is s/f where s is the sample size and is the sample rate

Point 1 is mostly irrelevant for Lanczos (medium & high). I think 96kHz is pretty much standard nowadays on most audio hardware, but I have no strong feelings about this; we can kick it if you like.

**Comment by DirtyHairy** [comment] 2018-05-16 08:43
Just did a quick check agains Pick'n'pile: disabling VSYNC helps a lot. The current code still has a slight coupling between framerate and scheduling (the emulation usually runs for a single frame, but there are pretty tight max and min cycle counts in place that kick in if the frame comes too early or too late), but this makes me suspect that most of the observed connection between frame rate and audio dropouts is due to video rendering.

Before doing more experiments on the scheduler, I'll move video rendering to a thread first; I think this will resolve most of the issues.

**Comment by thrust26** [comment] 2018-05-16 09:07
Shouldn't we allow even higher frequencies (whatever is supported by the hardware and libraries) if this makes signal processing better and also easier? If I get @DirtyHairy right, the Lanczos filter becomes less and less relevant, the higher the frequencies are, correct? Also what's the performance impact here?

**Comment by sa666666** [comment] 2018-05-16 10:49
OK, I see no reason to remove the higher sampling rates if there is a potential use for them.  I just didn't understand what the use-case was.

OK, first regression noticed:  AVCSTec Challenge.  The first few notes are 'tinny' or have less 'bass' than before.  I'm not sure what words to use to describe sounds, but the ROM on my real console sounds pretty much like the old sound core, and the new one seems to be a regression in this area.  I was _really_ hoping that this wouldn't happen, and that we could just do tuning on the new code.  Because TBH, I have no idea how to fix sounds that don't 'sound' right.

Regarding a ROM I mentioned that locked up the app, it was actually happening because of developer options that were enabled, and had nothing to do with the sound code.

**Comment by DirtyHairy** [comment] 2018-05-16 11:11
Fear not :) 639b6af1

I was just missing a reset call, so the initial state of the audio core was messed up.

**Comment by sa666666** [comment] 2018-05-16 11:30
Fear relieved :)  This fixes the AVCSTec ROM, and also other ROMs where there is slight 'garbage' at the start of emulation.

Only thing left now is again fine tuning, and fixing under-runs here and there.

**Comment by DirtyHairy** [comment] 2018-05-16 12:00
There is one thing left 😈  a few more seconds into the tune, there is *heavy* interference between the channels going on, and there Stella is still sounding off. However, Stellerator is right, so I am very confident that I will be able to nail the issue.

The other thing that currently gives me headache is whether I will be able to move rendering to a thread. I find no definite answer on the web whether I can render from a secondary thread; it *seems* like creating the renderer there, too, should do the trick, but who knows... If this doesn't work, the only way to pull this off to keep video and event handling on the main thread and move emulation into a secondary thread, but that's a long stony road that I don't want to go. The lower hanging fruits probably are

* changing TIASurface->render to redraw only if an actual surface has been issued (that will put the wonky-scanline-count ROMs on equal footing with their well-behaved brethren)
* Emulate the timeslice on a separate thread and bit the last frame to the screen at the same time

I've currently no idea what I'm gonna try first though :smirk:

**Comment by sa666666** [comment] 2018-05-16 12:20
Hmm, I leave it to your discretion, but I really hoped that such a large refactoring wouldn't be required.

Regarding rendering in a separate thread, from what I've read on the SDL mailing list, it seems that most systems _can_ do it, but a few can't, and in creating the library they had to account for _all_ systems.  So they chose the lowest common denominator.  I don't know what that means for us, and if trying to work around the SDL way of doing things will break, or if it will affect the major platforms we support (Linux, OSX, Windows).

In any event, more testing is definitely required.  We need to get this spread to more end-users, since we have very few test-cases ATM.

**Comment by DirtyHairy** [comment] 2018-05-16 13:04
I agree, I don't want or intent to start this kind of refactoring either. My current plan is:

* Redender only if a new frame is available; see whether this is sufficient
* If not, emulate while rendering; hope that this is sufficient
* Look into the VCSTec issue
* Tie up the UI

Then we should go for a public test.

**Comment by DirtyHairy** [comment] 2018-05-17 08:12
OK, I think we can tick off the VCSTec issue. I don't know exactly what is going on, but the exact sound depends on the initial state. If I turn on randomization, then I can get both the "thin" and "thick" versions of the questionable notes on different resets.

I have given up identifying the exact piece of randomness (the effect is very random, and I am starting to get sick of the otherwise pretty cool tune 😈), but I guess this influences the cycle in which the first writes to the audio registers happen, and this influences the precise phase of the signal. Sometimes it cancels at times, sometimes it doesn't --- similar to the well-known random disappearance of notes in the PAL Ms. Pac-Man tune that @ale-79 analyzed.

**Comment by thrust26** [comment] 2018-05-17 08:32
You are refering to this topic, correct?
http://atariage.com/forums/topic/274863-ms-pac-man-pal-sound-issue/

**Comment by DirtyHairy** [comment] 2018-05-17 09:11
Exactly 😀

**Comment by thrust26** [comment] 2018-08-02 21:05
@DirtyHairy Where are we with this issue? Can we close it?

**Comment by DirtyHairy** [comment] 2018-08-02 22:28
Let's wait until the final release.

**Comment by sa666666** [comment] 2019-08-17 15:28
I guess since Stella 6 has been out for over 6 months now, the new sound code has received a lot of testing.  At least there have not been many (any?) reports of regression.  So @DirtyHairy, I guess we can close this one?

**Comment by DirtyHairy** [comment] 2019-08-17 20:05
Indeed 😏

**Closed by DirtyHairy** 2019-08-17 20:05 UTC
Labels: regression test
