### ISSUE TITLE
macOS: Stella does not always start binary when launching

### ISSUE THREAD

**Issue by ayarusso** [stella-emu/stella#497] opened 2019-06-25 19:02 UTC
When I want to test a 2600 binary in Stella (which is quite often!) I copy it into my stella/ROM folder and then double-click the binary to open it.  I have .bin files associated with Stella, so Stella launches, but most of the time (I'd say at least 80%), the game does not start up.  I then have to find the binary I want to run in the long list of binaries I have in that directory. 

Would love to see this work 100% of the time.  :)

Currently using High Sierra on most of my machines, but OS version doesn't seem to matter with this one, as I've seen this issue for some time now.

**Comment by thrust26** [comment] 2019-08-13 15:43
@DirtyHairy Since you are our "Mac-Man", can you reproduce this behavior?

**Comment by sa666666** [comment] 2019-08-13 15:45
I also have a Mac (two now; a Hackintosh at home and an authentic Mac at work).  Unfortunately what I don't have so far is time to actually test it.

**Comment by DirtyHairy** [comment] 2019-08-14 20:04
I can reproduce this. For me, it happens reliably with certain ROMs, although I can't see any pattern. I'll try to get this fixed.

**Comment by DirtyHairy** [comment] 2019-08-17 21:50
Fixed by 712cfbaeb. This does away with a whole bunch of code in `SDLMain.m` that --- to the best of my knowledge --- should be useless. We should be especially careful to watch out for regressions when 6.1 is released.

**Closed by DirtyHairy** 2019-08-17 21:50 UTC
Labels: bug, target 6.1
