### ISSUE TITLE
BRK and display...

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#651] opened 2020-06-03 15:08 UTC
When stella hits a BRK instruction, it continues to display the last (perfectly formed) frame.
I would expect a black screen, or at the very least some sort of minimal TIA output.

**Comment by thrust26** [comment] 2020-06-03 15:16
Stella displays the previous screen until a new display starts. Why should the screen be black?

**Comment by andrew-davie** [comment] 2020-06-03 15:19
Because, and you guys work so hard on this, Stella shows what a TV shows.
TVs do not, generally, show the previous screen.

**Comment by thrust26** [comment] 2020-06-03 15:33
This is the debugger, not the emulator. Here function is important, not perfection. :smile:

**Comment by andrew-davie** [comment] 2020-06-03 15:40
The emulator does the same thing.

**Comment by thrust26** [comment] 2020-06-03 15:40
Huh? You can't see the emulator while in debugger mode.

**Comment by andrew-davie** [comment] 2020-06-03 15:43
For me, at least, it is **not** in debugger mode. I have a fully formed display, and nothing happening. I wondered what was happening, and stella is continually executing the same BRK instruction. I was pointing out that this is not what i would expect to see (in the emulator).

**Comment by thrust26** [comment] 2020-06-03 15:46
Sorry, my fault. I misinterpreted `BRK` with `break`

But again, why should Stella display an empty screen in this case? Stella simply executes the code where the break vector points to.

**Comment by andrew-davie** [comment] 2020-06-03 15:49
Because a TV would not display the last frame.
And furthermore, because as a developer I would like/expect to see what the Atari/TV would actually do. I sat there for 30 seconds watching a seemingly-normal display when in fact the program had crashed and was executing BRK endlessly.
It's not proper emulation if, on executing BRK, you have the last frame displayed.
I don't really care about this. Just reporting it because I think it's wrong.
Very marginal case, though.

**Comment by thrust26** [comment] 2020-06-03 15:53
OK, if there is an endless loop (BRK or whatever), then you are correct. Then Stella should stop displaying a complete display. Instead it should continue to display the last line.

**Comment by andrew-davie** [comment] 2020-06-03 15:56
Yes, I have an endless BRK loop happening. That's what I was trying to point out - stella should be displaying a minimal TIA output (single scanline).

**Comment by thrust26** [comment] 2020-07-04 07:58
@andrew-davie Can you provide an example code here, please? I cannot reproduce the problem, I am getting an all blank screen when I am doing this (with various TIA registers != 0):
```
Break
    brk
    ...
    ORG     $fffc
    .word   Start
    .word   Break
```

**Comment by andrew-davie** [comment] 2020-07-04 09:07
Here you go.
It will draw 63 squares of a chessboard, then hit a break.
You can single-step and see it on the break for every instruction, but we have a full screen being displayed by stella.
It looks like it's a valid frame being displayed, but it's not.

[chessBreaker.bin.zip](https://github.com/stella-emu/stella/files/4872343/chessBreaker.bin.zip)

**Comment by thrust26** [comment] 2020-07-04 10:24
Hm, might be OS related. On my Windows notebook, the screen becomes black.

Can someone else confirm what Andrew is reporting?

**Comment by andrew-davie** [comment] 2020-07-04 10:45
Screen recording showing what I see...

[chessBreaker.mp4.zip](https://github.com/stella-emu/stella/files/4872634/chessBreaker.mp4.zip)

**Comment by thrust26** [comment] 2020-07-04 18:33
Looks the same for me, except for the black screen.

**Comment by DirtyHairy** [comment] 2020-07-08 18:58
I cannot reproduce this on my Macbook either, I get a black screen.

**Comment by sa666666** [comment] 2020-07-08 19:14
Also cannot reproduce in Linux.

**Comment by thrust26** [comment] 2020-07-08 19:55
Hm... I suppose we should close this. Unless Andrew wants to fix it himself.

**Comment by thrust26** [comment] 2020-07-21 14:16
@andrew-davie?

**Comment by andrew-davie** [comment] 2020-07-21 14:29
I do not have the skills to fix, alas.

But as it is only me experiencing the issue, and it's a real marginal case anyway, it can probably be ignored without anyone caring. I just reported it out of a feeling of "correctness". I don't mind if it's left as is.

So, I have no objections to issue being closed.  But the "bug" is still there ;)

**Closed** 2020-07-21 14:35 UTC
Labels: needs research, wontfix
