### ISSUE TITLE
Add file save dialogs in the debugger  (and elsewhere)

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#172] opened 2017-07-09 21:34 UTC
Currently, whenever something is saved from the command prompt in the debugger, a default name/location is used, or you're forced to type the full path to save the file.  It would be better to use a dialog box to do this.  The beginnings of this are already in BrowserDialog, but it needs to be expanded upon.

**Comment by thrust26** [comment] 2020-08-06 18:14
@sa666666 How should we trigger the dialog box? 
- new commands (save/saveas, savesnap/savesnapas ...)
- optional extra parameter, e.g. '?' (save ?, savesnap 0 ? ...)

I am for the latter, as it doesn't create many more extra commands.

**Comment by thrust26** [comment] 2020-08-09 06:59
@sa666666 I working on this now. Problem is, that the `BrowserDialog` shows no directories even though `FilesystemNode::ListMode::All` gets selected. 

In `BrowserDialog::show(...)`, `case FileSave:` I have replaced
```
      _fileList->setNameFilter([&ext](const FilesystemNode& node) {
        return BSPF::endsWithIgnoreCase(node.getName(), ext);
      });
```
with
```
      _fileList->setNameFilter([](const FilesystemNode&) { return true; });
```
For whatever reason `ext` is filled with the current directory name in case of a directory. No clue why. Maybe you can have a look?

**Comment by sa666666** [comment] 2020-08-09 14:33
Yep, a case of premature optimization.  The lambda should keep what the string was when invoked, not what it might become in the future.  I already fixed another instance related to this this; guess I missed this one.

**Comment by sa666666** [comment] 2020-08-09 15:12
> @sa666666 How should we trigger the dialog box?

I don't think we need separate commands.  When the user types 'savexxx', simply pop up the save dialog with the name already present in it.  If they choose that name (which most people will by default), then simply pressing Return will initiate the save.  Or they can change the name within the save dialog UI and then save it.

So there's no need to modify commands to take extra parameters.  In fact we should do the opposite.  Commands that currently take the filename as a parameter should be modified so that they don't take that parameter anymore.  Move the selection/entering of the filename into the save dialog, where it belongs.

**Comment by thrust26** [comment] 2020-08-09 15:32
Hm, I frequently use the history of the prompt directly or slightly modified. Enforcing an UI interaction slows things down a bit.

**Comment by sa666666** [comment] 2020-08-09 15:45
Properly implemented, it would mean only one extra keypress (Return).  Press Return once on the command, and then after the UI pops up, press Return again.

Although I suppose you can also have the commandline process it, like now.  But then you need to look at the parameters given, and only show the UI sometimes.  And then also, you'd need to validate the path given (which isn't really being done at all now).

I really have no preference.  I was merely talking about what's quicker to code.  So there could be two versions: one that recognizes the path has been provided, and just uses it (without UI).  And another where you if you don't specify the path, then it pops up the UI, and preferably has a default value already there for the user to accept.

**Comment by thrust26** [comment] 2020-08-09 15:47
That was my idea #2 from above.

**Comment by sa666666** [comment] 2020-08-09 15:48
I guess it really comes down to whether we always show the UI or not.  We don't have to get rid of allowing the user to enter the path on the commandline; it can simply be used as the (default) path in the UI.  So you can still make minor changes on the commandline, and have the UI work with it.  But it _will_ force the user to press Return twice.

**Comment by thrust26** [comment] 2020-08-09 15:50
The (e.g.)? would be a parameter. Instead of e.g. `save`, you type `save ?`.

**Comment by thrust26** [comment] 2020-08-09 16:00
I have the basics working, though much work is still required,

One problem I am facing are multiple parameters. Currently the filename parameter is transferred via `BrowserDialog`, which sends a command on OK. And the command code then reads the selected file filename (incl. path). But additional parameters cannot currently be transferred that way. And I have no idea how to transfer them elegantly.

**Comment by sa666666** [comment] 2020-08-09 16:12
> nother thing: If the user selected a different directory in the process, then we should remember that directory and not make the user navigate over and over again. So we need more settings. Agreed?

That part could be added as an instance variable of `BrowserDialog`, since it's really the job of the save dialog to remember where it was before.  Of course that would mean the dialog needs to not be destroyed and re-created each time you need it.  And do you want that 'last path' to persist across program runs, or only within a single run?   If the former, then we need to save it to settings.

> But additional parameters (e.g. required for `savestate`) cannot currently be transferred that way. And I have no idea how to transfer them elegantly.

I thought that we'd be using the save dialog only for things that take a string (aka, a filename).  I'm not sure how it should work when you have multiple parameters.  Also, I haven't thought that far ahead on this stuff; that's why the issue is still open :smiling_imp: Maybe `BrowserDialog` needs to be extended/redesigned for this too.

**Comment by thrust26** [comment] 2020-08-09 16:16
> If the former, then we need to save it to settings.

IMO only this makes really sense.

> Maybe BrowserDialog needs to be extended/redesigned for this too.

As of now `savestate` seems to be the only command which needs additional parameters. So for now this has no high priority.

**Comment by thrust26** [comment] 2020-12-22 08:55
I have analyzed the various "save" operations in Stella and they are quite mixed up. Each one has of course its own suffix, but the save paths and names vary a lot too:

Command | Class | Path | Name | Suffix | Notes
-- | -- | -- | -- | -- | --
script | DebuggerParser | defaultSaveDir | „commands“ | script | defaultSaveDir expected by „exec“ command
access | CartDebug | defaultSaveDir | PropType::Cart_Name | csv |  
config | CartDebug | cfgDir | OSystem.romFile() | cfg | File is loaded by debugger at startup and by user command
disassembly | CartDebug | defaultSaveDir | PropType::Cart_Name | asm |  
rom | CartDebug | defaultSaveDir | PropType::Cart_Name | a26 |  
session | PromptWidget | defaultSaveDir | „session“ + timestamp | txt |  
snapshot | TiaOutputWidget | snapshotSaveDir | PropType::Cart_Name | png |  
state | Debugger | stateDir | PropType::Cart_Name | sta |  
allstates | Debugger | stateDir | PropType::Cart_Name | st? |  
dump | DebuggerParser | defaultSaveDir | PropType::Cart_Name + „_dbg_“ | dump |  
  |   |   |   |   |  
saveprops | GameInfoDialog | defaultSaveDir | OSystem.romFile() | pro |  

With the following defined paths:
Pathname | Path
-- | --
defaultSaveDir | Desktop
baseDir | ~/Stella
cfgDir | baseDir + „cfg“
stateDir | baseDir + „state“
snapshotSaveDir | defaultSaveDir \| settings("snapsavedir")

So we have a great variety of paths, some are fixed, some depend on the OS, some are user defined. This leads to the following problems if we provide a optional file dialog. If the user decides for a different path, name and suffix:
1. How does this affect other commands using the same path? E.g. if the user saves a ROM in a different path than `defaultSaveDir`, should the path be remembered for the next save?
2. If yes, should this change `defaultSaveDir` for all commands using this path or should each command use an individual path?
3. If the changed path(s) are remembered, only for the current session or persisted in the settings?
4. Is the user even allowed to change path, name or suffix? In some cases this may result into loading problems.
5. ... (I am sure there is more)

So before I continue implementing the file dialogs, we have to analyze and decide case by case if a dialog is required, what can be defined by the user (path, name, suffix?) and how these definitions are remembered.

**Comment by sa666666** [comment] 2020-12-22 13:12
I agree the entire thing is a mess.  We need some sanity here, since it's all over the place.

**Comment by thrust26** [comment] 2020-12-22 17:48
Yes, we have to come up with some systematic. Even I often do not know where a file is saved.

At first glance `defaultSaveDir` + `PropType::Cart_Name` seems to be the most common denominator. But maybe we should classify first:
1. user files, the user needs to know where they are and might want to define path and name
    - for emulator (snapshots, exported props),
    - for debugger (ROM, disassembly, access, dump)
2. Stella files (also loaded by Stella), user should not define where they are
    - for emulator (props, states, also e.g. palettes, nvram and ini), 
    - for debugger (config, script, session)
    
I would suggest the following: 
- we allow two common paths for user files (emulator and debugger file paths). All have a default path (initially both = defaultSaveDir), name (based on PropType::Cart_Name) and suffix (based on file type). But the user can define path, name and suffix. 
- the Stella files go into baseDir or sub-directories of it. The whole path is defined by Stella.

This should work for all saves (and loads) listed above. Except for 'script' which can have a user-defined path **and** is loaded by Stella. No clue how this even works now.

**Comment by thrust26** [comment] 2020-12-23 08:59
BTW: To make things even more complicated, we have the options 'basedir' and 'baseinappdir' (Windows only) which change `defaultSaveDir` too. 

And then we have a `defaultLoadDir` which seems to be always(!) identical with `defaultSaveDir`. Huh? Why woulkd separate directories even make sense?

**Comment by thrust26** [comment] 2020-12-25 10:27
This is done now, except for "dump". The problem is that the browser dialog is called asynchronously, so you are loosing all context when you process the results. One could transport the context through the browser dialog etc., but this would be only a hack. Maybe the browser dialog should be handled different from all other dialogs?

@sa666666 Or do you have a good idea?

**Comment by sa666666** [comment] 2020-12-25 13:13
Maybe we need to pass in a lambda containing the code to execute on a save, rather than sending a command back when the the save button is clicked.  That way the save is asynchronous, but the context is not lost (since it's part of the lambda).

**Comment by sa666666** [comment] 2020-12-25 13:29
I suppose passing in a lambda could be seen as 'transporting the context', but I don't see it as a hack.  You're simply telling the dialog what to do when the user confirms an action.  In fact, I would have originally designed it that way, but lambda's didn't exist in C++ when `BrowserDialog` was first written :smile: 

Now that we have this functionality, there's probably some more commands in the debugger that can take advantage of it.  The 'Save log to disk' button in "System Logs" is a good candidate too.

**Comment by thrust26** [comment] 2020-12-25 13:55
I am not too firm with lambdas. After the coming release, maybe you can have a look at the "dump" command?

I will check the 'System logs' now.

**Comment by sa666666** [comment] 2020-12-25 14:27
Conceptually the idea of the lambda is pretty straightforward.  Right now, we give the dialog an integer 'command', and when a button is pressed, it sends that command back to the callee, which then reacts to it.

With a lambda, instead of giving the integer command, we give the _actual block of code we want executed_ when the button is clicked.  So there is no communication directly back to the callee; it is all done through the lambda.  Of course, if we still want something to happen in the callee, that will be done in the lambda too.  Point being, we don't need a separate `handleCommand` in the callee to handle the returned integer command, since there won't be one.

**Comment by sa666666** [comment] 2020-12-25 14:29
If you're familiar with Java, it's essentially providing an `ActionListener` to the dialog.

**Comment by thrust26** [comment] 2020-12-25 16:14
@sa666666 
Instead of coding the same code multiple times, I would like to provide global `BrowserDialog` object, which can be modified using a global method. I am not sure if and how this be can done within our current framework.

**Comment by sa666666** [comment] 2020-12-25 16:20
I guess you mean you want to make it `static`, so there's only one instance in the entire program?  I suppose that's possible, but I don't see how much duplicate code it will eliminate.  You will still have to change its title, give it a lambda specific to the context of how it's being used, etc.  After that, how much other code is duplicated?

Perhaps you can point me to places in the current code that you feel are needlessly being duplicated?

**Comment by thrust26** [comment] 2020-12-25 16:29
Why should we create the same object over and over again? This is something I find irritating about other dialogs too. E.g. we create the `OptionsDialog` (and all sub dialogs) three times.

For the `BrowserDialog` the code in `createBrowser` is required almost always.

**Comment by sa666666** [comment] 2020-12-25 16:40
OK, I see what you mean.  If we go that route, then we can have only one.  There are issues with the 'owner' of the pointer of the dialog.  We can't share that pointer with all other dialogs, since the UI code auto-deletes the pointer eventually.  And trying to delete an already deleted pointer leads to a crash.  So we would need to create _one_ instance, and not have it owned by _any_ dialog.  That's easy enough to do.  I can look into it if you like.

Regarding this happening in other parts of the code, unfortunately it is part of the design.  The code is old, and based on what could be done in C++ back then.  If I were designing it now, I'd use `shared_ptr<Widget*>` everywhere, and let dialogs clean up themselves when no longer needed.  I tried once to convert the current code to that, but after making 1000's of changes and it still had bugs, I gave up.  It's a limitation we may have to deal with.

But the `BrowserDialog` is a special case, and can probably be made to work like we would want.

**Comment by sa666666** [comment] 2020-12-25 16:56
I think the best I can do is have _one_ `BrowserDialog` be owned by `OSystem`, and you can activate it with `instance().showFileBrowser(...)`, where the `...` takes the title and the other parameters you would pass to `BrowserDialog::show`.  The common code from the various `createBrowser` classes could then be folded into its creation, and would only be done once.

However, if we do that, then we _have_ to move to lambdas of some kind.  Right now, the 'owner' that creates the `BrowserDialog` is the one that receives responses from it.  If we change it so that `BrowserDialog` doesn't have an owner, then it can't pass any info back.  So we need to pass in all info it needs to function; aka, we need a lambda.

**Comment by thrust26** [comment] 2020-12-25 16:59
I will leave that up to you. And then try to understand. :smile:

**Comment by sa666666** [comment] 2020-12-25 16:59
Alternatively, we have to pass the `this` pointer from the dialog that wants to present the browser.  The `this` parameter then becomes the `CommandReceiver` that receives the info back from the dialog.

**Comment by sa666666** [comment] 2020-12-25 17:09
> I will leave that up to you. And then try to understand.

So are you asking me to work on this next?  Or to push it until after 6.5?

**Comment by thrust26** [comment] 2020-12-25 17:12
Up to you.

**Comment by sa666666** [comment] 2020-12-25 17:13
I can try for the upcoming release.  But later this evening or tomorrow; I want to take at least some of today off.

**Comment by sa666666** [comment] 2020-12-26 21:57
OK, some progress.  The following example is for `LoggerDialog`, since it's the simplest example I could find.  The current code is this:
```
    case GuiObject::kDefaultsCmd:
      // This dialog is resizable under certain conditions, so we need
      // to re-create it as necessary
      createBrowser("Save Log as");

      myBrowser->show(instance().userDir().getPath() + "stella.log",
                      BrowserDialog::FileSave, kSaveCmd);
      break;

    case kSaveCmd:
      saveLogFile();
      break;
```
Note how `kSaveCmd` had to be passed into the `show` method, and then passed back when 'OK' was clicked?  This is the new code:
```
    case GuiObject::kDefaultsCmd:
      // This dialog is resizable under certain conditions, so we need
      // to re-create it as necessary
      createBrowser("Save Log as");

      myBrowser->show(instance().userDir().getPath() + "stella.log",
                      BrowserDialog::FileSave,
                      [this](bool OK, const FilesystemNode& node) {
                        if(OK) saveLogFile(node);
                      });
      break;
```
With this new version, the browser calls the lambda when a button is pressed.  If OK is clicked, then the first parameter is set to true, otherwise it's set to false.  The second parameter is the node selected at that time.  So this is generic.  The calling code is simply informed whether OK was clicked or not, and what the node was at that point.  It's then free to act on that info in whatever way it wants.  This keeps the context in one place.  And there are no int commands being sent and received.

Next I will integrate the creation of the browser object into a common class, so that each class that wants to use it doesn't need to duplicate code.  In the end, if it all works out, I envision simply being able to call `instance().showBrowserDialog(...)`, and everything else is automatic.

**Comment by thrust26** [comment] 2020-12-26 22:41
This looks cool. :+1: (though I still have problems to understand the syntax of lambdas, just too many different brackets :smile:)

When you create a common object, please make sure that it can be resized based on its parent dialog's size.

**Comment by sa666666** [comment] 2020-12-26 22:54
OK, one major problem that I'd hoped to avoid, but can't really do it with the current design.  I think we need to change to always creating a new object, vs. caching it.  So every time a browser is to be shown, a new object is created.  This is unfortunately because the UI code isn't resize-able, sometimes takes different fonts, sometimes has different bounds, etc.

But at least it will only happen in one place, instead of inside every class that makes use of a browser.  Maybe in the future we can extend the UI code to be resize-able, but we've discussed that before, and it's a _major_ undertaking.

**Comment by sa666666** [comment] 2020-12-26 22:59
Also, a dialog has to have some `DialogContainer` has its parent, and depending on the mode in which it's created, that parent will be different.  So there's no current way to have one static `BrowserDialog` usable in all cases.  But at least we can have just one method to call to create and show one when we want.

**Comment by thrust26** [comment] 2020-12-26 23:00
Fine by me, recreating the object was what I had expected anyway.

If we should ever go to resizing and stuff, this would require quite a lot of dialog redesign.

**Comment by sa666666** [comment] 2020-12-26 23:31
OK, this is as clean as I can make it, within the limitations of the current UI code:
```
    case GuiObject::kDefaultsCmd:
      BrowserDialog::show(this, _font, "Save Log as",
                          instance().userDir().getPath() + "stella.log",
                          BrowserDialog::FileSave,
                          [this](bool OK, const FilesystemNode& node) {
                            if(OK) saveLogFile(node);
                          });
      break;
```
And this is the static method signature in `BrowserDialog`:
```
    /**
      Place the browser window onscreen, using the given attributes.

      @param parent     The parent dialog of the browser (cannot be nullptr)
      @param font       The font to use in the browser
      @param title      The title of the browser window
      @param startpath  The initial path to select in the browser
      @param mode       The functionality to use (load/save/display)
      @param command    The command to run when 'OK' or 'Cancel' is clicked
      @param ext        For file modes, show only files with this extension
    */
    static void show(Dialog* parent, const GUI::Font& font,
                     const string& title, const string& startpath,
                     BrowserDialog::ListMode mode,
                     const Command& command, const string& ext = "");

```

**Comment by thrust26** [comment] 2020-12-26 23:45
It would become a little shorter if the `Dialog` would allow access to its `_font`.

**Comment by sa666666** [comment] 2020-12-26 23:53
The problem is that after I ran a search of how `createBrowser` is currently being used, it doesn't always use the dialog font.
```
src/gui/SnapshotDialog.cxx
192:    myBrowser = make_unique<BrowserDialog>(this, myFont, w, h, title);

src/gui/GameInfoDialog.cxx
680:    myBrowser = make_unique<BrowserDialog>(this, _font, w, h, title);

src/gui/UIDialog.cxx
715:    myBrowser = make_unique<BrowserDialog>(this, myFont, w, h, title);

src/gui/RomAuditDialog.cxx
232:    myBrowser = make_unique<BrowserDialog>(this, myFont, w, h, title);

src/gui/BrowserDialog.cxx
233:      make_unique<BrowserDialog>(parent, font, w, h, "PLACEHOLDER");
252:      make_unique<BrowserDialog>(parent, font, w, h, "PLACEHOLDER");

src/debugger/gui/DebuggerDialog.cxx
498:    myBrowser = make_unique<BrowserDialog>(this, instance().frameBuffer().font(), w, h, title);
```
So I have to use a parameter.  Maybe later we can clean that up too.

**Comment by sa666666** [comment] 2020-12-26 23:55
I'm also going to change the `ext` parameter to instead accept a `FilesystemNode::NameFilter` lambda (optionally).  Because displaying files by specific extension isn't the only way we may want to filter the names; there are many other possibilities.

**Comment by thrust26** [comment] 2020-12-26 23:59
Isn't the `BrowserDialog` using always the same font?

**Comment by sa666666** [comment] 2020-12-27 00:10
Not according to the above code, where a `BrowserDialog` is created with potentially at least give different fonts.

For now I will leave the parameter there.  Once we clean up later, we may be able to remove it again.

**Comment by thrust26** [comment] 2020-12-27 00:23
Yes, I can trace back the fonts then.

**Comment by sa666666** [comment] 2020-12-27 03:13
OK, I've finished this, and converted all uses of `BrowserDialog` to the new scheme.  Tomorrow I will test in Windows and Mac, but I don't foresee any problems; it's pretty standard code.

**Comment by thrust26** [comment] 2020-12-27 08:23
> Yes, I can trace back the fonts then.

The fonts are always identical (`OSystem.framebuffer().font()`). Which is no surprise, because all dialogs should use the same font.

**Comment by sa666666** [comment] 2020-12-27 14:57
Hmm, then I don't know why some dialogs are holding a reference to a font, and some aren't.  Maybe more cleanup work to do there ...

**Comment by sa666666** [comment] 2020-12-27 16:16
OK, just added the changes in https://github.com/stella-emu/stella/commit/3edc5aafe86fe8321e5dccb68d9722bf3293eb7b.  Once you're confident of how it works, I guess we can get this added to the changelog, and close this issue.

**Comment by thrust26** [comment] 2020-12-27 17:57
> Hmm, then I don't know why some dialogs are holding a reference to a font, and some aren't. Maybe more cleanup work to do there ...

Yup.

**Comment by sa666666** [comment] 2020-12-27 20:07
Only took 3.5 years to implement :smiley:

**Comment by thrust26** [comment] 2020-12-27 21:24
True.

Nevertheless, I think I will inline the `BrowserDialog` in the `DebuggerParser` too. 

So we are only almost done. 😈

**Comment by thrust26** [comment] 2020-12-28 11:44
**Now** I am done. :smile: 

@sa666666 Please have a look, especially at `executeDump`. There is some ugly code, because I wasn't able to correctly use stringstreams in the capture without converting to and from strings.

**Comment by sa666666** [comment] 2020-12-28 15:51
There were a bunch of places with duplicate declarations of `dlg`.  But these could simply be passed into the lambda capture, so that was pretty easy to fix.

The stringstream and capture issue is more complicated.  `commandResult` didn't need to be passed in at all, since it's part of the class being referenced by `this`.  So we have direct access to it.

The `out` variable is more complicated.  This one is a local variable, and it will no longer exist when the lambda is actually called.  So we need to capture it.  Problem is, we can't capture by reference, since it will then become a null reference (and crash Stella).  But we also can't capture by copy, since `ostringstream` doesn't seem to allow that.  I am researching this right now.

The reason your code worked is that you captured strings by copy, and at that point it didn't matter if the `out` variable went out of scope.

**Comment by thrust26** [comment] 2020-12-28 16:19
Good catch with the `dlg` ( I am still learning...)

`commandResult` is cleared when the browser dialog is used, because else you get the resulting output before saving (or aborting). Also it is filled with a special string to indicated that the `PromptWidget` must not print a prompt. So we cannot use is and have to capture by value (which doesn't work).

**Comment by sa666666** [comment] 2020-12-28 16:26
Actually, I am working on this now, so I may have to revert some of the last commit.  It's not good form to capture everything; only what you need.  So the various captures should be `[this, dlg]`, not `[=]`.  You'll see what I mean when I do the next commit.

**Comment by thrust26** [comment] 2020-12-28 16:26
Why not use ` [=]`. AFAIK this doesn't catch everything, but only everything you need.

**Comment by thrust26** [comment] 2021-01-04 20:36
Sorry, I have to reopen this.

The `BrowserDialog` doesn't resize. If you open it first on a large surface, it won't open on a smaller one.

**Comment by thrust26** [comment] 2021-01-05 15:13
I think with 3a1df0e9 (merge pending) we can close this one now.

**Closed by thrust26** 2021-01-05 15:13 UTC
Labels: debugger, enhancement
