### ISSUE TITLE
"Wal-Rush" 2 pushed off screen

### ISSUE THREAD

**Issue by kdgarris** [stella-emu/stella#375] opened 2018-09-05 20:40 UTC
The "Wal-Rush 2" homebrew game has the score pushed off the screen.  I'm attaching the rom as well as screenshots for the game running on hardware vs on Stella 6.0 pre1.

<img width="688" alt="screen shot 2018-09-05 at 3 05 13 pm" src="https://user-images.githubusercontent.com/4992162/45119523-af711780-b129-11e8-9d21-77221f87da97.png">

![40847059_719207758418016_8352039415786242048_n](https://user-images.githubusercontent.com/4992162/45119729-39b97b80-b12a-11e8-83c8-6554e2fd5ae9.jpg)

[WalRush2.zip](https://github.com/stella-emu/stella/files/2354501/WalRush2.zip)

**Comment by thrust26** [comment] 2018-09-05 20:43
That's because the screen centering code does not now about the white space not being used. Your whole screen is too much down as you can see on your TV too. Either fix that or go into Stella's game properties and adjust Y-Start.

**Comment by sa666666** [comment] 2018-09-05 20:45
This might be fixed in a different way after the 6.0 release, when the window size will become ~230 lines high.  I just wanted it documented here so that we can use it as a test case, and to make sure this isn't a bug in the ystart autodetection code.

**Comment by thrust26** [comment] 2018-09-05 20:49
The problem is, that VBLANK is disabled right after VSYNC and the background is white already. So there are no black unused areas to detect. Maybe we could fix this by allowing all colors there. But then in this case it would probably end to much upwards. 

Anyway, IMO we should remove that auto-centering completely as it doesn't exist on a normal TV too. Games have to be centered correctly.  And yes, the 230 lines thing will help here too.

**Comment by kdgarris** [comment] 2018-09-05 21:07
It's not my game, but I reported it in case it would be helpful to do so.  I linked to the report in the game topic for the developer to see.  The early disabling of VBLANK is strange, though, since I didn't think batari Basic games did that.

**Comment by DirtyHairy** [comment] 2018-09-05 21:11
Yeah, this is one of those cases where autodetect in its current form cannot work reliably. I think the best way to proceed is to just record a fixed ystart value in the ROM properties.

**Comment by thrust26** [comment] 2018-09-07 16:30
> This might be fixed in a different way after the 6.0 release, when the window size will become ~230 lines high.

That's #368, just for reference.

**Comment by sa666666** [comment] 2019-12-19 19:56
With the recent removal of ystart autodetection, this ROM now displays correctly.

**Closed by sa666666** 2019-12-19 19:56 UTC
Labels: enhancement, target 6.1
