### ISSUE TITLE
MacOS - opening from finder doesn't work

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#534] opened 2019-09-04 12:48 UTC
Under MacOS, if I right-click on a ".bin" file and choose "open with Stella", it does run stella, but stella simply presents me a directory from where I need to navigate to the file and choose it again. It seems that stella is not detecting that it has been asked to open a specific file.

**Comment by thrust26** [comment] 2019-09-04 12:54
Could this be related to #497?

**Comment by andrew-davie** [comment] 2019-09-04 13:01
I should note that I was testing the release version, not the current beta - which I only have as a binary, not bundled as an App which the system will use/recognise for "open with...".  It's possible that this has been fixed by the referenced issue above

**Comment by DirtyHairy** [comment] 2019-09-04 13:51
I am pretty sure that this is a duplicate of #497. I'll close it, but please reopen if you manage to reproduce this with the current version of Stella.

**Closed** 2019-09-04 13:51 UTC
Labels: bug

**Comment by andrew-davie** [comment] 2019-09-04 13:56
I suspect so, too. Unfortunately I can't build a system-recognisable App to test with at the moment -- the XCODE build appears to be broken (#535). When I find out, I will report back if it is not resolved.
