### ISSUE TITLE
500K cycles for ARM not enough

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#1033] opened 2024-06-02 13:36 UTC
I have a binary that works on hardware (and Gopher) but bombs out in Stella with the 500K cycle timeout, as shown.
Essentially, I'm pretty sure the 500K is just too small a limit and all that needs fixing is an adjustment to this.

<img width="700" alt="Screenshot 2024-06-02 at 11 31 52 pm" src="https://github.com/stella-emu/stella/assets/16424075/93217c4c-5ea8-41d7-9ba6-1443121ad36a">

I have my 6507 code EA-timeout starting early, about $700D and I am (deliberately) holding the ARM from returning until the absolute last moment possible (I have an empty while-loop doing this, based on calculated cycles). The crux of this is that the code works fine on hardware, not on Stella.

I am happy to share a confidential binary, or test a bug-fix version of Stella.

**Comment by thrust26** [comment] 2024-06-02 14:35
What limit would we need here?

**Comment by andrew-davie** [comment] 2024-06-02 14:47
> What limit would we need here?

I truly don't know because 500K makes NO sense to me. I do however have some example ARM-cycle calculations that might help. In my 'crash Stella' binary I use the full-ARM cycles in my ARM code.


; timer values
VB_TIM64T = 43
OS_TIM64T = 29


VB = 43 x 64 cycles
   = 2752 cycles
   = 2752 / 76 scanlines
   = 36 scanlines


VB spends about 10 scanlines doing vsync, sprite positioning, etc.
Leaving ~26 scanlines for ARM


OS = 29 * 64 cycles
   = 1856 cycles
   = 1856 / 76 scanlines
   = 24 scanlines

Assume ~3 for 6502 overhead
Leaving ~20 scanlines for ARM




@70MHz, each scanline (262 lines @ 60Hz)
 = 70000000 / 60 Hz. Cycles per frame
 = 1166666 cycles/frame

1166666/262 lines
 = 4452 ARM cycles/line


So, available VB time for ARM
 = 26 scanlines * 4452
 = 115752 ARM cycles

Available OS time for ARM
 = 20 scanlines * 4452
 = 89040 ARM cycles

So, according to me I'm only using ~115K and ~89K cycles when this problem happens.
My code is now very complex, so perhaps I could share confidential binary for you to find correct value?

**Comment by thrust26** [comment] 2024-06-02 15:14
Well, I suppose your code loops longer than you expect. And this error is correct.

**Comment by andrew-davie** [comment] 2024-06-02 15:15
> Well, I suppose your code loops longer than you expect. And this error is correct.

No, you miss the point. This runs correctly on hardware. Stella should not be halting.

**Comment by thrust26** [comment] 2024-06-02 15:30
So you mean the code doesn't run that long, right?

Then, which Stella version are you using? And I would need a binary to find out why is executes that long in Stella.

**Comment by andrew-davie** [comment] 2024-06-02 15:35
> So you mean the code doesn't run that long, right?
> 
> Then, which Stella version are you using? And I would need a binary to find out why it executes that long in Stella.

500k instructions -- that's what the dialog says.
ARM instructions?  6507 instructions?  Either way, it's ridiculously large - are you sure it's really 500K?
My code does not run that long, no... I am confident.  I am using Stella 6.7
I am happy to share a binary via PM.

**Comment by thrust26** [comment] 2024-06-02 15:43
> 500k instructions -- that's what the dialog says. ARM instructions? 6507 instructions? 
> Either way, it's ridiculously large - are you sure it's really 500K? 

Yes. The code checks for 500K consecutive ARM instructions..

> My code does not run that long, no... I am confident. I am using Stella 6.7 I am happy to share a binary via PM.

You still have my email address? Else PM me via AtariAge.

**Comment by andrew-davie** [comment] 2024-06-02 16:10
A bit of sleuthing here, in the following code Stella will fault as above, and Gopher and running on Hardware (via Harmony cart) will not fault...

```
    T1TC = 0;
    T1TCR = 1;

    while (T1TC < 1)
        ;
```

My working theory here is that the timer is not incrementing. Either I have not initialised it correctly, or Stella is buggy here. If I have not initialised it correctly then also this must mean the Harmony cart is initialising it for me and I've not done it right - but ALSO that the Gopher emulator also has default/init for the timer such that the above code works.

Essentially TL;DR - the while loop is infinite (in stella) because the T1TC value never increments. This looks like a timer initialisation bug - probably me - but I need some assist if that's the case; what is the correct way to init/run the timer? Are there scaling vars that are not initialised in stella or my code or gopher or harmony or combination thereof?

**Comment by thrust26** [comment] 2024-06-02 18:00
I remember that I once tried to add missing timers to thumb (thought that was T0TC). Maybe I did wrong? Or maybe you compiler optimizes that while loop away? But then, why would it work in Gopher and on real hardware?

Here we are mostly relying on external development support. Maybe you can have a look?

**Comment by andrew-davie** [comment] 2024-06-03 00:04
If stella does NOT update timer values in real time during ARM execution, but instead adjusts them after ARM code is complete, this would exactly explain the situation I see. Essentially, my sample code will not work if the timer is not correctly updated on-the-fly. A post-ARM timer adjust would see most games work, but not this one.  So... question... are timer values adjusted every ARM instruction, or only periodically, or worse yet... after ARM code is complete?

**Comment by thrust26** [comment] 2024-06-03 06:04
Here is the code from `thumbulator.cxx`,`read32()`:

```
        case 0xE0008008:  // T1TC - Timer 1 Counter
          if(T1TCR & 1)
            // timer is counting
            data = T1TC + (tim1Total + (_totalCycles - tim1Start)) * _armCyclesFactor;
          else
            // timer is disabled
            data = T1TC + tim1Total * _armCyclesFactor;

   ...
   return data;
```
`_totalCycles` is updated with each ARM instruction. `tim1Total` is set to the value you write into `T1TC`. And `tim1Start` is set to `_totalCycles` when you write to `T1TC`. `_armCyclesFactor` defaults to 1.05, it takes care of some incorrect cycle counts.

So it **should** be updated on-the-fly whenever you read it.

**Comment by andrew-davie** [comment] 2024-06-03 07:19
TY. I can't see much wrong with that, and yet the loop never exits.
I'll PM you a ROM or two for testing.

**Comment by andrew-davie** [comment] 2024-06-03 07:26
TY. If tim1Total is the value you write to T1TC, then why does the code use T1TC as well as a base?  
I don't really understand what this code is doing - adding T1TC *and* the value you sayi is the initial T1TC value. Why is T1TC even in these calculations at all, if "_tim1Total" is the written value?
In any case it looks to me like the loop is never exiting, and that makes no sense. I'll send you a PM/bin to test.

**Comment by thrust26** [comment] 2024-06-03 08:29
Quick fix: Enable Developer Mode.

But I have to find out why everything is disabled on purpose(!) in Player mode.

**Comment by andrew-davie** [comment] 2024-06-03 09:23
I use the timer to determine dynamically exactly how much processing I can do in VB and OS. If I do not have the timer value available, I cannot accurately know if there is sufficient time to call particular functions. So being able to read the timer value at any time is critical. I am deliberately holding the ARM because I was trying to find the exact timer value where things went overtime. At this point I found that Stella locked-up as advised and began hunting the bug. I do not particularly want to have a wait-loop like that, but it is not *wrong*.  But the wait loop highlights that the read of the timer value is not correct and I most definitely absolutely NEED to be able to read that value on the fly.  IMHO the emulator should behave like hardware.

**Comment by thrust26** [comment] 2024-06-03 10:07
I get you. So you are doing something similar with ARM that we did with Boulder Dash? Timeslices? 

The problem is, that you cannot rely on exact cycles counts. These are something we found impossible for thumb emulation. There are way too many factors involved. And they differ between chips used and ARM setup code (which we cannot see). Some parts are not even fully documented. You can search the web for more detailed information. 

Therefore Gopher and Stella are only **approximating** the cycle count, with no guarantees made. So, will this still be usable for you?

BTW: If I enable that for player mode and ARM games become too slow on some platforms, I will point at you! 😈

**Comment by andrew-davie** [comment] 2024-06-03 10:09
Yes, a dynamic timeslice system. I am aware that I cannot rely on exact times, so I add ~20% for inaccuracy. But even so I need to be able to decide if I should call a function or not. So I need to read the timer value dynamically.  Regarding slowing down other games, I would be willing to add code which signals to Stella to enable/disable the cycle counting cability so that it runs for my game, and not by default.

**Comment by andrew-davie** [comment] 2024-06-03 10:14
... actually couldn't any read of T1TC simply enable the cycle accurate system, which is otherwise disabled?

**Comment by thrust26** [comment] 2024-06-03 10:15
IIRC SpiceWare is using the timers to differ between PAL and NTSC systems. So that wouldn't work.

**Comment by thrust26** [comment] 2024-06-03 10:19
> Regarding slowing down other games, I would be willing to add code which signals to Stella to enable/disable the cycle counting cability so that it runs for my game, and not by default.

Seems like a good idea. How would that look like? Writing to a special address?

**Comment by andrew-davie** [comment] 2024-06-03 10:40
Looking at the LC214X manual, it appears that although the register T1TCR is 8 bits only, there are actually 32 bits of address space reserved (i.e., registers are long-word aligned). One could use D8 of the 32 bit value (on a write) to indicate to Stella the suggested disable/enable of counting and hopefully not affect real hardware.

**Comment by thrust26** [comment] 2024-06-03 10:41
> Looking at the LC214X manual, it appears that although the register T1TCR is 8 bits only, there are actually 32 bits of address space reserved (i.e., registers are long-word aligned). One could use D8 of the 32 bit value (on a write) to indicate to Stella the suggested disable/enable of counting and hopefully not affect real hardware.

You better test that before we go for it. Maybe a read would be less risky? We only have to find a working address.

**Comment by JetSetIlly** [comment] 2024-06-03 10:47
A read of the APBDIV register (0xE01FC100) might be good. The register is only used to read/write the divisor for the peripheral (timer) clock. If a program is touching that address then it would indicate that the programmer is interested in hardware detail not normally required.

**Comment by andrew-davie** [comment] 2024-06-03 11:03
I might also note that the manual specifically reserves bit 2-7 as "do not set to 1" but simply treats it as an 8-bit register and doesn't seem to care about D8-D31. If the other bits were important I would expect the manual to say so.

**Comment by thrust26** [comment] 2024-06-03 11:18
I would prefer JetSetIlly's approach. It seems less hacked.

**Comment by andrew-davie** [comment] 2024-06-03 11:23
> I would prefer JetSetIlly's approach. It seems less hacked.

I am happy to proceed that way.

**Comment by thrust26** [comment] 2024-06-03 11:29
I just committed 40ba8969, which needs testing. 

@andrew-davie Can you build Stella yourself?

**Comment by andrew-davie** [comment] 2024-06-03 11:34
> I just committed [40ba896](https://github.com/stella-emu/stella/commit/40ba8969eab37f3dfbf3a9857668669a071530c4), which needs testing.
> 
> @andrew-davie Can you build Stella yourself?

I have done it previously, but not on my new machine.

**Comment by thrust26** [comment] 2024-06-03 11:36
Windows?

**Comment by andrew-davie** [comment] 2024-06-03 11:41
MacOS. Tried, following instructions at https://stella-emu.github.io/development.html for MacOS.
No luck; XCode is not happy...

![Uploading Screenshot 2024-06-03 at 9.40.01 pm.png…]()

**Comment by thrust26** [comment] 2024-06-03 11:57
We recently had weird build problems with MacOS lately. If I get @DirtyHairy right, he was able to fix them by using a newer version of XCode.

**Comment by andrew-davie** [comment] 2024-06-03 13:44
OK, I have succesffully built Stella.
Confusingly, my wait loop no longer causes the timeout... but I have changed nothing in my code.

**Comment by andrew-davie** [comment] 2024-06-03 13:55
I tried 'git checkout git checkout  40ba896' which set me to the branch 'HEAD is now at 40ba8969e added option to enable thumb cycle counting via emulated ROM' which looks OK. Then to XCODE and do a build, and I get the following...

[
<img width="266" alt="Screenshot 2024-06-03 at 11 53 19 PM" src="https://github.com/stella-emu/stella/assets/16424075/ec3ad81a-1fc8-4260-8058-cbb72cbc71d9">
](url)

**Comment by thrust26** [comment] 2024-06-03 14:38
So it once did build and after you updated one class it stopped building?

**Comment by andrew-davie** [comment] 2024-06-03 14:39
> So it once did build and after you updated one class it stopped building?

Sounds like a me-error. I thought I was grabbing the branch not an individual checkin. Wasn't thinking, sorry.
What's the branch I should grab?

**Comment by thrust26** [comment] 2024-06-03 14:52
Master.

**Comment by andrew-davie** [comment] 2024-06-03 15:02
> Master.

Ah, OK. I am not used to testing/experimental stuff being on the master branch. So be it.
OK, good news and strange news.  With the following code at my SystemReset() startup...

`
    actualScore = APBDIV;

    T1TCR = 1;
    T1TC = 0;

    while (T1TC < 1)
        ;
`

Stella 6.7 of course still gives the 500K timeout.  Stella 7.0_pre successfully runs as hoped. But my palettes are all greyscale, which is extremely odd!   Gopher displays expected palettes.

<img width="752" alt="Screenshot 2024-06-04 at 1 02 18 AM" src="https://github.com/stella-emu/stella/assets/16424075/afbaf3e0-bc53-4588-b2bd-6b10d41ce2c9">

**Comment by thrust26** [comment] 2024-06-03 15:09
I have no clue what is causing this. Here the colors are fine.
![BDTJStella](https://github.com/stella-emu/stella/assets/24360774/681827ae-da27-40ce-bd5f-28f7b9cb37ea)

**Comment by thrust26** [comment] 2024-06-03 15:15
The new ROM looks fine too. Must be your Stella build.

**Comment by thrust26** [comment] 2024-06-03 15:31
OK

**Closed by thrust26** 2024-06-03 15:31 UTC
Labels: bug, enhancement

**Comment by andrew-davie** [comment] 2024-06-20 09:28
An update to this one - if you run in developer mode, the read of APBDIV is treated as a fatal error. I think this is incorrect - we want this to be legal now.

<img width="551" alt="Screenshot 2024-06-20 at 7 26 09 PM" src="https://github.com/stella-emu/stella/assets/16424075/5422b4ed-59d8-42bd-b6ac-f54c55c2f159">
