### ISSUE TITLE
Activision Grand Prix - Momentary scanline corruption

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#82] opened 2017-01-19 07:33 UTC
Momentary scanline corruption, left side of screen, same row and color where opponent car appears

http://atariage.com/forums/topic/259633-testing-the-new-stella-tia-core/page-3#entry3674988

Note: On the right side some pixel disappear then. Happens in Stellerator too. There is an HMOVE @74 followed by a NUSIZ1 change (1->7) involved.

**Comment by DirtyHairy** [comment] 2017-01-20 23:48
Spot on, thank you, @thrust26 . The issue is indeed the incomplete description of the effects of NUSIZ during draw. 6070291 improves this and fixes this (and #87), but on the long run, systematic testing is required to get all these cases described correctly (#63).

**Comment by sa666666** [comment] 2017-03-05 00:23
There is still a little bit of an errant scanline appearing on the left of the screen, as reported at http://atariage.com/forums/topic/259633-testing-the-new-stella-tia-core/page-6#entry3710714.  The current code fixes it quite a bit, but not completely it seems.

**Comment by DirtyHairy** [comment] 2017-03-05 13:35
Cancelling any pending draw on NUSIZ removes this artifact, so this is definitely connected to NUSIZ during player draw / decode. It is very possible that this will be fixed by modelling TIA behavior in the situations outlined in my last comment on ticket #63 .

**Comment by DirtyHairy** [comment] 2017-03-07 23:07
Fixed by e021660

**Closed by DirtyHairy** 2017-03-07 23:07 UTC
Labels: affects 6502.ts, regression test
