### ISSUE TITLE
Stella crashes when attempting to load a zip file as rom directory

### ISSUE THREAD

**Issue by anonymous7002** [stella-emu/stella#749] opened 2020-12-25 19:24 UTC
When I ran Stella for the first time, it worked fine, but when I ran it the second time, it crashed on startup.
I tried uninstalling and reinstalling Stella and vcredist, but couldn't get it to work.

P1: Stella.exe
P2: 6.4.0.0
P3: 5fa00463
P4: ucrtbase.dll
P5: 10.0.18362.1110
P6: b4cacc38
P7: 000000000006dace
P8: c0000409
P9: 0000000000000007
P10:

**Comment by sa666666** [comment] 2020-12-25 19:29
- Open Windows Explorer and go to %APPDATA%/Stella
- Delete the stella.ini file
- Start it again

If it starts again only once and then crashes, then it must be something in the settings causing it to happen.  If it _never_ starts again, even after deleting the settings file, then it's something more serious.

Also, uninstalling and reinstalling will almost never fix an issue like this.  If it worked the first time, then the install was fine.  So reinstalling won't actually fix anything in that case.

**Comment by sa666666** [comment] 2020-12-25 19:30
Also, what version of Stella (32 or 64-bit), what version of Windows, etc are you using?

**Comment by anonymous7002** [comment] 2020-12-25 19:30
Windows 10 64-bit.

**Comment by anonymous7002** [comment] 2020-12-25 19:30
Now it works again, starting multiple times.

**Comment by sa666666** [comment] 2020-12-25 19:31
So after deleting the INI file, all is working fine now?  It starts every single time?  If so, problem solved I guess.  But I'm still curious why it happened in the first place.

**Comment by anonymous7002** [comment] 2020-12-25 19:34
Starting multiple times, but if I open a game, close and open the emulator, same exact problem.

**Comment by sa666666** [comment] 2020-12-25 19:35
A quick Google search seems to indicate to make sure you have the very latest vcredist installed, as well as all updates to Windows itself.  So I guess you need to try that next.

**Comment by sa666666** [comment] 2020-12-25 19:39
Otherwise I'll have to wait until other members of the Stella team see this, as I don't work on the Windows versions exclusively (I'm more on the Linux side of things).

**Comment by anonymous7002** [comment] 2020-12-25 19:39
It apparently tried to load a zip file as a rom directory. Removed the zip, now it works again.

**Comment by sa666666** [comment] 2020-12-25 19:39
Please provide the ZIP file that causes the problem.  If I can see it on my end, it will be much easier to figure out.

**Comment by anonymous7002** [comment] 2020-12-25 19:40
[Dragster (USA).zip](https://github.com/stella-emu/stella/files/5742322/Dragster.USA.zip)

**Comment by sa666666** [comment] 2020-12-25 19:43
So to be clear, it works until you start this ROM?  And then afterwards, it crashes?  Or does it crash while trying to start this ROM?

**Comment by anonymous7002** [comment] 2020-12-25 21:24
When I ran Stella for the first time, and loaded the rom, I could play it, and even got a 5.67 ;)
Then, when I closed Stella and ran the program again, it crashed right on startup. I couldn't even get to rom loading screen.
When I removed the zip folder that was left from extracting, it now works again as normal.

**Comment by sa666666** [comment] 2022-05-30 19:29
Can anyone else confirm of this issue is still present in the most recent code?  I cannot reproduce it.

**Comment by thrust26** [comment] 2022-05-30 19:38
I don't think that I ever was able to reproduce this either.

**Comment by sa666666** [comment] 2022-05-30 21:07
I will give it a few days, to see if the original poster replies.  Otherwise, we can close it.

**Comment by sa666666** [comment] 2022-06-09 19:16
No further feedback, so I'll assume it's no longer an issue.

**Closed by sa666666** 2022-06-09 19:16 UTC
Labels: bug, needs research
