### ISSUE TITLE
Snapshots corrupted with "disable image filtering" option

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#222] opened 2017-09-12 15:35 UTC
If you select the option "Disable image filtering (1x mode)" in the "Snapshot Settings" window, the resulting pics are corrupted in the lower half of the frame:
![centipede 1982 atari - gcc cx2676 pal](https://user-images.githubusercontent.com/24704739/30334600-5d16033c-97e0-11e7-84b7-f825de01e9ec.png)

Also, is that option really needed? I think that players would usually prefer snapshots of what they're actually seeing while playing (with filters and all). 
A 1x snapshot without filtering might sometimes be useful for developers, but there's already the "savesnap" command in the debugger (and the keyboard shortcut added in #161) for that, and the bug doesn't show there.

**Comment by ale-79** [comment] 2017-09-12 15:47
> is that option realy needed? 

On a second thought, the option _is_ useful when saving continuous snapshots (with ALT+S or SHIFT+ALT+S)

**Comment by thrust26** [comment] 2017-09-13 10:20
Confirmed, but only with phosphor enabled.

**Comment by thrust26** [comment] 2017-09-17 14:22
The artifacts are clearly coming from a frame with a higher resolution (4x?). Probably the phosphor data from a previous frame with higher resolution is applied to the current frame with 1x. 

So this might be related to #202.

**Comment by thrust26** [comment] 2017-09-17 15:22
Closed with f0ced8a

**Comment by thrust26** [comment] 2017-09-17 17:11
Still buggy. 😠

**Comment by sa666666** [comment] 2017-09-17 18:26
Only when both TV effects _and_ phosphor is enabled.

**Comment by sa666666** [comment] 2017-09-17 19:02
I guess the real question here is if disable filtering/1x mode should also disable phosphor effect too.  I think it should, since in all cases where TiaSurface::pixel() is called, phosphor is not seen anyway (since you're getting only a snapshot in time, and phosphor depends on multiple snapshots to see the blending.

**Comment by sa666666** [comment] 2017-09-17 19:19
Fixed in https://github.com/stella-emu/stella/commit/f442fae8904b439addb7a2776b1c7b77ea3c6412.  Basically, phosphor mode is disabled when calling TiaSurface::pixel().  This is correct, since that method is supposes to return data from the TIA output itself, with any filtering/phosphor/post-processing happening.

**Closed by sa666666** 2017-09-17 19:19 UTC
Labels: bug
