### ISSUE TITLE
GameInfoDialog 'Defaults' option bugs

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#297] opened 2018-02-12 09:11 UTC
If you press 'Defaults' on any tab in the `GameInfoDialog`, the following happens:
1. all values in **all** tabs are set to default (in all other dialogs only the **current** tab is affected)
2. all **following** changes to external props are ignored 
3. the data for **all** tabs is cleared in 'Stella.pro'. 
4. for 'known' games, the defaults are set to valid values (e.g. md5 and manufacturer are filled), for games added by the user (also contained in 'Stella.pro') the values are cleared. I cannot see the logic behind that and also what is causing this different behavior.

For 2. and 3. the problematic code in `saveConfig()`  is:
```
  // Determine whether to add or remove an entry from the properties set
  if(myDefaultsSelected)
    instance().propSet().removeMD5(myGameProperties.get(Cartridge_MD5));
  else
    instance().propSet().insert(myGameProperties);
```
@sa666666 IMO the 'myDefaultsSelected' logic doesn't work at all and should be removed. Else it should be replaced with something more complex which considers individual changes.

We should decide if 1. is a bug too.

**Comment by thrust26** [comment] 2018-06-02 09:52
I think the dialog should be changed like this:
- _Default_ button only defaults the **current** tab (to be consistent with all other dialogs)
- current `myDefaultsSelected` logic should be removed
- if we still want to remove entries (IMO no necessary) from a property set, we should either 
a) add a new button or 
b) check if all values for all tabs are identical with the default values

**Comment by thrust26** [comment] 2018-07-12 13:46
@sa666666 What shall we do with 3.? 

- Ignore? Then we can close this one. 
- Else we have to decide how to continue

**Comment by sa666666** [comment] 2018-07-25 23:56
I will work on this next, since I just found a bug with this and the new dirty-render code.  Basically, we already have a message in this dialog that changes require a ROM reload.  But some of them are immediate, and some are not (and several of those that are not cannot be done dynamically).

I propose to make this dialog only modify the properties to be loaded/saved to the properties database, and **not** have them dynamically change things.  This would make the dialog consistent.

Your suggestions also need to be taken into account, and the current logic needs to be fixed.

**Comment by thrust26** [comment] 2018-07-26 07:05
I would prefer that some things stay working immediate (e.g. phosphor). We have the '*' and the according message to mark those which require a reload. And other dialogs are mixed here too, so why should we limit ourselves here? 

IMO, the more changes we can make work without reloading, the better.

**Comment by sa666666** [comment] 2018-07-26 11:19
The problem is that the (*) indicates (or it _should_ indicate) that _none_ of the settings are dynamic.  Some of them can't be changed, so it makes more sense to me to make this dialog be used for changing the properties database only, not for changing the current settings in emulation mode.  Also, it fixes a bug with the new dirty-update code if I change the dialog to not make dynamic changes.

For the settings that are currently dynamic (format, ystart, height, etc), there are already keyboard shortcuts to dynamically change them.  I would rather make the dialog pick up on these when it's opened, but only exist to load/save those settings into the database.

Some of the buttons probably need to be renamed, etc, but this is the direction I want to go here.

**Comment by thrust26** [comment] 2018-07-26 11:39
BUT there is no (*) in the "Display" tab (anymore). :smile:

I know we have keyboard shortcuts for those, and as a user who can't remember all those shortcuts I would assume that this dialogs helps me here. Having to reload just because I used a dialog instead of a shortcut seems very odd. 

Generally I suppose that's a matter of perception. We had a similar discussion about persistent an non-persistent settings. E.g. phosphor and its blend values are settings which are not persistent if you use the shortcuts while changing the volume is persisted. IIRC the logic behind this is, that global settings are persisted, game only settings are not. Correct? (See, even I can't remember it! :wink:)

So I suppose for you this dialogs is just for updating the internal database (which is then used on reload). While I want it also to be(come) an alternative for using shortcuts (which most people will hardly remember).

**Comment by sa666666** [comment] 2018-07-26 12:02
Yes, I now see that the (*) message is removed from the last tab :smiling_imp: 

I guess your last paragraph really sums up the situation; do we make it a dialog for modifying the database or an active dialog for dynamic changes (or both, with separate buttons for different functionality):
- PRO: dynamic changes would be nice, so we don't _have_ to remember key shortcuts
- CON: I need to fix a bug in the dirty-update code, because currently if you make a change to any settings in the display tab and press 'OK', the TIA screen is blanked

Overall, I don't have a problem with making as much of this dialog as possible dynamically change current settings.  But it is a bit more work than first appears, and I wonder if we should tackle it for 5.2??

**Comment by thrust26** [comment] 2018-07-26 12:10
IMO we can do this step by step and there is no need to do this all at once. As long as the dialog still informs the user about the reload where required we should be fine.

Not sure were you want to go with separate buttons (save only + save and apply?) What would be the advantage from user perspective?

**Comment by sa666666** [comment] 2018-07-26 12:19
If I can fix the dirty-update blanking screen bug, I have no issue leaving it as it is now, and expanding on it further.

As to your second point, there may be times you want to apply the settings you've just made and _not_ save them permanently.  It's the persistent vs. non-persistent argument all over again :smiling_imp:

**Comment by thrust26** [comment] 2018-08-04 10:03
Agreed. But in that case, I would consider the dialog settings persistent and the the hotkeys non-persistent.

Anyway, I suppose this would make things even more complicated, so IMO we should keep things persistent as they are now.

**Comment by thrust26** [comment] 2018-08-05 07:45
@sa666666 
I am trying to make changes to the _Controller_ tab immediate too. So I tried:

`instance().console().setControllers(myMD5->getText());`
and also 
`instance().console().system().consoleChanged(...);`

This seems to work for joystick games (e.g. _Swap ports_). But for a paddle game this results into the mouse not reacting anymore. So I must be missing something. Any ideas?

**Comment by sa666666** [comment] 2018-08-06 15:45
Just seeing this comment now.  Many of the items in this dialog are not meant to be 'hot-switched', since the code wasn't designed for it.  After discussing it with you, I now agree that it would be ideal for everything to be hot-switchable.

Now, as to how feasible this is before the next major release, I'll have to look into it.  This is what I'll work on next.

**Comment by thrust26** [comment] 2018-08-06 15:50
The hot-switching is not too critical IMO. The 6.0 target for more for the inconsistency of the dialog.

**Comment by sa666666** [comment] 2018-08-06 15:51
OK, we need some clarification on what buttons will be here (ie, what functionality we want this to have).  The following summarizes so far:
- We need a button that can somehow reset back to that stored in the internal database (and in the process remove the entry from the external file/database entirely).  So do we use another button for this, tie it to the 'Default' button, etc?

- The fact that 'Default' now works only for each tab (instead of all of them at once) implies that we need _another_ button for resetting.

- Do we need a button to apply settings vs. saving them (ie, does save do an immediate apply _and_ save to database, or do we have two buttons for that?

**Comment by thrust26** [comment] 2018-08-06 16:12
1. Wouldn't defaulting all tabs have the same result? I don't think we need a _Default all_ button. And is it really important to remove entries from the database?
2. Why another button? That would be four by now, right?What would that be used for???
3. A 5th button? I really don't think we need an _Apply_ button.

So I don't think we need any extra button here. And only _maybe_ the logic to remove an entry from the external database.

**Comment by sa666666** [comment] 2018-08-06 16:12
I propose to make the topic of this dialog doing runtime changes (aka, hot-switching) a separate issue, and for this one to address only the points in my previous message.

**Comment by sa666666** [comment] 2018-08-06 16:14
I want a button (or some facility) to remove from the database, since otherwise it can grow without bound.  Sometimes it is nice to just reset back to the defaults.  And every entry that is saved to stella.pro slows down startup time (probably negligible, but still a valid point).

OK, what buttons do you want, and what functionality should they have.  Please be specific :smiling_imp:

**Comment by thrust26** [comment] 2018-08-06 16:28
OK, go ahead.

**Comment by sa666666** [comment] 2018-08-06 16:36
No, I was asking you what buttons we need.  There are now three:
- Default: sets entries in current tab to that from the database
- OK: saves all properties to database, and at the same time applies those that can be changed at runtime
- Cancel: obvious, do nothing

Do you at least agree with those?  Do we need to change the names on the buttons??

**Comment by thrust26** [comment] 2018-08-06 16:41
No, they are all fine.

**Comment by thrust26** [comment] 2018-08-08 19:13
Just in case: The screen blanking bug is due to #333.

**Comment by sa666666** [comment] 2018-08-09 15:17
Just to add to this; there is already logic in PropSet (I believe) that will check if the properties are the same as what is already built-in, and if so, it will not be saved to the external stella.pro file.  So I suppose just clicking 'Default' on every tab will, in the end, accomplish the same thing.  It's just that the removal will be implicit, not explicit.  I'm fine with that too.

**Comment by sa666666** [comment] 2018-08-23 15:50
This is basically done, but I will leave the issue open until #333 is addressed.

**Comment by thrust26** [comment] 2018-09-13 21:30
@sa666666 Now that #333 is closed, can we close this one too?

**Comment by sa666666** [comment] 2018-09-13 22:14
Nope, still not taken care of.  Start a ROM and go to "Game Properties".  Then click 'OK'.  The frame auto-detect kicks in, resulting a blank screen, since somewhere along the line `TIA::reset` is called (or some similar method).  This resets the TIA framebuffer image to all black, and this is what we see; a blank screen.  As soon as we exit the menu, drawing returns to normal.

I'm not sure if this should be a show-stopper for 6.0, or we can deal with it later.  Opinions??

**Comment by DirtyHairy** [comment] 2018-09-13 22:38
The black screen is due to spurious calls to `TIA::frameReset()`. I removed them in 52494335 . Btw, it turns out that changing ystart in the GUI was broken in 5.1, too (didn't change anything), and I am pretty sure that it was also broken in 5.0.

I just noticed that I can change ystart in the GUI, but the result is *not* save. I'll open another ticket, this is likely to be unrelated to my changes.

**Comment by sa666666** [comment] 2018-09-13 22:50
The method is still being called from somewhere; perhaps from `TIA::reset()`.  So I still need to track this down.

**Comment by DirtyHairy** [comment] 2018-09-13 22:57
Yes, it is called from `TIA::reset()`, and that call is legitimate and required :smirk:

**Comment by sa666666** [comment] 2018-09-13 23:03
OK, so I need to decide whether the screen needs to be blanked at all in such cases.  `TIA::frameReset()` is called from `reset` (as you say), and also from `GameInfoDialog` and `Console`.  I have to analyze whether it still needs to exist at all.

**Comment by DirtyHairy** [comment] 2018-09-13 23:16
It absolutely should to be called from `TIA::reset()`. I am pretty sure the other calls can be removed.

**Comment by sa666666** [comment] 2018-09-13 23:18
But it's the call from `TIA::reset()` that's the problem!

**Comment by DirtyHairy** [comment] 2018-09-13 23:32
Trust me, we need the call in reset 😉  It is required to get the buffers into a consistent state - they are only partially overwritten between frames, and not clearing them during reset might result in garbage in the blank parts of the screen.

**Comment by DirtyHairy** [comment] 2018-09-13 23:34
Technically, you only need to clear one of the three buffers, but I don't see any benefit in not clearing all of them instead of just resetting to a sane state.

**Comment by sa666666** [comment] 2018-09-13 23:41
OK, so that means this issue needs to be solved in another way.  After pressing 'OK' in the dialog, a call is eventually made to `TIA::reset()`.  If we accept that the framebuffers absolutely need to be cleared (which does make sense), then the display will immediately show a blank screen, since we've just blanked the TIA.

This was never an issue with the old code, since the frame was updated continuously.  Now that it's not, we need to force it.  Perhaps call `FrameBuffer::update` to force a redraw?

**Comment by sa666666** [comment] 2018-09-13 23:58
So, I have no idea how to proceed.  I figured I would call `TIA::update()` to force an update of the framebuffers in the TIA class.  Then `FrameBuffer::update(true)` to force a full redraw.  Problem is, the force re-render is happening fine; it's just that it's rendering an image that contains all black pixels (aka, blank screen).  So it looks like `TIA::update()` isn't actually doing anything.

Overall, the problem is: what should the screen show after `setFormat` has been run?  If called in emulation mode, the TIA is updated and it just shows the next screen.  But in UI mode, we need the TIA to be updated at least once, so that the blanked buffers are filled with something.   And that's not happening.  And I can't figure out why.

**Comment by sa666666** [comment] 2018-09-14 00:10
Nevermind; problem is solved in https://github.com/stella-emu/stella/commit/b9bbbe13813aaee5dda62037611686ab095f2e6b.  I see that we have to use `renderToFramebuffer` instead of `update`.  I forgot that one updates the TIA state, and the other posts those updates to the framebuffer for eventual redraw in `FrameBuffer::update()`.

**Comment by thrust26** [comment] 2018-09-14 17:02
When changing yStart, this is not reflected until the display format is changed or the game is reloaded.

Also we should avoid the long delay for auto display format detection when not required.

**Comment by sa666666** [comment] 2018-09-14 19:41
And now the screen stays black again sometimes :sob: 

This is getting really annoying.  I fear the code was just not designed to have this stuff change dynamically.  That's when all the problems started; when we try to change the settings without doing a full reload.

**Comment by sa666666** [comment] 2018-09-14 19:44
Also beginning to think we should have left the ystart stuff alone until after 6.0.  Because now we have non-working code, and can't really roll it back since so much as changed.  And all this work will disappear when we refactor ystart stuff after 6.0.  Arrgh.

**Comment by thrust26** [comment] 2018-09-14 19:49
It used to work, so I am positive we can fix it. Before or after 6.0.

**Comment by sa666666** [comment] 2018-09-14 19:54
But there have been significant changes since it last worked.  First, changing properties is now dynamic.  Second, we moved from updates every frame to only update when something changes.  That one alone is huge, and can't be wound back (nor would I want to).

**Comment by thrust26** [comment] 2018-09-14 20:07
It still worked in 5249433.

**Comment by sa666666** [comment] 2018-09-17 19:58
I think (hope!) we can now close this again, since the background is no longer blanked when exiting `GameInfoDialog`???

**Closed** 2018-09-17 20:20 UTC
Labels: bug, target 6.0
