### ISSUE TITLE
3E+ broken - latest release

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#658] opened 2020-06-08 09:50 UTC
It appears that 3E+ bankswitching is broken in the latest release.
For example... the following code...

```
    lda #$80
    sta $3E
```

This should switch bank/slot #2 to use RAM bank 0.
In fact, the debugger shows it switching ROM bank #30 in.
Something appears to be quite wrong there!

**Comment by thrust26** [comment] 2020-06-08 10:05
All files I have seem to run correctly. Is this a debugger problem only?

**Comment by andrew-davie** [comment] 2020-06-08 10:07
Local build MacOS using XCODE.
Previous version works OK, and RAM bank switches correctly.
This new version does not work.

I put the indicated code very first thing after "CLEAN_START" call and stepped through, watching the bank switching happening.
I have reverted to previous version (again, compiled locally) and it is working OK.
Pretty sure there's a bug in the 3E+ in the latest release!

**Comment by thrust26** [comment] 2020-06-08 10:09
So your own builds crash now? Can you provide an example ROM?

**Comment by andrew-davie** [comment] 2020-06-08 10:40
I have done a re-grab of Stella (via ZIP this time, instead of 'git pull' as per last time) and re-build and getting same results. Note that stella is identifying as '6.2.1_pre'

Attached is a ROM file which attempts to switch in 3 RAM banks (to "slot" 1,2,3)
When attempting to set slot 1 to RAM bank 1, it switches in RAM bank 0
Similarly, slot 2 RAM bank 2 switches in RAM bank 1
And slot 3 RAM bank 3 switches in RAM bank 2.
And I re-confirm attempting to set slot 2 to RAM bank 0 actually sets it to ROM bank 30

2 videos in the ZIP showing "good" version and "bad" version, with "bad" being the latest.
ROM attached.

To test, load/run ROM, hit ~ to get to debugger.
Put a breakpoint on the line after "bne .ClearStack"

You see three bankswitch efforts, all to RAM
$41 = slot1, bank 1.  But it switches in bank 0
$82 = slot2, bank 2, but it switches in bank 1
$CA = slot3, bank 10, but it switches in bank 9

The good/bad videos show this for the two versions of stella. I highlight the bank switch issue with the mouse, to make it clear.

[3E+Bug.zip](https://github.com/stella-emu/stella/files/4745411/3E%2BBug.zip)
[goodbadvid.zip](https://github.com/stella-emu/stella/files/4745410/goodbadvid.zip)

**Comment by sa666666** [comment] 2020-06-08 12:23
> I have done a re-grab of Stella (via ZIP this time, instead of 'git pull' as per last time) and re-build and getting same results. Note that stella is identifying as '6.2.1_pre'

Just commenting on this part.  I've already started new commits to master, which is what you're accessing.  That's fine, but if you want the exact code that was released for 6.2, you need to use the 6.2 tagged release.

**Comment by andrew-davie** [comment] 2020-06-08 12:24
> Just commenting on this part. I've already started new commits to master, which is what you're accessing. That's fine, but if you want the exact code that was released for 6.2, you need to use the 6.2 tagged release.

I will do that ASAP and report back.

**Comment by sa666666** [comment] 2020-06-08 12:29
Well, it won't make a difference in this case, since very little has changed since the release (only 2 commits).  I just wanted to explain _why_ you're seeing the discrepancy.

**Comment by andrew-davie** [comment] 2020-06-08 12:39
> Well, it won't make a difference in this case, since very little has changed since the release (only 2 commits). I just wanted to explain _why_ you're seeing the discrepancy.

Noted.

But to just confirm - since I have finished download/build/check.... the official 6.2 release branch performs (incorrectly) as advised above. RAM banks are switched incorrectly.

**Comment by thrust26** [comment] 2020-06-08 12:42
Was that broken just lately? Can you say when?

**Comment by DirtyHairy** [comment] 2020-06-08 12:46
You can use `git bisect` to identify the exact commit that broke it.

**Comment by andrew-davie** [comment] 2020-06-08 12:46
The "good" version I have seems to have last date stamps on files that I do not think I have touched about 4 June 8:32pm.

**Comment by andrew-davie** [comment] 2020-06-08 13:31
I'm wondering - could it be that the display in the debugger is wrong, that the bank #/type are being calculated incorrectly - and the actual bankswitch code is correct?  Just thought I'd throw that up for consideration.

**Comment by DirtyHairy** [comment] 2020-06-08 16:46
What is the SHA of the commit that broke it (according to bisect)?

**Comment by andrew-davie** [comment] 2020-06-08 20:53
```
boo@Andrews-MacBook-Pro stella.bad % git bisect start 900e7dd435829e0c101843cd8cb2aeafd14666c7 79a12351ce9551953131a8575f302035e2548512 
Bisecting: 6 revisions left to test after this (roughly 3 steps)
[070dd48f22172b44efee73644135e119bc4a4a2b] And as usual, some last minute updates.
boo@Andrews-MacBook-Pro stella.bad % git bisect bad
Bisecting: 2 revisions left to test after this (roughly 1 step)
[baa47aec5712181b1d365396659915f4f389a1b2] take care of odd ROM sizes (fixes #653)
boo@Andrews-MacBook-Pro stella.bad % git bisect bad
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[6b14a13f1589a477121a71f73f8171c2b8459a92] Shorten error messages in ROM launcher, to fix overflow of buffer width.
boo@Andrews-MacBook-Pro stella.bad % git bisect good
baa47aec5712181b1d365396659915f4f389a1b2 is the first bad commit
commit baa47aec5712181b1d365396659915f4f389a1b2
Author: thrust26 <tjentzsch@yahoo.de>
Date:   Fri Jun 5 18:04:08 2020 +0200

    take care of odd ROM sizes (fixes #653)

 src/emucore/CartEnhanced.cxx | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)
boo@Andrews-MacBook-Pro stella.bad % 
```

**Comment by thrust26** [comment] 2020-06-08 21:48
That's the one I committed to round **up** the ROM banks.

@sa666666 Is that rounding still necessary?

**Comment by sa666666** [comment] 2020-06-09 00:26
I don't know; I'll have to play with it tomorrow.  But I don't think you need to round anyway.  Just do the calculation, and if it's 0, use 1 instead.  The only case where it crashed was when the result was 0, so maybe that's the only one we need to worry about.

**Comment by andrew-davie** [comment] 2020-06-09 01:19
> I don't know; I'll have to play with it tomorrow. But I don't think you need to round anyway. Just do the calculation, and if it's 0, use 1 instead. The only case where it crashed was when the result was 0, so maybe that's the only one we need to worry about.

I don't see how you could ever get "0" if you have "mySize" set to a whole multiple of the bank size. I don't like special-casing.

**Comment by thrust26** [comment] 2020-06-09 07:21
I think I found the problem. 
1. the bank size is 0x400 (bank shift is 10)
2. `mySize` is 0x7801 (= 30.something banks)
3. `romBankCount()` round this up to 31 banks

So far so good.

But `mySize` (which is not changed) is further used in calculations (not only in the new code, but also in old or unchanged code). And here this effectively rounds the number of banks down to 30 again. 

How to fix this? Ideas:
1. adjust `mySize` (in this case to 0x7c00)
2 introduce a new size variable (rounded to 0x7c00) and use this one for calculations.
3. introduce a new size variable which contains the real ROM size (0x7801, e.g. used for displaying the ROM size in debugger) and adjust `mySize` to 0x7c00 
4. do not use the size variables, but always `romBankCount()` (or a variable)

@sa666666 What would you prefer?

**Comment by andrew-davie** [comment] 2020-06-09 07:25
I have been looking at the code too, and concur with the analysis above, for the most part.
My approach, in particular, would have been to have "mySize" reflect the "virtual" size, not the binary size itself. I don't see why the actual binary size is of any importance after loading.

Also, while I'm commenting on this class in particular - it has a bank(...) call that loads the first bank into slot #3, which is clearly in error. At least in my view. I haven't traced to where it is correctly loaded into slot #0 - presumably by a parent class. I was going to suggest that this load (to bank 3) be removed to avoid confusion but I haven't fully traced why it is doing what it's doing yet, as I said.

**Comment by andrew-davie** [comment] 2020-06-09 10:20
Never mind. Reset Vectors... FFFC.... got it.
I was getting confused about the comment "1st segment mapped to start bank"

**Comment by sa666666** [comment] 2020-06-09 12:28
In the latest code fixes I made, `mySize` should be referring to 'virtual size', as @andrew-davie calls it.  So if the binary is of an odd size, then this is fixed up in `CartEnhanced` c'tor.  For example, one of the crash ROMs was 4094 bytes.  This is fixed in the c'tor so that the buffer is 4096 bytes, and so is `mySize`.

So if I've done my work correctly, once the c'tor is finished, `mySize` is always a 'correct' size for that ROM.  You can depend on this in the rest of the class, and perhaps simplify some of the code.  So any code that you added to round up (or down) can be removed.

**Comment by thrust26** [comment] 2020-06-09 13:05
@sa666666 
I cannot see this fix for the 3E+ example file Andrew posted above. There mySize stays at 0x7801 (but should be fixed to 0x7c00).

**Comment by sa666666** [comment] 2020-06-09 13:11
I will look into it.

**Comment by sa666666** [comment] 2020-06-09 13:21
There's still a bug in my code.  Working on it ...

**Comment by sa666666** [comment] 2020-06-09 14:02
OK, just did commit https://github.com/stella-emu/stella/commit/476a2b2c562f40694306b9641505b41c73ae9681, which makes sure the `mySize` that is used in the rest of the class is that specified by the scheme.

There is still an issue.  Previously, the size was 30721.  Now, it is 32768.  However, you're saying it's supposed to be 31744.

Where does this '31744' comes from?  Why are we not going to the next power of 2 here, like we do for all other ROMs??  As the code exists right now, when creating a `3E/3E+` cart, the desired bankswitch size is set to the power of 2 closest to the ROM size.  So we pass in a rom size of 30721, and a desired size of 32768 (next power of 2 from 30721).  The code sees the discrepancy, adjusts the amounts, and continues on.

If the desired size should have instead been 31744, what formula is determining this?  I can easily change what is passed into the c'tor to be whatever we want, and the current code will still work, fixing up the sizes as appropriate.  But how can I know that 30721 is supposed to map to 31744 and not 32768?

**Comment by andrew-davie** [comment] 2020-06-09 14:06
> OK, just did commit [476a2b2](https://github.com/stella-So we pass in a rom size of 30721, and a desired size of 32768 (next power of 2 from 30721). The code sees the discrepancy, adjusts the amounts, and continues on.


To be pedantic here, shouldn't the desired size ("virtual size") be the next multiple of the bank size?  Not power of two.  That would cause all sorts of issues like expanding a 48K ROM to 64K, for example, when in fact no expansion at all would be required.  The principle, I think, is to ensure that there are no "partial banks", and thus - increase size to the next multiple of bank size, not next power of two.

**Comment by andrew-davie** [comment] 2020-06-09 14:07
... and THAT is where your 31744 comes from.
31 (complete) banks * 1024 (bank size) = 31744 bytes

**Comment by sa666666** [comment] 2020-06-09 14:16
Well, Stella was never really designed to work with ROMs that don't have a pre-defined size, so this is leading to the issues we have now.  In your example of a 48K ROM, there has _never been_ a 48K ROM supported.  So this was never an issue before.

I suppose we can increase to next multiple of bank size instead of next power of 2.  It's just that that's not the way we did things up to this point.  It's easy enough to change it through.  The virtual size is just a value passed to a constructor.  I can just as easily pass 31744 as 32786; just use the correct formula to convert the value from 30721.

**Comment by andrew-davie** [comment] 2020-06-09 14:19
I have no skin in the game. If it's the next power of two, I'm not going to be up in arms about that. I was more or less answering your question about the 31744 size. Also, I'm not particularly fussed any more about the "odd" sizes. If it's easier to not support them, then so be it.

**Comment by thrust26** [comment] 2020-06-09 14:20
I vote for rounding to the next bank size. Else e.g. the debugger will allow selecting banks which do not exist.

**Comment by sa666666** [comment] 2020-06-09 14:22
OK, it's easy enough to fix this.  One other question; where did the ROM of size 30721 come from?  Did you create a ROM with this size specifically to 'harden' the access in Stella?

**Comment by thrust26** [comment] 2020-06-09 14:25
There were previous ROMs from Andrew using 3E+ with odd sizes. I suppose that's how he found the issue.

**Comment by andrew-davie** [comment] 2020-06-09 14:27
OK, me bad.
It came about because of the move of the reset vector to bank 0.
In prior ROMs generated by dasm, the presence of this reset vector in the last bank “automatically” guaranteed a “correct” ROM size.
But as I was developing 3E+ code, I was blissfully unaware that the ROMs I was running were an “illegal” size. They worked, I was happy.
When I tried to fix it, I realised I had no idea how to actually force dasm to pad to a particular boundary, other than, and yes this was a bad idea… to just generate a new bank with one byte in use, and simply never use that bank.  And that’s where it’s been for quite some time.
Using that ROM led to detecting errors in Stella because of the odd size, and subsequent discussion as to how Stella should handle it.
I believe Thomas’s view is that the ROMs were illegal and should not run, because they were not genuine 3E+ ROMs.
And my view, at the time, was that the 3E+ specification did not forbid it, and in fact Stella supported it.
Anyway, water under the bridge.

**Comment by sa666666** [comment] 2020-06-09 14:30
Will the bank sizes always be a power of 2?  Because if we can assume that, the rounding function I create can be faster than the general case.

**Comment by andrew-davie** [comment] 2020-06-09 14:30
> Will the bank sizes always be a power of 2? Because if we can assume that, the rounding function I create can be faster than the general case.

Until someone decides to create a new bankswitch scheme, I would say yes.

**Comment by thrust26** [comment] 2020-06-09 14:31
Yes. The current code only works with power of 2 banks anyway. :smile:

**Comment by sa666666** [comment] 2020-06-09 15:09
OK, the virtual size of 3E/3E+ ROMs is now always a multiple of 1024.  This allows the ROM above to be stored as 31744 bytes internally.

@thrust26, I guess you can continue with your work now, and remove rounding from the various methods.

There is still a slight issue, though.  `3E+` bank size is 1KB.  So its size must be a multiple of 1KB.  That part is working.  However, it seems that `3E` bank size is 2KB.  However, due to the way that inheritance is set up, the current code will also use 1KB bank size for `3E`.  I'm not sure if we care about that, or we should rework this some more??

**Comment by thrust26** [comment] 2020-06-09 15:18
That definitely should be fixed, yes.

**Comment by sa666666** [comment] 2020-06-09 15:27
Well, that complicates things.  The value is passed to `CartEnhanced` c'tor in `Cart3E`, but it originates in `Cart3EPlus`.  Ideally, it would be `1 << banksize` instead of being hardcoded to 1KB.  But by the time we get to `Cart3E`, we've lost the information from `Cart3EPlus`. :anguished: 

About the only way to properly fix this is to do what @DirtyHairy suggested, and have another method that takes care of creating the buffers.  It's not hard, but it means a call needs to be made from every Cart c'tor that inherits from `CartEnhanced`.  I will get to it, I guess ...

**Comment by DirtyHairy** [comment] 2020-06-09 15:41
>  It's not hard, but it means a call needs to be made from every Cart c'tor that inherits from CartEnhanced. I will get to it, I guess ...

You could also add the method to `CartEnhanced` with either an abstract or empty implementation and call it in `CartEnhanced::CartEnhanced`. Descendants can then implement the necessary logic there, and it will be automatically called, without the need to invoke it in every constructor separately.

**Comment by sa666666** [comment] 2020-06-09 15:53
@DirtyHairy, won't we then get compiler warnings about calling a virtual method from a base c'tor at that point?  I did consider this, and wanted to eliminate such warnings.

I suppose it's "6 in one, half-dozen in the other".  I either modify 23 classes and have them call a method from their c'tor, or modify 23 classes and add a virtual `bankSize` method that simply returns a single value (and potentially get a compiler warning).  Either way, I am modifying 23 classes :smiling_imp:

**Comment by DirtyHairy** [comment] 2020-06-09 16:03
Aw. screw it, you're right, forgot about that issue 😏 Not only will  there be warnings, it won't work either. Another idea: give `CartEnhanced` a constructor that receives a `function<void()>` that is called to setup the banks? That way, you can't forget to call it, or  you could add  default  behavior to `CartEnhanced`.

**Comment by DirtyHairy** [comment] 2020-06-09 16:06
Or we could turn `CartEnhanced` into a template that receives its child as template parameter (that's [CRTP](https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern), I guess). We could then call the method for setting up the buffers safely in the `CartEnhanced` constructor, as it wouldn't be a virtual method anymore.

**Comment by sa666666** [comment] 2020-06-09 16:15
Passing a `function<void()>` to `CartEnhanced` c'tor won't work in the case of `Cart3EPlus` -> `Cart3E`, since we'd then need to pass it _through_ the `Cart3E` c'tor.  And sometimes that c'tor is called directly, and we're then breaking the API, forcing code that uses `Cart3E` c'tor directly to pass in that parameter.

The template approach you mention is something I'm not familiar with, and TBH seems to be overkill for what we need here.  Remember, the whole issue here is simply getting the correct banksize, just a single `size_t`.

Really, the problem is that stuff needs to be done by the constructor that can't be done by the constructor :smiling_imp: Another approach would be to create the object and immediately call a method to create the buffer afterwards, in some sort of factory class.

**Comment by DirtyHairy** [comment] 2020-06-09 16:30
I guess you're right. I think the best way to do this is to bite the bullet and just call the necessary method from the constructor of each child.

**Comment by thrust26** [comment] 2020-06-09 16:53
> I think the best way to do this is to bite the bullet and just call the necessary method from the constructor of each child.

And I was so happy that I was able to circumvent doing this. 😒

**Comment by sa666666** [comment] 2020-06-09 16:57
> And I was so happy that I was able to circumvent doing this.

There are ways around it, but I think the easiest way is to just add the call from the ctor.  About to commit the code for this.  We can refactor in the future if you like, but honestly, I don't think it's worth the effort.

**Comment by sa666666** [comment] 2020-06-09 17:05
Hmm, now you have me thinking again.  Still don't feel really comfortable adding the calls to each ctor.  Somehow feels dirty.  So I will consider it some more ...

**Comment by thrust26** [comment] 2020-06-09 18:06
For this case, couldn't we simply create a 2nd constructor for 3E? And this will be called by 3E+, providing the bank size.

**Comment by sa666666** [comment] 2020-06-09 18:25
Yep, already coded, ready to commit.  Just doing some testing.

**Comment by sa666666** [comment] 2020-06-09 18:29
OK, committed with https://github.com/stella-emu/stella/commit/5c879d4a48203f46da268a1483060cfa826f5f0f.  I think this is all now from me.  @thrust26, you can now continue with removing any rounding code still present, and then we can do testing again.

**Comment by thrust26** [comment] 2020-06-09 18:44
I reverted one commit. That's all from my side.

**Comment by sa666666** [comment] 2020-06-09 19:08
OK, now if you and @andrew-davie can test this, we can get this one closed.

**Comment by thrust26** [comment] 2020-06-10 06:20
Looks good for me too. @andrew-davie ?

**Comment by andrew-davie** [comment] 2020-06-10 07:11
My test-case now appears to be working as expected. Thank you for your work on this.

**Comment by thrust26** [comment] 2020-06-10 07:18
Thanks!

**Closed by thrust26** 2020-06-10 07:18 UTC
Labels: bug
