### ISSUE TITLE
System Logs button not working

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#128] opened 2017-05-04 07:19 UTC
When I select "System Logs" in the options menu, nothing happens. The menu gets stuck until I press ESC twice. It seems that the logs window is hidden.

This does **not** happen when the game got started via command line. The bug already exists in 4.7.3.

**Comment by sa666666** [comment] 2017-05-04 11:17
You're using Windows, I assume?  I remember you reporting this, but I cannot duplicate it here at work,  I will have to wait until I get home and have access to a Windows machine.  But even then, I don't think I could duplicate it.  I suspect we will have to narrow this down to see if it's a window problem, or the contents of the window that can't be found, etc.

**Comment by thrust26** [comment] 2017-05-04 12:15
Yes, Windows 10.

I don't think I have reported this one before. Maybe something similar?

**Comment by SpiceWare** [comment] 2017-05-05 12:42
Just tried, happens to me as well when launched via Xcode, icon, or even start a specific game via terminal.  macOS Sierra 10.12.4.

**Comment by sa666666** [comment] 2017-05-05 12:47
Confirmed in Linux as well.  Now I see why I didn't notice it before; it only seems to happen when none of the other window settings are changed (ie, a fresh startup).

**Comment by sa666666** [comment] 2017-05-05 14:40
It seems to only happen when in 2x mode and also in emulation mode.  If you go to a higher zoom level (3x or above), it works fine.  Can you guys confirm this?

**Comment by thrust26** [comment] 2017-05-05 14:48
Doesn't happen in 3x and 4x. What do you mean with "emulation mode"?

**Comment by sa666666** [comment] 2017-05-05 14:53
Basically, not in either the ROM launcher or the debugger (ie, when you have a window that contains the TIA image).

**Comment by SpiceWare** [comment] 2017-05-05 14:57
Confirmed - looks like the System Log is always displayed in the same size window, and that window is taller and wider than the 2x screen.

**Comment by thrust26** [comment] 2017-05-05 14:57
Not happening in the launcher. How do I trigger it within the debugger?

**Comment by sa666666** [comment] 2017-05-05 15:00
You misunderstand.  When I said "not in either the ROM launcher or the debugger", I was answering your question of what "emulation mode" actually is.

**Comment by sa666666** [comment] 2017-05-05 15:02
The problem is that (as @SpiceWare said) the window is larger than a 2x TIA image, so it doesn't display at all.  For now I'm just going to add a dialog box that states as such.  Ideally the window should resize as necessarry, but the UI code wasn't written to change the dialog size after the dialog item has been instantiated.

**Comment by thrust26** [comment] 2017-05-05 15:04
Yup, that also explains why it works with 2x and PAL.

**Comment by sa666666** [comment] 2017-05-05 19:23
Fixed in https://github.com/stella-emu/stella/commit/6ba627e059297d4abc176693002ec1c7b9674aa1.  Basically just shows a message to enlarge the window.  This only affects people using TIA mode (aka, emulation mode) in 2x zoom, which is basically nobody on recent hardware.

A better solution might be to resize the dialog box, but that is an invasive UI change that I don't want to do for this corner case.

**Comment by SpiceWare** [comment] 2017-05-05 20:24
I always run in 2x mode, though this was the first time I'd ever looked at Stella's System Log.

**Comment by sa666666** [comment] 2017-05-05 20:42
May I ask, earnestly, what is your use case?  I suspected that for most people, the window would be much too small to be of use.  And when you use the debugger, it is at least 1000x700 or so, so you must already have the resolution to support more than 2x TIA mode.

**Comment by thrust26** [comment] 2017-05-05 20:51
I always run in 2x mode too. :)

During development, you don't need large windows and save space for other tools.

**Comment by sa666666** [comment] 2017-05-05 20:58
OK, then for now I will leave it as-is, and revisit this for post-5.0.  The problem is that many (most?) dialog boxes are created with a set size inside their c'tors, so resizing is difficult; it might be easier to just recreate the dialog with a new size.

**Comment by SpiceWare** [comment] 2017-05-05 21:00
Yep, space for other development tools.  At times I've even wished for 1x; though, I suspect that would break lots of things.

Anyhow, as I'd never looked at the log before, it's not a high priority for me.

**Comment by sa666666** [comment] 2017-05-05 21:04
It's not just the log, though.  I just noticed it also happens with the browser dialog's under "Snapshot Settings" and "Config Paths" too.  I may have to look into this, because it's more serious than I thought ...

**Comment by thrust26** [comment] 2017-05-05 21:05
Agreed, 1x would be nice occasionally. And the log has low priority for me too.

BTW: I think the windows only needs a few pixel less height, since it works in 50Hz modes, even at 2x.

**Comment by thrust26** [comment] 2017-05-05 21:07
Now I remember those problems! I think I had reported them quite some time ago. And today we found the reason. :)

**Comment by sa666666** [comment] 2017-05-05 21:27
It's not always just a few pixels, though, since if you have a small aspect ratio set, it could interfere with even normal sized windows.  I'll look into it.

However, I have to draw the line at 2x; doing 1x would break everything.

**Comment by sa666666** [comment] 2017-05-05 21:39
Of course, the other option is to create these dialogs dynamically, as the respective button is clicked.  Then it can check the current window size and act accordingly.

**Comment by SpiceWare** [comment] 2017-05-05 22:24
"BTW: I think the windows only needs a few pixel less height, since it works in 50Hz modes, even at 2x."

NTSC windows are narrower than PAL.  I compared screenshots and there's not enough width, nor height, for NTSC to show the System Log. 

I think that's due to Video Settings->General->NTSC Aspect = 90, PAL Aspect = 100

**Comment by thrust26** [comment] 2017-05-05 22:29
I am working with both at 100. Else the pixel width is different.

**Comment by sa666666** [comment] 2017-05-05 22:58
Fixed in https://github.com/stella-emu/stella/commit/bab6e3119d10822723290d0066cefdec7a2dfbb6.  Dialog boxes are now opened dynamically, adjusting for available space.  When appropriate, larger fonts are also used.

**Closed by sa666666** 2017-05-05 22:58 UTC
Labels: bug, target 5.0
