### ISSUE TITLE
Coke Zero - Vertical movement

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#43] opened 2016-12-20 17:24 UTC
No idea why, but the text bar in Coke Zero moves down (actually it seems to start too high) a bit after a few seconds. This does not happen on real hardware.

[Coke Zero.ZIP](https://github.com/DirtyHairy/stella/files/664337/Coke.Zero.ZIP)

**Comment by DirtyHairy** [comment] 2016-12-20 19:41
This is caused by the FrameManager algorithm for autodetecting the first visible scanline. As the Coke logo moves upwards, the vblank area decreases in size, and the code adapts to the new height, causing this shift.

I think this is a candidate for just fixing ystart in the props (once this is supported, cf. #32).

**Comment by thrust26** [comment] 2016-12-20 19:47
I don't agree here. IMO this should work out of the box like it did in the old core too. YStart should only be there small fixes of rare exceptions.

**Comment by DirtyHairy** [comment] 2016-12-20 20:34
I think it worked in the old core because there was (in absence of a configured ystart value) a fixed line at which the visible part of the frame starts. I agree on the rare exceptions part, but I have a feeling that this actually is a rare exception when it comes to autodetecting the first visible line :smirk:

I would suggest that, at some point, we review the list of ROMs that require ystart to be configured and, after removing those that now work without it, check whether there is an improvement. If we have fewer exceptions with the new code, then I'd honestly prefer to just stick with it. If not, I am very much in favor of looking for another solution.

**Comment by sa666666** [comment] 2016-12-20 20:59
In the old core, YStart was used with _every_ ROM; it just so happened to default to 34, and that worked for most ROMs.  So it only worked 'out of the box' since the value 34 worked out of the box.

It's easy to find all the ROMs that needed specific tweaks to this.  Just search for "Display.YStart" in src/emucore/stella.pro.  If a ROM used 34, then it won't be listed in this file (since it's the default, and hence not saved).  Otherwise, it _will_ be listed, with the value needed for the applicable ROM.

A quick bit of scripting with grep and wc shows that the properties file contains 322 ROMs that need a non-default setting, out of 3288 ROMs total.

I suggest something very similar to the old core, where there is always a default YStart, except in our case it can default to 0, to give the same behaviour as the current core.  Then, if ROM properties for some ROM have a non-zero YStart, it should be applied, and turn off the autodetection of the first visible scanline.  However, as this would happen in the FrameManager class, I have no idea how to implement it there.  Basically, @DirtyHairy, if you could have the FrameManager take a parameter/method to introduce this ystart value, I could tie the ROM properties stuff into it very easily.

**Comment by DirtyHairy** [comment] 2016-12-20 21:54
I have been thinking the same :smile: I'll go ahead and add it in the next days.

**Comment by DirtyHairy** [comment] 2017-01-15 12:45
I'd like to close this one. I think there is no way that the default (which is autodetecting the first line) can be made to work with this ROM, and setting a fixed ystart value in the cartridge DB will fix it for good. @thrust26 , @sa666666 , what do you think?

**Comment by thrust26** [comment] 2017-01-15 12:57
VBlank is used to automatically set the top of the kernel display (YStart), correct?

**Comment by DirtyHairy** [comment] 2017-01-15 13:13
Yep.

**Comment by thrust26** [comment] 2017-01-15 13:24
Ok then, I doubt (besides maybe another demo) many ROMs will use variable VBlank ends.

**Comment by sa666666** [comment] 2017-01-15 18:36
Fixed with ROM properties in https://github.com/stella-emu/stella/commit/ac226eb6eb351225346bcff7aa27f176e182b66c.

**Closed by sa666666** 2017-01-15 18:36 UTC
Labels: bug, glitched game

**Comment by thrust26** [comment] 2017-01-15 21:50
Found other ROM with (**slight**) problems: Lady Bug, when switching from title to game screen, the screen rolls a few pixel up. This may happen with a number of games (e.g. Lord of the Rings, Motorodeo), which use multiple display kernels where the VBlank times may differ.

**Comment by DirtyHairy** [comment] 2017-01-15 23:04
This is the way autodetection of ystart works: if the algorithm observers a deviation from the determined start line that persists for several frames, it will switch. However, I am not sure whether this is really desirable since it is different from the way a real CRT works. An alternative would be to completely lock ystart if it stays constant for a bunch of frames. @thrust26 , @sa666666 , what do you think?

**Comment by sa666666** [comment] 2017-01-15 23:44
I would prefer that the code worked as close as possible to how a real CRT works.  But I'm not working on that part of the code, so I can't make any demands; whatever is easier on your end is fine with me.

**Comment by thrust26** [comment] 2017-01-16 07:50
I agree with Stephen.

Maybe the best solution would be to increase the vertical size so that it matches an average real CRT and base everything only on VSYNC. Then we will have black borders at top and bottom as they show on TV.

**Comment by DirtyHairy** [comment] 2017-01-17 20:53
I think what I'll do on the short run is to lock the detected ystart after 30 frames without change. After that, the algorithm behaves just like a CRT, and I guess this will be the prerequisite for reimplementing jitter anyway.

@thrust26 , your suggestion is interesting. Together with blargg, this might make for a very nice TV-like image. I guess I'll give it a try behind an option :smirk:

**Comment by thrust26** [comment] 2017-01-17 21:01
Thanks. 

Maybe we should keep in mind that the window size is variable, depending on the total scan lines. The percentage is ~92% (~240/262, ~288/312). That means the vertical pixel scaling is variable too, not only between NTSC and PAL, but between games with different total scan lines.
