### ISSUE TITLE
CX22 Resolution too high

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#70] opened 2017-01-11 07:58 UTC
@sa666666: Not specific to the new core.

The (unmodded) CX22/CX80 Trak-Ball delivers only **half** the resolution of e.g. an Atari or Amiga Mouse, a modded CX22/CX80 or other Trak-Balls modded for Atari Mouse mode.

http://atariage.com/forums/topic/243453-atari-2600-trak-ball-games/page-20#entry3668812
https://atariage.com/forums/topic/243453-atari-2600-trak-ball-games/page-20#entry3669256

BTW: There is no hyphen in CX22 or CX80. Also we should rename the controller option _CX-22 Trakball_ into eg. _CX22/CX80 Trakball_ and _CX-80 Mouse_ into _Atari Mouse_ or _AtariMouse_ (like _AmigaMouse_). The current naming causes constant confusion. It results from an old wrong assumption that CX80 work like an Atari Mouse.

**Comment by sa666666** [comment] 2017-01-12 21:02
This will probably have to wait until after the 5.0 release, but it's good to have it recorded here.

**Comment by sa666666** [comment] 2017-02-24 22:12
I think this is now fixed by https://github.com/stella-emu/stella/commit/52d3bd9df3a74509f253367e6332d5139be27991 and https://github.com/stella-emu/stella/commit/5114a8e88e4aebbe0859d73b90bcd297ed3d5361.  More testing is required, but for now it seems to work with the ROMs from the above links.

**Closed by sa666666** 2017-02-24 22:12 UTC
Labels: enhancement, missing feature

**Comment by thrust26** [comment] 2017-02-25 09:33
Great!

When will there be a next pre-release?

**Comment by sa666666** [comment] 2017-02-25 21:42
@DirtyHairy mentioned wanting to get the automated testing done before we do pre5.  So I await his answer.

**Comment by DirtyHairy** [comment] 2017-02-26 23:39
@sa666666 I was indeed planning to do that before pre5, and I also wanted to do #93 before as I strongly suspect that this will fix #83 . However, my pace has slowed slighgly since new year, and this is unlikely change in the foreseeable future (we are currently planning a house :smirk:), so those two features could still be a few weeks away, and I see no harm whatsoever in releasing pre5 without them.

I'd just like to avoid people going through the effort of regression testing the whole VCS catalog against the next release as regression testing will catch most potential issues anyway :smile:

**Comment by sa666666** [comment] 2017-02-27 00:15
In that case I will do a test release tomorrow after work.
