### ISSUE TITLE
Stella libretro bug

### ISSUE THREAD

**Issue by AngelofMe** [stella-emu/stella#903] opened 2022-06-18 18:57 UTC
stella 7.0 pre b35b2b7
stella 2014 ok
3-D Ghost Attack (USA) (Proto)
![3-D Ghost Attack (USA) (Proto)-220619-024819](https://user-images.githubusercontent.com/26894447/174452599-8b474a55-5c8c-4f10-a4b2-81d4e6354f2c.png)
![3-D Ghost Attack (USA) (Proto)-220619-024812](https://user-images.githubusercontent.com/26894447/174452601-1b483601-7929-47de-8b5e-a07aa6635cbe.png)

**Comment by sa666666** [comment] 2022-06-18 19:10
This is a duplicate of https://github.com/stella-emu/stella/issues/900.

**Closed by sa666666** 2022-06-18 19:10 UTC
Labels: duplicate
