### ISSUE TITLE
mouse captured incorrectly - MacOS

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#607] opened 2020-04-02 12:46 UTC
Latest release binary 6.1. MacOS
I have been going through some binaries, and the Kickman (paddle hack) binary when run in stella captures the mouse pointer (it disappears) and does not reappear when mouse is outside stella window. Other binaries do not show this behaviour - the mouse comes back. Is this a paddle issue/requirement?

**Comment by sa666666** [comment] 2020-04-02 12:49
@thrust26, I believe this may be related to changing the behaviour of show/hide cursor and grab/ungrab mouse, in turn related to the lightgun stuff :smiling_imp:

**Comment by thrust26** [comment] 2020-04-02 14:17
@andrew-davie Please Ctrl+G, does that help?

**Comment by andrew-davie** [comment] 2020-04-02 14:36
Yes, Ctrl-G fixes the problem. Well, the mouse appears when not over stella window.
But I'm a bit confused - the beaviour of "mouse grab" appears to be identical whether I have it on or off (pressing Gtrl-G to toggle). I see the mouse when it's not over the stella screen. I don't see it when it is over the stella screen.

**Comment by thrust26** [comment] 2020-04-02 14:56
That's an UI setting. You can enable the mouse in emulation there. Be default it is disabled.

**Comment by thrust26** [comment] 2020-04-03 13:10
@andrew-davie Did you find the settings and can we close this one?

**Comment by andrew-davie** [comment] 2020-04-03 13:13
> @andrew-davie Did you find the settings and can we close this one?

I don't quite know what you're asking. I tried different binaries. Most worked. One had different behaviour of the mouse visibility (i.e., wasn't visible when mouse left stella window).  I didn't change any settings.

Is this normal behaviour because of some auto-detect of the ROM and behaves differently?  If so, OK. If not, then it's still a bug...?

**Comment by thrust26** [comment] 2020-04-03 13:30
When the mouse is grabbed, then it cannot leave the window, so it can never become visible outside. Mouse grabbing only works for controllers which can be emulated by the mouse (e.g. paddles and trackball). Additionally you can select if you want your mouse visible within emulation (default is off).

Maybe you can be a bit more specific about the binaries you used and what happened with the mouse there?

**Comment by andrew-davie** [comment] 2020-04-03 13:34
Sure. My initial post gave the binary. I did not change any settings for this binary.
Other binaries show correct mouse pointer behaviour. That binary behaves differently - the mouse pointer is not visible at all. I understand about mouse pointer being invisble within emulation. But this binary shows no mouse pointer anywhere -- emulation window and desktop.
My question - if I do not change settings for a binary, in other words load it like any other binary - then should the mouse pointer disappear because of something special about that binary?

**Comment by thrust26** [comment] 2020-04-03 13:38
The Kickman hack is a paddle game and auto detected as such. If you have mouse grabbing enabled (see Input dialog), then you will not be able to move the mouse outside the window. 

This is not a bug, but a feature. Without mouse grabbing, when you play a paddle game with the mouse, you risk loosing control by exiting the emulation window.

**Comment by andrew-davie** [comment] 2020-04-03 13:40
OK, this can be closed then. I actually asked this question the very last sentence of my original post.

**Closed** 2020-04-03 13:41 UTC
Labels: help wanted
