### ISSUE TITLE
Wrong frame displayed in debugger.

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#115] opened 2017-04-08 12:00 UTC
When you go at the start of a frame (using "Frame+1", "Step" or "Scan+1") the TIA Display in the debugger is 2 frames behind instead of 1.
That's also what is displayed as a grayed out background if stepping the emulation mid screen.

This simple test rom just displays a frame counter (in hex) all over the screen and shows the issue:

Start of a frame (the display should show the previous completed frame): 
![frame1](https://cloud.githubusercontent.com/assets/24704739/24828709/583de83c-1c63-11e7-9a92-687677de69cf.png)

Mid of a frame using "Scan +1":
![frame2](https://cloud.githubusercontent.com/assets/24704739/24828712/64207ee4-1c63-11e7-83a8-9ec73b11e879.png)

Start of next frame:
![frame3](https://cloud.githubusercontent.com/assets/24704739/24828714/6d7ce040-1c63-11e7-9dfa-e4aa17376366.png)

Stella 4.7.3 has the same issue.

[framecounter.zip](https://github.com/stella-emu/stella/files/907425/framecounter.zip)

**Comment by sa666666** [comment] 2017-04-25 22:53
Confirmed.  It seems to related to double-buffering, where the image you're seeing the frame before, not the current one.  Fixing this could be somewhat difficult ...

**Comment by sa666666** [comment] 2017-05-28 16:29
This is now fixed in https://github.com/stella-emu/stella/commit/79d8ed001087cdc381f6cbb216ca5eb2bbabb5cb.  It was due to double-buffering in the both the TIA class (current and previous buffer) as well as double-buffering at the rendering level (OpenGL, DirectX, etc).

Removed the double-buffering within the TIA, which fixes this but breaks phosphor mode.  Fortunately, we have new code for this from Thomas that doesn't depend on the previous framebuffer in TIA (issue https://github.com/stella-emu/stella/issues/75).

**Closed by sa666666** 2017-05-28 16:29 UTC
Labels: bug, target 5.0

**Comment by thrust26** [comment] 2017-05-28 16:38
> Fortunately, we have new code for this from Thomas that doesn't depend on the previous framebuffer in TIA 

Are you sure? Probably I miss something, but any phosphor effect has to know about the previous frames.

**Comment by sa666666** [comment] 2017-05-28 17:14
Yes.  Your code does indeed have another buffer for the previous frame, but it isn't the one that was in the TIA class (myPreviousFrameBuffer).  So I am free to remove that one, and with your new code, phosphor will work again.

**Comment by thrust26** [comment] 2017-05-28 17:19
Ah, IIRC my code uses the previous **displayed** buffer, while the old code used the previous **rendered** buffer. Correct?

**Comment by sa666666** [comment] 2017-05-28 17:30
I don't remember the specifics.  Give me an hour, and you can see for yourself when I commit it :smile:

**Comment by thrust26** [comment] 2017-05-28 17:32
Did you make it work with Blargg too???

**Comment by sa666666** [comment] 2017-05-28 17:50
Not yet; that will be my next job.
