### ISSUE TITLE
INPTx registers not working in all cases

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#17] opened 2016-12-05 22:37 UTC
The recent addition of the PaddleReader class allows paddle games to work correctly.  However, other games that use those inputs are now broken.  In particular, ROMs using keypad controller (Alpha Beam with Ernie).  Also, Compumate ROMs make extensive use of these registers, and the display isn't even showing up there.

I'm not sure if there's a bug in the PaddleReader class itself, or a difference in how the relevant parts of Stella now interact with the new code (in particular, Keyboard.cxx and CompuMate.cxx).  I suspect the latter.

**Comment by DirtyHairy** [comment] 2016-12-05 23:24
Thanks, @sa666666 , I'll look into it.

**Comment by DirtyHairy** [comment] 2016-12-07 23:50
Fixed in afae00a .

This suggests a possible keypad emulation bug that also affects the old core: writing value A to SWTCHA  and later value B without reading from INPT[0123] between the two writes will have no effect on the emulation. On real hardware, the first read will potentially discharge the capacitor (depending on keyboard state) and thus affect subsequent reads even after B is written. The new core does slightly better than the old one as it updates the readout circuit state each frame, but this won't help if both writes happen within the same frame. Fixing this properly and efficiently would require crosstalk between RIOT and TIA (i.e. updating the readout circuit state before SWTCHA is written).

**Comment by sa666666** [comment] 2016-12-08 19:16
We should consider your suggested improvement for a future release; I want to have the emulation as accurate as possible.  Obviously there is much more to do first, of course.

**Comment by DirtyHairy** [comment] 2017-07-18 20:54
I think this has come back from the grave to [haunt us](http://atariage.com/forums/topic/267810-stella-50-released/page-2#entry3808740)

**Comment by DirtyHairy** [comment] 2017-07-18 21:33
It seems that at least BASIC is affected, and a bit of printf debugging suggests that the issue is indeed the order in which the paddle resistance is updated: multiple writes to SWCHA happen per frame.

**Comment by sa666666** [comment] 2017-07-18 21:39
Many other controllers use paddle inputs too, so this makes me think the problem is now in Keyboard.cxx.

**Comment by sa666666** [comment] 2017-07-18 21:44
Synthcart plays a different sound on each key, and uses the keypad controller.  For me, q/w/z/x don't work, which correspond to keypad 4/5*/0, respectively.

[synthcart.zip](https://github.com/stella-emu/stella/files/1157376/synthcart.zip)

**Comment by DirtyHairy** [comment] 2017-07-18 21:54
I think the solution is to update the paddle readout circuit whenever an analog pin changes state. I am working on this, but I am not sure whether I'll finish it today :smirk:

**Comment by sa666666** [comment] 2017-07-18 22:01
Can we perhaps try to fix this at a lower level, so it doesn't come back to haunt us again :smile:

Also, would it be worthwhile to now implement the crosstalk between TIA and RIOT that you mentioned above, so this area of the code is fixed for good (or is that what you're already doing)?

**Comment by DirtyHairy** [comment] 2017-07-18 22:03
That's basically what I am doing: I am modifying `Controller` to force all analog pin updates through a method that calls a callback after updating the pin state. The callback will be wired to the TIA, which in turn updates the readout circuit. I think this is the right place --- RIOT was a bit too enthusastic I think :smile:

**Comment by sa666666** [comment] 2017-07-18 22:19
The problem of course is that Controller::write() and friends are empty virtual methods, only implemented by classes that need them.  So maybe that will force the classes overriding them to do this instead??

**Comment by DirtyHairy** [comment] 2017-07-18 22:21
I added a separate protected method `updateAnalogPin`. Only analog updates are routed through this, and it is separate from `Controller::write` and company ;)

**Comment by DirtyHairy** [comment] 2017-07-18 23:46
I was a bit hasty; there is something else going wrong, and I am going to need considerably more debugging in order to find out what it is. Later this week...

**Comment by DirtyHairy** [comment] 2017-07-19 00:21
Got it! Actually, this is not a bug at all, but a lesson in electronics :smirk: Typing it out is too much for tonight though, so I'll add more detail (and commit a fix) later.

**Comment by DirtyHairy** [comment] 2017-07-19 14:12
Time for a break (I skipped lunch today) and elaborate a bit :smirk:

**The analog readout circuit**
In this circuit, a capacitor is connected to pin 9 (5) (with a small series resistor). While bit 7 of VBLANK is asserted, the capacitor is pulled to ground and discharged. After bit 7 has been cleared, the capacitor starts charging through the connection to pin 9 (5) and, after the voltage reaches a threshold, INPTx will read 1.

**Paddles**
For the paddle controller, the paddle potentiometer is used as a variable resistor (not as a divider) and connects pin 9 (5) to pin 7 (+5 Volts). Changing the paddle position changes the resistance and such the rate at which the cap charges.

**Keyboard**
The keyboard controller connects pin 9 (5) to pin 7 (+5 Volts) via a pullup resistor and to pin 1 / 2 / 3 / 4 (the RIOT GPIO pins configured as output) via the key matrix (the GPIO pin selects the row). In order to read one of the keys you set the corresponding GPIO pin to 0 (pulling it to ground) and discharge the cap. If the key is pressed, the cap is connected to ground and stays discharged (or discharges) -> INPTx reads 0. If it is unpressed, the cap charges via the pullup -> INPTx reads 1.

The important part is that this is different from connecting pin 5 (9) to +5 Volts via a potentiometer. For a paddle controller, the cap charge will always increase after VBLANK is cleared, while reading a pressed button on the kids controller will actively discharge it even if it was charged before.

Stella (and all other emulators, I guess) model analog input with a single resistance value which isn't enough to accurately model what is happening. A better choice would be a tuple of voltage and resistance, and the only precise way would be to model the whole circuit within the controller itself :smile:

Instead of dumping the cap if the button is pressed, Stella maxes out the resistance value. The old code contains a check whether the resistance is maxed out and always returns 0 in this case. This is not a correct physical description as the resistance can become large for other reasons as well (in which any existing charge is held if the voltage is unchanged), but it does the job for the actual controller implementations.

The new code calculates the charge buildup on the cap between resistance changes. Maxing out the resistance immediatelly after VBLANK is cleared will prevent the cap from charging, but it will not discharge it. This is why some games work, and some don't.

I think the solution is to discharge the cap if the "resistance" is maxed out. Technically, this is not correct and *would* fail for actual high resistances, but those never occur for any real-world controller, so I think it is good enough :smirk: I have tested this and it works, but I also have made the change I talked about before which and I want to up and commit, too --- this will resolve any timing issues in updating the circuit state for good.

**Comment by sa666666** [comment] 2017-07-19 14:24
Sounds like an excellent analysis of the problem.  I particularly like the last sentence 'this will resolve any timing issues in updating the circuit state for good.' :smile:

**Comment by thrust26** [comment] 2017-07-19 15:27
Something for 5.0.1 I suppose? 😉

**Comment by ale-79** [comment] 2017-07-19 15:37
Other controller using the paddle lines are Genesis pads and the Booster Grip. 

It seems that genesis pad support is broken too in 5.0 (I just tried a few of the 2 button hacks from this thread: [http://atariage.com/forums/topic/158430-rom-hacks-to-support-2-buttons-with-genesis-controllers](http://atariage.com/forums/topic/158430-rom-hacks-to-support-2-buttons-with-genesis-controllers))

On Genesis pad, pin 9 is connected to an ouptut of an IC (74157 in the original 3-buttons controller) that is at logic "0" if button "C" is pressed and "1" otherwise.

The Booster grip, just connects the paddle lines to pin 7 (+5v) when the trigger (pin 5) or top button (pin 9) are pressed, and leave them flaoting otherwise.

**Comment by sa666666** [comment] 2017-07-19 15:38
Definitely.  I haven't done a point-0 release yet that didn't have something we missed.  But considering the huge number of features added, and the amount of code churn in 5.0, missing only just this one thing is very good.

I suggest we test all types of controllers for the next release, because most of the other ones use the INPTx registers in some way too.

Like @DirtyHairy, the ROM I used for testing was Alpha Beam with Ernie, and of course that ROM worked fine :imp:

**Comment by DirtyHairy** [comment] 2017-07-21 22:51
Implemented and fixed in 0d5d3de4

**Comment by sa666666** [comment] 2017-07-21 23:48
Good work on this; I didn't expect it would need to be so involved.  But it's really nice that this is now emulated correctly at a lower level.  It works with all the test ROMs I tried, so I think we're done.  Now, would you consider looking at issue #176 before the next point release? :smile:

**Comment by thrust26** [comment] 2021-03-22 15:09
Sorry, but I think we need another look. 

The attached binary worked until 5.0 and stopped working with 5.0.1 where this fix was added. And it is reported to work on real hardware (@sa666666 please double check). The problem is that you cannot move the ships.

[Alpha Beam (12-22-82).zip](https://github.com/stella-emu/stella/files/6183207/Alpha.Beam.12-22-82.zip)

**Comment by thrust26** [comment] 2021-03-22 15:25
Changing `MIN_RESISTANCE` from 5600 back to 0 fixes the issue. Where did that number come from?

**Closed** 2021-09-06 21:27 UTC
Labels: bug
