### ISSUE TITLE
Activision Ice Hockey - Occasional 'dots'

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#83] opened 2017-01-19 07:38 UTC
Occasional 'dot' appears on the left side of screen when puck is in the upper half of the rink; appears on the right side of the screen when puck is in the lower half of the rink.  Imitates movement of puck momentary then disappears.
http://atariage.com/forums/topic/259633-testing-the-new-stella-tia-core/page-3#entry3675034

Happens in Stellerator too.

**Comment by DirtyHairy** [comment] 2017-01-21 13:09
That could be fixed by increasing the ENAMx delay from 1 to 3. Which reminds me that I don't have anything apart from guesswork on how long this shoud be in the first place :smirk: I'll write a test to find out, then I can hopefully close this.

**Comment by DirtyHairy** [comment] 2017-01-23 22:06
Too bad, the test confirms that the delay is 1. So, I have to continue looking. What I know is that the 'dot' is a copy of the missiles that constitute the bat handle, so its movement is actually mimicking the bat handle. This might be related to NUSIZ during / before / after draw. I'll revisit this issue after I am done with NUSIZ-during-draw.

For reference, a have  [attached](https://github.com/stella-emu/stella/files/725072/testcases.zip) my two testcases (one for RESMx, one for RESBL). The source can be found in the [6502.ts repo](https://github.com/6502ts/6502.ts/tree/master/aux/2600/enax_delay). What the test shows are Missile 0 / Ball (orange) overlayed over Missile 1 / Missile 0 (white). The first line shows the plain sprites for reference. On the next lines, ENAM0 / ENABL is triggered at the same cycle the sprites were originally positioned, while each lines moves the sprites one pixel to the left via hmove. The color switch selects between ENAM0 / ENABL initially being on and off.

After the reference line, there are three lines before the effect of ENAM0 / ENABL becomes visible. As there is a one pixel delay between the position where RESMx / RESBL was strobed and the first pixel, this means that there is a one pixel delay.

The test images look like this in all emulators that I tested and on my PAL TV:

![enabl_delay](https://cloud.githubusercontent.com/assets/2444224/22224854/7674d014-e1c0-11e6-881a-f1e85a56e08c.png)

![enabl_delay_1](https://cloud.githubusercontent.com/assets/2444224/22224833/5edcb75a-e1c0-11e6-90ed-f000a56ad886.png)

**Closed** 2017-03-24 21:31 UTC
Labels: affects 6502.ts, glitched game

**Comment by DirtyHairy** [comment] 2017-03-24 21:33
After reproducing this issue in two-player mode (much easier to debug, should've thought about that earlier :smile:), it turns out that this was caused by RESMPx: it seems that decodes of the missile draw counter are ineffective while RESMP is active.
