### ISSUE TITLE
Processor Status flags set in Developer Mode

### ISSUE THREAD

**Issue by DNSDEBRO** [stella-emu/stella#705] opened 2020-09-19 22:18 UTC
I've noticed an issue with the processor status flags when starting a ROM in Developer Mode. 

At the start of my ROM, I set clear DECIMAL mode with CLD and never set it to decimal mode. In my ROM I manipulate the stack to perform the BALL enable trick by pointing the stack to ENABL. When I perform a PHP, I notice the DECIMAL flag is getting manipulated. This is causing arithmetic issues since values between 10d and 15d are being treated as decimal values.

It appears the BRK and IRQ are affected as well.

I only see this issue when I start Stella in Developer Mode. This doesn't happen when I switch to Developer Mode after the ROM has started.

I'm using version 6.1.2 at the moment.

**Comment by sa666666** [comment] 2020-09-19 22:25
Before we go any further, I would prefer that you use the very latest version; 6.2.1.  To make sure that this problem isn't already fixed in the latest code.  Probably not likely, but it's better than wasting time tracking down an non-existent bug.

**Comment by DNSDEBRO** [comment] 2020-09-19 23:49
Good point.

I just verified the same in 6.2.1.

**Comment by thrust26** [comment] 2020-09-20 06:08
@DNSDEBRO I cannot reproduce the issue, also Combat which uses the same trick is working in developer mode. 

Can you provide a test ROM/code, please?

**Comment by DNSDEBRO** [comment] 2020-09-20 23:33
That's exactly what I'm doing Thomas and causing my issue. Thank you. I can upload the ROM if you'd still like it but this appears to not be an issue. If I'm understanding correctly after doing research the PHP command could alter the values too.

**Comment by thrust26** [comment] 2020-09-21 05:54
PHP should not change any flags, only PLP.

**Closed** 2020-09-21 05:55 UTC
Labels: invalid
