### ISSUE TITLE
Screenshots large and cropped 

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#599] opened 2020-03-30 13:28 UTC
Screenshots outside the debugger are large and cropped:
https://atariage.com/forums/topic/304258-stella-61-released/?do=findComment&comment=4495032
https://atariage.com/forums/topic/304230-stella-61-released/?do=findComment&comment=4495274

**Comment by sa666666** [comment] 2020-03-30 13:36
Can't reproduce in Linux.  And I don't think you @thrust26 can reproduce in Windows either.  So it may be Mac-specific.

**Comment by DirtyHairy** [comment] 2020-03-30 22:50
That's a scaling bug I introduced with native retina support. Fixed in 4d99bca2c.

**Closed by DirtyHairy** 2020-03-30 22:50 UTC
Labels: bug
